### ISSUE TITLE
Social Promos for ADA.gov

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1000]
**Goal of project:**
Ultimately, we want to create social promotions that will drive DOJ social followers and ADA influencers to visit beta.ada.gov and give us feedback in order to help drive feature and content prioritization/development.

**Platforms we're targeting:**
* Facebook
* Twitter
* Instagram

**Look and feel:**
HHS does a good job of creating clear/informative social graphics. I've included samples at the bottom of this ticket.

**Working text (still being finalized)**

Headline: Reimagining ADA.gov 

Body text: We’re building a new site! Help shape the future and **give feedback at beta.ADA.gov** 

Post Description Text:
Track our progress as we work to make ADA.gov more accessible, user friendly, and dynamic. Share your feedback today at beta.ada.gov!

**Images/look and feel**
I was thinking of using a dimmed out version of the beta.ada.site, but there is text there...not sure if that text will interfere with the other message text we're including.  As for look/feel, I'm assuming we will just use the same colors/fonts as the site.

**Sizes needed**
(taken from https://sproutsocial.com/insights/social-media-image-sizes-guide/)

Twitter: 1200x628
Facebook: 1200x630
Instgram: 1080x1080
- If there is time to do an Instagram story size, please do: 1080x1920

**Tracking links**

Twitter
https://beta.ada.gov/?utm_source=twitter&utm_medium=social&utm_campaign=ada-anniversary&utm_content=080121

Facebook
https://beta.ada.gov/?utm_source=facebook&utm_medium=social&utm_campaign=ada-anniversary&utm_content=080121

Instagram
https://beta.ada.gov/?utm_source=instagram&utm_medium=social&utm_campaign=ada-anniversary&utm_content=080121

==
Sample HHS images

![hhs1](https://user-images.githubusercontent.com/6254621/126911746-5e974353-3b0e-4a28-9c1b-cc88f31bd17c.jpg)
![hhs2](https://user-images.githubusercontent.com/6254621/126911747-3d1decd0-0fb0-489c-aef6-45bf5b9ce015.jpg)
![hhs3](https://user-images.githubusercontent.com/6254621/126911748-3d2d5afe-18ca-43c2-acba-7bc6938b17fc.jpg)

**Comment by emilycryan** [comment]
Two versions - this would be the Facebook / Twitter sizes (they are only one pixel different) LMK thoughts on this approach. If these feel like the right direction, we can make the other sizes once we have final text. CC @randyabramson 

![1200x628-2](https://user-images.githubusercontent.com/73443807/127022323-cf1d356c-6d11-46f4-8866-2fa6d77506d4.png)
![1200x628](https://user-images.githubusercontent.com/73443807/127022334-eb10fc5d-76d1-42a2-bb00-eb36537990bf.png)

**Comment by randyabramson** [comment]
@emilycryan nice start!

Note that this line of text is not in the graphic (it goes in the text area below the graphic): Track our progress as we work to make ADA.gov more accessible, user friendly, and dynamic. Share your feedback today at beta.ada.gov!

Also, is there a way to make the headline smaller? We want the 'give feedback at beta.ada.gov' to pop

**Comment by emilycryan** [comment]
![1200x628-2b](https://user-images.githubusercontent.com/73443807/127025868-fd0387dd-8cd9-4802-ac2f-36232083280f.png)

Another option, @randyabramson

**Comment by emilycryan** [comment]
@randyabramson I don't want to shrink the header b/c that breaks all of our typography rules here and would look strange. This allows both to be about the same size.

**Comment by randyabramson** [comment]
@emilycryan that works

**Comment by emilycryan** [comment]
@randyabramson do you prefer the yellow tint (which mutes the images a bit) or the cleaner all white?

**Comment by randyabramson** [comment]
@emilycryan  I like the yellow

**Comment by emilycryan** [comment]
Ok, here they are @randyabramson 
![1080x1920-Final](https://user-images.githubusercontent.com/73443807/127035216-d0536ae7-ba05-49d3-a4d0-c6a2f009a831.png)
![1080x1080-Final](https://user-images.githubusercontent.com/73443807/127035241-c1cea4cc-0457-4265-99ca-a82ce85fc543.png)
![1200x630-Final](https://user-images.githubusercontent.com/73443807/127035244-452ab890-8d8d-4875-b3ff-1dd402770528.png)
![1200x628-Final](https://user-images.githubusercontent.com/73443807/127035247-270cd38b-4be6-49f9-90f4-9514926fae37.png)

**Comment by randyabramson** [comment]
@emilycryan - these were all approved...thank you!
