### ISSUE TITLE
Placeholder - plan for attachments copy

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1005]
Review attachments language display.

Maybe italics just translates to 'disregard' to users?

Or do we need new language completely?

![image](https://user-images.githubusercontent.com/6254621/128081298-c5406ac2-870c-4c35-9bb9-e9207d4a8e78.png)

**Comment by emilycryan** [comment]
Two options for text treatment based on existing styles. Content is not final but it includes information letting the user know that we cannot accept attachments. CC @randyabramson @blaughman 

![Personal Description -Updated text, option 1](https://user-images.githubusercontent.com/73443807/128352110-831519b0-fc59-4258-a3a7-3c5725b05d03.jpg)
![Personal Description -Updated text, option 2](https://user-images.githubusercontent.com/73443807/128352120-9c36734a-e2c2-4686-9e7a-f3659d735f63.jpg)

**Comment by randyabramson** [comment]
I like option 2. @blaughman ...your thoughts?

Also @emilycryan do we need the second line 'if you provide details of these materials...' ?

**Comment by blaughman** [comment]
@randyabramson @emilycryan Personally, I prefer option 1.  I like getting it all out there before they get to the text field.  Once they enter their description, I would think they would immediately want to click 'Next' without reading the disclaimer.  JMO.

**Comment by emilycryan** [comment]
I don't feel strongly either way re. where the location of the wording goes. By this point, many users may be fatigued by the process so it likely won't make a huge difference where it belongs as to their likelihood of reading it. As for the second sentence, I added it to help the user understand why we were asking them to tell us what documentation they have yet not allowing them to actually upload it. I could imagine someone saying "if I can't upload this stuff, why do you need to know about it now?" I'll let you two decide what we move forward with here. Just having something is better than nothing and I think this may help with the confusion around not being allowed to upload their documents and photos/videos. CC @randyabramson @blaughman

**Comment by randyabramson** [comment]
@emilycryan would it be bad to take 'the best of both worlds' here and bold the 'any supporting materials' text (option 2) and add the text below? 

I agree we should add the explainer text, but the point of this ticket was to solve for that people aren't seeing the text asking them to describe the materials

cc: @blaughman

**Comment by emilycryan** [comment]
@randyabramson @blaughman 
![Attachments-Copy](https://user-images.githubusercontent.com/73443807/128730992-722ba901-0a47-461d-bd0b-c4b05dfde13a.jpg)

**Comment by blaughman** [comment]
@chinelo-ikejimba We need to confirm your thoughts on language and placement for this language.  This stems from the public's long standing request to add attachments when they are submitting a complaint.  Our security policy does not allow attachments from the public facing side.  We have never been clear with the public on this topic.  Before you joined the project, we had done the work above.

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson 

I recommend **Option 1** that has the explanation directly above the text box. Ideally, it'll help set expectations before they start typing in the text box.

@billyhunt @louh here is the text:

> While you **cannot** submit these materials through this site, we may request copies of these from you at a later date. If you provide details of these materials, we can know what will be most helpful for your report.

**Comment by blaughman** [comment]
I'll submit this for translation.

**Comment by chinelo-ikejimba** [comment]
@blaughman sounds good.

**Comment by blaughman** [comment]
Closing this card.  #1179 is the updated card with translations.
