### ISSUE TITLE
Search - Billy to confirm if we just go with OR to start or And/Or

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1007]

**Comment by randyabramson** [comment]
@billyhunt @ilodidoj Emily, Bill and I were chatting and we would prefer if the separate url search had and/or functionality out of the gate in order to truly distinguish what we are offering on legacy search. Let us know if that is possible.

**Comment by billyhunt** [comment]
I think we might break the work into two distinct PR's, but could only announce the release when we do the frontend portion.  That way we can make sure it works first.  Does that sound OK to you?

**Comment by randyabramson** [comment]
@billyhunt that works.

**Comment by randyabramson** [comment]
Decision was to create two tickets for this. Closing this ticket and will replace with 2 new tickets.
