### ISSUE TITLE
Search - update first slice mocks

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1009]
Update mocks for first slice:

1. Personal Description only
2. And/Or is still TBD
3. Do we need a character count?
4. Any changes to helper text?
5. What else?

**Comment by emilycryan** [comment]
Newest screens for initial design / dev work: https://gsa.invisionapp.com/console/share/XC2X84XU5W/734451939

All items from above have been updated. 

- Helper text is updated within the design
- We shouldn't need a character count 
- Start with AND/OR (we need to settle on this decision and just go with it - I'd rather get feedback from specialists after we implement it and they've used it)
CC @randyabramson @blaughman

**Comment by randyabramson** [comment]
The mocks in this thread are final. I am going to close this and enter a new ticket.
