### ISSUE TITLE
Search - create separate url

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1010]
Create separate url

**Comment by randyabramson** [comment]
Blocked until other decisions are made

**Comment by randyabramson** [comment]
@ilodidoj @billyhunt Is there any guidance you can provide on this 'first step' for search? 

Is it simply creating a URL for the new search? If there's a lot more detail, we can talk on Wednesday, but we thought it would be great to get this into 'ready for dev'.

**Comment by billyhunt** [comment]
I think we can put this in "Ready for Dev"

I was thinking the new view could be _URL_/form/view-beta for the new search, and continue to use  _URL_/form/view for the old one.

@ilodidoj, @randyabramson, @louh, thoughts?

**Comment by randyabramson** [comment]
Good by me @billyhunt

**Comment by billyhunt** [comment]
After initial implementation, we decided we no longer need this.
