### ISSUE TITLE
SPL Form Letter - Spanish

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1013]

**Comment by blaughman** [comment]
https://github.com/usdoj-crt/crt-portal-management/files/6735920/SPL.Form.Letter_SP.docx

**Comment by blaughman** [comment]
Special Litigation Section removed from header.  Please use this version.
[SPL.Form.Letter_SP (3) with Header Edit.docx](https://github.com/usdoj-crt/crt-portal-management/files/6976810/SPL.Form.Letter_SP.3.with.Header.Edit.docx)

**Comment by blaughman** [comment]
Function works as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Function works as intended in Staging.  Ready for Production deploy.

**Comment by randyabramson** [comment]
Works as intended on CHROME and EDGE. Closing
