### ISSUE TITLE
SPL Form Letter - Traditional Chinese

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1014]

**Comment by blaughman** [comment]
[1368276.SPL.Chinese-Traditional.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7009305/1368276.SPL.Chinese-Traditional.final.docx)

FBI approved version

**Comment by blaughman** [comment]
Form letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Function works as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Function works as intended in Staging.  Ready for Production.

**Comment by randyabramson** [comment]
Not sure how to test. Closing for now.
