### ISSUE TITLE
SPL Form Letter - Tagalog

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1018]

**Comment by blaughman** [comment]
[1368287.SPL.Tagalog.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7009306/1368287.SPL.Tagalog.final.docx)

FBI approved version

**Comment by blaughman** [comment]
There are some minor edits needed for this form letter as well.  We should remove the highlighted English text and characters. @ilodidoj @billyhunt @louh @randyabramson @emilycryan 
[Tagalog Edits Needed.docx](https://github.com/usdoj-crt/crt-portal-management/files/7099832/Tagalog.Edits.Needed.docx)

**Comment by billyhunt** [comment]
This one seems clear cut!

**Comment by billyhunt** [comment]
Going to wait on official language translation.  CC @blaughman @ilodidoj @louh
