### ISSUE TITLE
Update uswds to 2.5.1

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1023]
## Summary

Dependabot reports a vulnerability in the `tar` and `trim-newlines` packages that is currently a dub-dependecy of the `gulp-sass` package. To clear these alerts by updating the affected packages, we will need to update `gulp-sass` to v5.x. Before we can do this, we also need to update the US Web Design System package (`uswds`) to version 2.5.1.

## Detail

`gulp-sass@5.0.0` updates subdependencies which update `tar` and `trim-newlines` to newer versions that clear the Dependabot security alerts (See #1012). However, this major version change introduces a breaking change that removes the deprecated `node-sass` package in favor of the currently-supported, canonical Sass package `sass`. In order to use this package, we must also bump up the version of the US Web Design System to `uswds@2.5.1`, which also switches out `node-sass` for `sass`.

The USWDS introduces new features and possibly breaking changes at each minor version release. We will need to incrementally update USWDS until we reach at least version 2.5.1, at which point we can then make the package ecosystem updates we need to resolve the Dependabot alerts.

Notes from local testing of this upgrade process:

- Updating to uswds@2.4.0 and uswds-gulp to just before the change to 2.5.0 is straightforward. No known issues.
    - There are sass variable changes in 2.2.0
    - There are footer markup changes in 2.3.0
    - I do recommend doing this as a series of incremental updates of each minor version, addressing changes along the way, until we reach 2.4.0.
- There will be a big change when uswds-gulp updates to uswds@2.5.0, because that comes with a host of dependency changes, including the change to the sass compiler. We will need to manually port over gulpfile changes. Also, it no longer imports browsers list and instead looks for .browserslistrc so we need to create that ourselves.
    - Make sure our package.json matches dependencies in uswds-gulp - bugs occur if versions are too new, it should track with uswds-gulp versions.
    - To do: update markup in templates. See changelog: https://github.com/uswds/uswds/releases/tag/v2.5.0. Old markup won't break, but we should track recommended updates in markup.
    - Note: uswds has not yet actually updated its use of the slash-div (which will be deprecated in dart-sass)
        - Twitter thread on this https://twitter.com/mayabenari/status/1398768190860140544
- This supercedes doing #1020, as the `node-sass` package will be removed during this process.

**Comment by ilodidoj** [comment]
@louh let's concentrate on USWDS as priority than the gulf upgrade.  This seems to be right approach to tackle the current situation.

**Comment by louh** [comment]
Update: upon closer inspection, `.browserslistrc` does not need to be updated here. It will be done in a future update.

**Comment by randyabramson** [comment]
Not sure how to test. Closing for now.
