### ISSUE TITLE
Search 1st Slice: Test OR function on new URL

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1025]
## User story:
As a product tester, I would like to see if the OR functionality will work on the new search URL

## Objective:
The goal is to ensure that the new URL/environment can support the OR function before changing the UI

## Ticket background:
One of our attorney's asked for a complex search that involved multiple spellings of a location, multiple keywords and multiple states. We also saw a lot of efficiency come from the Power Keyword Search workaround. Lastly, we wanted to attract a new user group for the Portal: attorneys who would have very specific and complex queries. All of this led us to the idea of making a more robust keyword search.

## Acceptance criteria:

- [ ] Make sure global OR search works (sample from current environment: https://crt-portal-django-prod.app.cloud.gov/form/view/?status=open&status=new&violation_summary=covid&violation_summary=COVID&violation_summary=mask&violation_summary=masks&sort=-create_date&page=1&per_page=15)

- [ ] Test complex sample OR search (sample from current environment: https://crt-portal-django-prod.app.cloud.gov/form/view/?assigned_section=DRS&status=new&status=open&status=closed&violation_summary=COVID&violation_summary=covid&violation_summary=corona&violation_summary=covid19&violation_summary=vaccine&location_state=LA&location_state=IL&sort=-create_date&page=1&per_page=15)

- [ ] Make sure section level OR search works (sample from current environment: https://crt-portal-django-prod.app.cloud.gov/form/view/?assigned_section=ADM&status=open&status=new&violation_summary=covid&violation_summary=COVID&violation_summary=mask&violation_summary=masks&sort=-create_date&page=1&per_page=15)

**Comment by randyabramson** [comment]
[complex-queries-tickets.xlsx](https://github.com/usdoj-crt/crt-portal-management/files/7018443/complex-queries-tickets.xlsx)

@billyhunt - we can get even more complex. but let's start testing with this list. I will most likely add more when I have more time.

**Comment by randyabramson** [comment]
@billyhunt when the code is ready on DEV, we can use the below to test against

[complex-queries-tickets.xlsx](https://github.com/usdoj-crt/crt-portal-management/files/7021809/complex-queries-tickets.xlsx)

**Comment by billyhunt** [comment]
Hi @randyabramson.  Right now the OR search only works for violation_summeries.  I would not mind putting that in the wild first before we add it to the other fields.  What do you think?

**Comment by randyabramson** [comment]
Thanks for the update @billyhunt  - Does that mean that the AND function will no longer be active? And will all of the other filters continue to work as is?

It's fine if AND is disabled for a bit...we just need to let the Intake Specialists know. Also, is there any sort of work around to perform an AND search if needed (url based search, etc.)?

cc @blaughman @emilycryan
