### ISSUE TITLE
Search 1st Slice: Create And/OR search function on Personal Description field

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1026]
## User story:
As an attorney, I want to be able to search the personal description using AND or OR operators on the PERSONAL description field only

## Objective:
The goal of this ticket is to give attorneys the ability to quickly find reports that represent patterns and trends around locations, etc.

## Key result:
More tickets flagged for 'secondary review'

## Ticket background:
One of our attorney's asked for a complex search that involved multiple spellings of a location, multiple keywords and multiple states. We also saw a lot of efficiency come from the Power Keyword Search workaround. Lastly, we wanted to attract a new user group for the Portal: attorneys who would have very specific and complex queries. All of this led us to the idea of making a more robust keyword search.

## Testing criteria:
Attorney Test:

* Incident location = Illinois
* Personal Description = covid OR corona OR coronavirus OR vaccine OR hy-vee OR hyvee OR hy vee OR mejer OR meir OR rite aid OR rite-aid OR riteaid OR Kroger

Vaccine test
* Personal Description = covid AND mask AND rights
* Status = new, open and closed
(results should match https://crt-portal-django-prod.app.cloud.gov/form/view/?per_page=15&status=new&status=open&status=closed&violation_summary=covid,%20mask,%20%20rights&page=1)

## Assumptions:

- [ ] Search queries can support spaces between words, special characters, etc.
- [ ] New AND/OR toggle filter will work in conjunction with all other search filters
- [x] Search is case agnostic
- [ ] Partial words should surface full word results (example: search for 'mask' gives results for 'masks')

**Comment by blaughman** [comment]
Function works as intended in Staging.  Ready for Production deploy.

**Comment by randyabramson** [comment]
Works as intended. Great work @billyhunt @louh @emilycryan Closing.
