### ISSUE TITLE
Improve accessibilty on date inputs

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1029]
## Summary

We have received a report that a user test with the JAWS screen reader can get stuck at date input elements (e.g. step 5 of the report form). The user expects this to be a text input box, but we have implemented a number input (which the screen reader calls a "spinbox").

## Suggested Actions

Recent research done by the team behind the [US Web Design System](https://github.com/uswds/uswds/pull/3392) and at [GOV.UK](https://design-system.service.gov.uk/components/text-input/#numbers) confirms our observations that [numeric inputs still carry many usability problems](https://design-system.service.gov.uk/components/text-input/#numbers). Thankfully, they have also issued guidance on a solution that we can benefit from.

We should change date inputs from `number` to `text` inputs. [This example code snippet](https://github.com/uswds/uswds/pull/3392/files) shows how we can update our output HTML to be text inputs and still use a browser's built-in number validation.

For example, instead of:

```html
<input class="usa-input usa-input--inline" aria-describedby="dobHint" id="date_of_birth_1" name="date_of_birth_1" type="number" min="1" max="12" value="">
```
use:

```html
<input class="usa-input usa-input--inline" aria-describedby="dobHint" id="date_of_birth_1" name="date_of_birth_1" type="text" maxlength="2" pattern="[0-9]*" inputmode="numeric" value="">
```

This change was introduced in uswds@2.7.0, however, we do not need to update the uswds to make this change. We are ready to modify our HTML output right now.

There are three locations to update our date input elements:

1. On the user-facing form (step 5)
2. Two date inputs on the pro form

## Acceptance Criteria

A user with the JAWS screen reader should no longer be stuck on the date input.

**Comment by blaughman** [comment]
This was tested in Dev with the NVDA screen reader.  When selecting the date boxes the screen reader was not indicating a spin box.  We will have Terri Youngblood confirm this is functioning properly.  Moving to UAT based on initial testing.

**Comment by blaughman** [comment]
This is properly functioning in Staging.  Ready for Production deploy.

**Comment by randyabramson** [comment]
Using NVDA screen reader. The date boxes the screen reader was not indicating a spin box. Closing
