### ISSUE TITLE
'Next' button is skipped on page 1 of the complaint form (keyboard navigation)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1031]
## Summary
Keyboard navigation is skipping over the 'Next' button

### Steps To Reproduce

1. Tab through the fields on page one
2. Servicemember area should tab to the 'Next' button
3. On the 'Next' button, clicking tab should progress the user to the footer

This occurs in both Chrome and Edge

### Expected Behavior

After clicking 'tab' in the servicemember question, the next logical field would be the 'Next' button

### Actual Behavior

Tabbing through the complaint form (page 1) - clicking tab while in the servicemember question goes directly to phone number in the footer.  This bug is on both staging and production.

## Suggested Actions
clicking tab while in the servicemember question should go to the 'Next' button

**Comment by randyabramson** [comment]
Worked as expected in CHROME and EDGE. Closing. Nice work @billyhunt
