### ISSUE TITLE
Update USWDS to v2.8.1

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1041]
This is the next step of the US Web Design System update process which was most recently updated to v2.5.1 (see https://github.com/usdoj-crt/crt-portal-management/issues/1023). That update was initiated to resolve Dependabot alerts for security vulnerabilities. However, this issue is opened not in response to security alerts, but rather, to continue the momentum of tracking updates to the design system. 

I chose Version 2.8.1 as the next milestone to match a reasonable stopping point [uswds-gulp](https://github.com/uswds/uswds-gulp/commit/246f19b7ee04b5eee05cd51ff6a10bb167248941), but more importantly, to call attention to the change in the [banner text](https://designsystem.digital.gov/components/banner/) introduced in [2.8.0](https://github.com/uswds/uswds/releases/tag/v2.8.0).

However, we're limited because of our localization work. While the USWDS system does provide ready-to-go translations in Spanish, in order to incorporate this change in our project we will still need to obtain official translations for the other languages that we support. cc @blaughman @randyabramson 

EDIT: Language translation for government banner text changes have been broken out into a separate issue: https://github.com/usdoj-crt/crt-portal-management/issues/1050

**Comment by louh** [comment]
Here is the updated English text to translate:

> **Official websites use .gov**
> A **.gov** website belongs to an official government organization in the United States. 

> **Secure .gov websites use HTTPS**
> A **lock (🔒)** or **https://** means you’ve safely connected to the .gov website. Share sensitive information only on official, secure websites. 

Please take note of where the **bold** text is. The second text uses a lock icon which we will programmatically replace with the correct image in our templates, but in order to make it easier to pass the text around I'm using a lock emoji in its place.

**Comment by randyabramson** [comment]
@blaughman  - kicking this to sprint 54...lots going on right now.

**Comment by ilodidoj** [comment]
@louh @billyhunt please also open separate card for the language translation needed for USWDS 2.8.1.  First card (this card) to upgrade to USWDS 2.8.1 and second one to update each language support (one card for all language support with separate commit for each language changes in the PR).
