### ISSUE TITLE
IER form letter

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1043]
- [x] Bill getting letter approved from Jenny
- [x] Get IER letter translated

**Comment by randyabramson** [comment]
Moving this to sprint 54

**Comment by louh** [comment]
@randyabramson @blaughman Is there an English language IER form letter?

**Comment by blaughman** [comment]
@louh Sorry, I thought this was in the card.
[Draft IER referral response for portal.docx](https://github.com/usdoj-crt/crt-portal-management/files/7635390/Draft.IER.referral.response.for.portal.docx)

**Comment by blaughman** [comment]
Name for dropdown menu:
IER - Form Letter 

Re: line should be consistent with other form letters
Response: Your Civil Rights Division Report - [complaint ID] from the Immigrant and Employee Rights Section

**Comment by blaughman** [comment]
Letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Letter appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letter appears as intended in Production.  Closing this card.
