### ISSUE TITLE
Screen Reader - Language Buttons

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1048]
## Summary

Using the NDVA screen reader, the language selection buttons on the public facing side of the portal are not reading properly.

### Steps To Reproduce

1. Use a screen reader
2. Tab to language select buttons
3. Some buttons read as 'button'

If it's relevant, add browser or operating system where the error occurs.

### Expected Behavior

The language buttons should read 'Espanol' 'English' 'Traditional Chinese' 'Simplified Chinese' 'Vietnamese' 'Korean' and 'Tagalog'

### Actual Behavior

The screen reader indicates the following 'Espanol' 'English' 'button' 'button' 'teng v' 'button' and 'tagalog'

## Suggested Actions

Label the buttons so that a screen reader will accurately and appropriately denote the language.
## Acceptance Criteria

1) Given I am on the public facing side of the portal and using a screen reader
when I tab through the language selection buttons
then I hear the language that correlates with that button.

![image](https://user-images.githubusercontent.com/52507395/131909713-9619a35b-9ab7-43b4-91dd-e6df2e1ee8a8.png)

**Comment by billyhunt** [comment]
When I try it with my mac screen reader, it is reading everything as if it is english.  So it can't read the chinese and korean characters.  How should the buttons work?  Read in whatever language you are currently in?  @blaughman @randyabramson @louh @ilodidoj @emilycryan

**Comment by ilodidoj** [comment]
@billyhunt @louh since this is button, we probably needs to add ARIA info:  **aria-label=**"select language english", aria-label="select language Chinese simplified" aria-label="select language Chinese traditional", etc. for each respective button item

**Comment by ilodidoj** [comment]
Now by default it's reading from the button-text.

**Comment by blaughman** [comment]
@billyhunt @louh @ilodidoj I think what Imran stated above is the extent of what we can do with this.  Keep the labels consistent with the expected behavior in the card no matter what language is currently selected.

**Comment by billyhunt** [comment]
Awesome.  I am on it!

**Comment by blaughman** [comment]
Buttons are properly recognized and described by a screen reader.  Moving to UAT.

**Comment by blaughman** [comment]
Function works as intended in Staging.  Ready for Production deploy.

**Comment by blaughman** [comment]
Labels read correctly in Prod.  Closing this card.
