### ISSUE TITLE
Error in form translation.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1051]
I noticed some english in a spanish language translation.  Notice the "Thank you for your Report" at the top.

![image](https://user-images.githubusercontent.com/6232068/132555268-95efeda7-9927-4816-a66b-9608ba751038.png)

**Comment by blaughman** [comment]
@billyhunt Good catch.  We can update with this language (taken from Spanish no capacity form letter).

Gracias por su informe:

**Comment by billyhunt** [comment]
It turns out we just needed to change a variable from "address" to "es.address" and everything works.  The change is made and is waiting on PR review.

**Comment by blaughman** [comment]
Content displays appropriately in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Form letters are fully translated in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Production verified.  Closing card.
