### ISSUE TITLE
IER Form Letter (Spanish)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1058]
Please reference #https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/usdoj-crt/crt-portal-management/667 in Zenhub for implementation of EEOC referral letter.  That form letter also used a table.

[Draft IER referral response for portal_SP.docx](https://github.com/usdoj-crt/crt-portal-management/files/7164245/Draft.IER.referral.response.for.portal_SP.docx)

**Comment by blaughman** [comment]
Name for dropdown menu:
IER - Form Letter

Re: line should be consistent with other form letters
Response: Your Civil Rights Division Report - [complaint ID] from the Immigrant and Employee Rights Section

**Comment by randyabramson** [comment]
Spanish translation:
[IER Form Chinese Simplified Translation Request.docx](https://github.com/usdoj-crt/crt-portal-management/files/7669580/IER.Form.Chinese.Simplified.Translation.Request.docx)

**Comment by blaughman** [comment]
Letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Letter appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letter appears as intended in Production.  Closing this card.
