### ISSUE TITLE
IER Form Letter (Traditional Chinese)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1059]

**Comment by blaughman** [comment]
[Chinese Traditional IER Form Letter.docx](https://github.com/usdoj-crt/crt-portal-management/files/7462597/Chinese.Traditional.IER.Form.Letter.docx)

**Comment by blaughman** [comment]
Name for dropdown menu:
IER - Form Letter

Re: line should be consistent with other form letters
Response: Your Civil Rights Division Report - [complaint ID] from the Immigrant and Employee Rights Section

**Comment by randyabramson** [comment]
Tradiitonal Chinese translation:

[1405596.Chinese-Tradtional.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7669584/1405596.Chinese-Tradtional.final.docx)

**Comment by blaughman** [comment]
Letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Letter appears as intended in Production.  Closing this card.
