### ISSUE TITLE
IER Form Letter (Simplified Chinese)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1060]

**Comment by blaughman** [comment]
[Chinese Simplified IER Form Letter.docx](https://github.com/usdoj-crt/crt-portal-management/files/7462621/Chinese.Simplified.IER.Form.Letter.docx)

**Comment by blaughman** [comment]
Name for dropdown menu:
IER - Form Letter

Re: line should be consistent with other form letters
Response: Your Civil Rights Division Report - [complaint ID] from the Immigrant and Employee Rights Section

**Comment by randyabramson** [comment]
Simplified Chinese transaltion:

[1405595.Chinese-Simplified.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7669587/1405595.Chinese-Simplified.final.docx)

**Comment by blaughman** [comment]
Letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Letter appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letter appears as intended in Production.  Closing this card.
