### ISSUE TITLE
IER Form Letter (Vietnamese)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1061]

**Comment by blaughman** [comment]
Name for dropdown menu:
IER - Form Letter

Re: line should be consistent with other form letters
Response: Your Civil Rights Division Report - [complaint ID] from the Immigrant and Employee Rights Section

**Comment by randyabramson** [comment]
Vietnamese translation:

[1405577.Vietnamese.final (4) (002).docx](https://github.com/usdoj-crt/crt-portal-management/files/7669635/1405577.Vietnamese.final.4.002.docx)

**Comment by blaughman** [comment]
Letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Letter appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letter appears as intended in Production.  Closing this card.
