### ISSUE TITLE
IER Form Letter (Tagalog)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1063]

**Comment by blaughman** [comment]
[Tagalog IER Form Letter.docx](https://github.com/usdoj-crt/crt-portal-management/files/7462589/Tagalog.IER.Form.Letter.docx)

**Comment by blaughman** [comment]
Name for dropdown menu:
IER - Form Letter

Re: line should be consistent with other form letters
Response: Your Civil Rights Division Report - [complaint ID] from the Immigrant and Employee Rights Section

**Comment by randyabramson** [comment]
Tagalog translation:

[1405593.Tagalog._Final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7669593/1405593.Tagalog._Final.docx)

**Comment by blaughman** [comment]
Letter appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Letter appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letter appears as intended in Production.  Closing this card.
