### ISSUE TITLE
Pagination pills can't display large numbers correctly

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1081]
## Summary

In production, we have so many records that pages number in the thousands. The pills aren't prepared to hold numbers of that size:

![image](https://user-images.githubusercontent.com/2553268/134579368-4ac9e854-857b-4891-84ec-27765549c701.png)

Fixing this is should be a simple CSS style tweak.

**Comment by blaughman** [comment]
Production verified.  Closing card.
