### ISSUE TITLE
Look into additional database improvements for form/view

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1087]
In order to better test performance solutions, we needed to be better able to simulate the production environment on our local systems, without exposing production data (PPE).  This tick addresses that by creating a new command to run to create a large data set in your local environment.  To run, you can run the following command.  

```
docker-compose run web python crt_portal/manage.py create_mock_reports 10
```

Which will create 10 reports.  To create 100,000 reports (about the size of the prod data set), change the number "10" to "100000".

This only will be run in local environments, so there is no way to test online.  Since it has been tested locally, you can close it when ready.

**Comment by ilodidoj** [comment]
@billyhunt please ensure there is a open PR for code review of the above before moving card to dev done.  Also let the reviewer merged the code once the reviewing person approved it.

**Comment by billyhunt** [comment]
The PR associated with this ticket is https://github.com/usdoj-crt/crt-portal/pull/1042

Its only for the creating of mock data.  There is another ticket for the new PR to actually make the DB change.  The new ticket is https://github.com/usdoj-crt/crt-portal-management/issues/1145

**Comment by randyabramson** [comment]
Per @billyhunt  there is no way to test this since it runs locally. Moving this to UAT complete.
