### ISSUE TITLE
No-reply address for auto-reply email

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1091]
Production reply settings on the GovDelivery email setup will have following changes:

CHANGE TO:
From address: civilrightsdonotreply@mail.civilrights.usdoj.gov
From name (display): DOJ Civil Rights - Do Not Reply 
Forwarding address: [NO FORWARDING ADDRSS]

CHANGE FROM:
From address: civilrightsreply@mail.civilrights.justice.gov
From name: civilrightsreply
Forwarding address: ask.CRT@usdoj.gov

- [x] Decide on Email address to use
- [x] Check with DEVS on how to configure this address with JMD/GovDelivery
- [ ] Test what happens when you reply to address

**Comment by blaughman** [comment]
Possible addresses:
No-reply@mail.civilrights.usdoj.gov

Doesn't point to anything

**Comment by blaughman** [comment]
We can't test this in the Dev environment.  Replying to a test email opens an email to an inbox for a former engineer.

**Comment by randyabramson** [comment]
We can't test this in the Staging environment. Replying to a test email opens an email to an inbox for a former engineer.

**Comment by randyabramson** [comment]
Can't test without sending an Email on Live. Will wait for @blaughman 's  team to test
