### ISSUE TITLE
Hate Crime translation - CHINESE SIMPLIFIED

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1102]
Translation doc:

[Chinese simplified.docx](https://github.com/usdoj-crt/crt-portal-management/files/7289090/Chinese.simplified.docx)

**Comment by randyabramson** [comment]
@louh attaching translations v2 with line breaks here

[Chinese simplifiedv2.docx](https://github.com/usdoj-crt/crt-portal-management/files/7305097/Chinese.simplifiedv2.docx)

**Comment by blaughman** [comment]
Function works as intended in Chrome, Edge and Mobile in Production.  Closing this card.
