### ISSUE TITLE
Hate Crime translation - TAGALOG

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1104]
Translation doc:

[tagolog.docx](https://github.com/usdoj-crt/crt-portal-management/files/7289104/tagolog.docx)

**Comment by randyabramson** [comment]
@louh attaching translations v2 with line breaks here
[tagologv2.docx](https://github.com/usdoj-crt/crt-portal-management/files/7305101/tagologv2.docx)

**Comment by randyabramson** [comment]
Passed the GT sniff test. Moving to UAT

**Comment by blaughman** [comment]
Function works as intended in Chrome, Edge and Mobile in Production.  Closing this card.
