### ISSUE TITLE
Hate Crime translation - KOREAN

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1106]
Translation doc

[korean.docx](https://github.com/usdoj-crt/crt-portal-management/files/7289118/korean.docx)

**Comment by louh** [comment]
@randyabramson The Korean translator has noted in their responses that “How do I…” as a heading doesn’t make sense in Korean word order. “How do I” in Korean would occur at the end of sentences, not at the beginning. How should we address this?

**Comment by randyabramson** [comment]
@louh attaching translations v2 with line breaks here

[koreanv2.docx](https://github.com/usdoj-crt/crt-portal-management/files/7305110/koreanv2.docx)

**Comment by blaughman** [comment]
Function works as intended in Chrome, Edge and Mobile in Production.  Closing this card.
