### ISSUE TITLE
Hate Crime Translation - SPANISH

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1110]
@louh attaching translations v2 with line breaks here
[Hate Crimes Spanish Translation Request SPA Final 2021 10 08.docx](https://github.com/usdoj-crt/crt-portal-management/files/7329402/Hate.Crimes.Spanish.Translation.Request.SPA.Final.2021.10.08.docx)

**Comment by randyabramson** [comment]
Passed the GT sniff test. Moving to UAT

**Comment by blaughman** [comment]
Function works as intended intended in Chrome, Edge and Mobile.  Closing this card.
