### ISSUE TITLE
Check with Lou on 1050 on github - translation for government banner at top

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1114]

**Comment by louh** [comment]
Here's the link to the issue - https://github.com/usdoj-crt/crt-portal-management/issues/1050

**Comment by blaughman** [comment]
Closing this card.  Using card #1050

**Comment by blaughman** [comment]
Spanish Translation
[Landing Page Updates - Spanish + MC 2022 01 31.docx](https://github.com/usdoj-crt/crt-portal-management/files/7979769/Landing.Page.Updates.-.Spanish.%2B.MC.2022.01.31.docx)

**Comment by louh** [comment]
Closing this in favor of #1050 (which has more info)
