### ISSUE TITLE
Tech Task: upgrade zap2docker version for circle ci

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#1115]
## User story:

As a developer I should be able to push release to staging without zap error.
Zap will be upgraded from weekly to stable latest version for circle ci tasks.

https://github.com/usdoj-crt/crt-portal/pull/1008
https://hub.docker.com/r/owasp/zap2docker-stable/tags

 

## Objective:

Run OWASP scan successfully in staging and prod

## Ticket background:

Successful circle CI job for OWASP tasks.

## Acceptance criteria:

 -[ ] Create new release and push to git repo
       - circle ci job should successfully complete OWASP scan test job

**Comment by louh** [comment]
Moving to current sprint because of our work unblocking staging deployment last week, and I will have some follow up discovery this week.
