### ISSUE TITLE
Assignee Filter Value for Unassigned Records

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1116]
## User story:
As a CRT user, I want to find records without an assignee so that I can assign/take action on them.

## Objective:
This will reduce the number of reports in the backlog.

## Key result:
Close rate and time to close will improve.

## Ticket background:
Unassigned records get lost in the mix of new/open reports.  There is no current way to determine which records are lacking an assignee without checking the complaint detail page.  This will allow staff to isolate those records and assign them for action.
  
## Acceptance criteria:
1) Given I am on the view all table
when I look in the 'Assignee' filter
then I see a value labeled 'Unassigned'

2) Given I am in the Assignee filter
when I select the 'Unassigned' value
then I see all records without an assignee based upon my current filters

## Assumptions
- The value 'Unassigned' should be at the top of the list when clicking the down arrow of the Assignee filter
- The value 'Unassigned' should be type ahead as well

**Comment by blaughman** [comment]
Function works as intended in Dev in Chrome and Edge.  Moving to UAT.

**Comment by randyabramson** [comment]
Worked as expected on STAGING

**Comment by blaughman** [comment]
Functions as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Works as intended in Production.  Closing this card.
