### ISSUE TITLE
Modal text is red on firefox

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1118]
The text on the contact information button is red when it is in focus on firefox.  

![image (1)](https://user-images.githubusercontent.com/6232068/137205718-45887649-862c-4645-b7d3-a7564a97dbd3.png)

**Comment by blaughman** [comment]
Issue resolved.  Text appears as intended in Chrome, Edge and Mobile in Production.  Closing this card.
