### ISSUE TITLE
Tech Task: update cert file on S3 SSO bucket 

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#1120]
## User story:

sso/ca_bundle.pem needs to be updated on S3 bucket for staging by Friday, 10/22.
sso/ca_bundle.pem needs to be updated on S3 bucket for production on Friday,  11/19 9 pm est.
This will be needed to keep SSO setup working for internal users of the portal.

UPDATES: 11/22/2021
Release 11-16-2021 restaged after Production cert update on DOJ ADFS on Nov 19th, 2021 after 9:00 pm EST. No changes or upload needed on existing cert file on the portal.

UPDATES: 11/03/2021
No update of sso/ca_bundle.pem needed for stating or production.
A validation of SSO access needed on Nov 19th, 2021 after 9:00 pm EST for production apps.

## Objective:

Keep SSO cert up to date from expiration and SSO access operational.

## Acceptance criteria:

 -[ ] Perform hard reset of CHROME or EDGE browser on users laptop. Go to internal intake url where SSO configured.
       - internal intake user should be able to reach the internal URL of the portal.

**Comment by randyabramson** [comment]
Worked as intended on Staging
