### ISSUE TITLE
Update activity log to deal with unassigned user code.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1128]
1. This PR syncs up the current dashboard code with the changes made for unassigned users.
2. The current implementation is doing thousands of user lookups. no good! This change directly filters using the actor_stream, which is a user specific activity stream. This should be much quicker.

To test, make sure that the dashboard view does not take 10 seconds to load on staging.

**Comment by blaughman** [comment]
The Staging environment is operating as expected.  Closing this card.
