### ISSUE TITLE
DRS - EEOC Referral Letter

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1129]
## User story:
As a DRS end user, I want a form letter so that I can reply to reports where the complaint is referred to the EEOC.

## Objective:
Give DRS end users the tool(s) necessary to complete their work.

## Key result:
Greater staff efficiency and reduced backlog.

## Ticket background:
This feature will help eliminate 1000 reports from the backlog.

## Acceptance criteria:
1. Given I am on the complaint detail page
when I click on the 'Contact complainant' button
then I see a list of form letters

2. Given I am on the 'Contact complainant' list of form letters
when I scroll the list sorted in alphabetical order
then I see a form letter labeled 'DRS - EEOC Referral Form Letter'

## Assumptions:
- This form letter will need translation into all the available languages
- Note - this letter will have two different addressees on it
- This letter should capture the email and physical mailing address if both are present

[DRS-EEOC Referral Letter.docx](https://github.com/usdoj-crt/crt-portal-management/files/7488112/DRS-EEOC.Referral.Letter.docx)

**Comment by blaughman** [comment]
@billyhunt @louh @ilodidoj @randyabramson I tested this feature and we're missing some required information in the output.  I highlighted the missing information in green in the attached file.

[DRS-EEOC Referral Letter (Missing Information).docx](https://github.com/usdoj-crt/crt-portal-management/files/7539674/DRS-EEOC.Referral.Letter.Missing.Information.docx)

**Comment by billyhunt** [comment]
OK, I am on it.

**Comment by blaughman** [comment]
Functions as intended in Staging.  Ready for Production.
