### ISSUE TITLE
Search helper text

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1137]
## User story:
As a CRT user, I want helper text to instruct me on search operators so that I can obtain better search results.

## Objective:
Better search results

## Key result:
Increased staff efficiency

## Ticket background:
The  'And' and 'Or' functions were added to the personal description, summary and incident location name filters.  It is not blatantly obvious to users that these functions are available when searching.

## Acceptance criteria:
1. Given I am on the view all table.
when I see the line of filters for personal description, summary and incident location name
then I see helper text to the rights of the text boxes.

## Assumptions
-  Text is able to be read by a screen reader

## Mockup
See Emily's mocks in card #1009 

![image](https://user-images.githubusercontent.com/52507395/140979115-01177da8-dad4-4043-a297-cbbb8a8125cf.png)

**Comment by blaughman** [comment]
@randyabramson @ilodidoj @billyhunt @louh We need to run the copy by Chinelo prior to implementation.

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson I attached a pdf of the design for showing the helper text with an additional placement of the "Apply filters" buttons as right-aligned with the results table. 

Let me know your thoughts.

[AND:OR search filter - Option 1.pdf](https://github.com/usdoj-crt/crt-portal-management/files/7558566/AND.OR.search.filter.-.Option.1.pdf)

**Comment by chinelo-ikejimba** [comment]
@randyabramson @blaughman let me know if you have thoughts on Option 2's tooltip design

[OR search filter - Option 2.pdf](https://github.com/usdoj-crt/crt-portal-management/files/7566681/OR.search.filter.-.Option.2.pdf)

**Comment by randyabramson** [comment]
@chinelo-ikejimba  I love it! ^^^^  Nice work cc @blaughman

**Comment by randyabramson** [comment]
Next step - @chinelo-ikejimba  running this by intake specialists

**Comment by chinelo-ikejimba** [comment]
### A/B testing update

- 2/3 of the intake specialists prefer Option 2 (tooltip feature)

**Comment by blaughman** [comment]
Devs - Please implement option 2.

**Comment by chinelo-ikejimba** [comment]
@billyhunt @louh - here's the [design hand-off](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Aug-2021-Working-pages-(Copy)?node-id=412%3A9941) link to Option 2

I sent your emails a link to the design as well. Let me know if you have any access issues.

**Comment by randyabramson** [comment]
Per Terri, this needs to:

1. Be able to navigate to the tool tip by keyboard and activate it by keyboard
2. Needs to be able to be heard on screen reader

**Comment by louh** [comment]
@blaughman @randyabramson I've got the tooltip done (and will be reviewing it with @chinelo-ikejimba today to make sure I've captured everything we need to), but one thing we don't have yet is a combined search field. We still have individual search fields for personal description, CRT summary and incident location name, with those last two existing below the helper text. Screenshot for context:

<img width="990" alt="Screen Shot 2021-12-06 at 11 36 34 AM" src="https://user-images.githubusercontent.com/2553268/144885423-96d84077-b7ac-43a9-8ca3-88d33e9617ec.png">

I think combining the search fields into one now (our eventual direction) is out of scope for this current ticket, but should we leave the fields alone, or do we move them elsewhere for now? Open to any suggestions.

**Comment by randyabramson** [comment]
I'd leave it to @chinelo-ikejimba if she wants to move the fields. I think the testing went well, so we might be OK to leave it as is.

As far as combining the search fields, I am open to it, but I really want to make sure we explore any possible scenario where users might actually want them separate. I know combining the fields *sounds* like a great idea...I just am not sure we really tested this to its fullest.

**Comment by louh** [comment]
@chinelo-ikejimba and I reviewed over screen share and she has recommended that we move the CRT summary and Incident location name fields since the helper text instructions only pertained to the Personal description field.

**Comment by randyabramson** [comment]
@louh  good by me.

**Comment by chinelo-ikejimba** [comment]
🙌🏽 high-fives all around team

**Comment by ilodidoj** [comment]
@louh @chinelo-ikejimba rendering of tooltip is not consistent due to large number of text and formatting of the text on browser.  Tooltip dynamically adjust the rendering based on the size of the main page and horizontal bar location of the page.  I think modal will be a better approach similar to 'Rerouting guide' on the detail page.

**Comment by blaughman** [comment]
Feature appears as expected and tooltip appears with keyboard navigation.  Moving to UAT.

**Comment by blaughman** [comment]
Feature appears as expected and tooltip works with NVDA screen reader.  Ready for production.

**Comment by randyabramson** [comment]
Formatting a bit strange in Edge. One grab below is at full browser width and one is at minmized browser width

<img width="376" alt="tooltip" src="https://user-images.githubusercontent.com/6254621/147610666-64da6178-2b1d-4d74-b2ca-0b6f62c6c05b.PNG">
<img width="354" alt="tooltip2" src="https://user-images.githubusercontent.com/6254621/147610667-fc41308b-6341-4911-82cf-eaf38dbfd85c.PNG">

**Comment by blaughman** [comment]
Looks and works as intended in Production.  Closing this card.
