### ISSUE TITLE
Confirmation Page Language Edit

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1139]
## User story:
As a CRT product owner, I want the public facing language to represent the experience so that we clearly convey expectations.

## Objective:
Increase public trust in our process

## Key result:
Improved customer experience

## Ticket background:
The language on the confirmation page was created prior to email implementation.  The language, as it currently exists, does not reflect the current experience.

## Acceptance criteria:
1. Given I am submitting a report
when I am on the confirmation page
then I see a validation message indicating
"Please save your record number for tracking."
"You should receive an email confirmation, but please print or save this page for your records."

## Current Experience
![image](https://user-images.githubusercontent.com/52507395/140995407-de40ee70-1e8d-415b-ba60-6dff89f61fa6.png)

**Comment by louh** [comment]
Dupe of #1149
