### ISSUE TITLE
Unassigned reports - bold font and activity log capture

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1140]
## User story:
As a CRT user I want the assignee text to be bold and "nobody" added in the activity log so that the experience and data are consistent.

## Objective:
Consistency in appearance and data.

## Ticket background:
The text in the action card has been bold since launch.  The GAO audit highlighted the importance of data consistency in our exports.

## Acceptance criteria:
1. Given I am on the complaint detail page
when I am in the 'Actions' card and select an assignee
then the text is bold

2. Given I am on the complaint detail page
when I select an assignee
then the activity log displays the text "Updated from "Nobody" to "username"
and
if an assignee is removed from a record
then the activity log displays the text "Updated from "username" to "Nobody"

#1116 
#739

**Comment by louh** [comment]
Follow up note to record our conversation from today: we agreed to leave the activity output alone to maintain consistent logs for audit purposes. As a result, the "assign to" action and filter will now read "(none)" for unassigned, instead of "(nobody)" or "(unassigned)".

**Comment by blaughman** [comment]
Functions as intended.  Moving to UAT.

**Comment by blaughman** [comment]
Functions as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Functions as intended in Production.  Closing this card.
