### ISSUE TITLE
Implement first DB change.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1145]
When looking at the sql queries for the /form/view page, one sticks out with large datasets.  The email_report_count.  

![image (2)](https://user-images.githubusercontent.com/6232068/142914660-2f5d8d31-c8f1-43c3-b265-782c0505386b.png)

Notice the two red queries related to email_report_count.  The total time of just those two queries is almost 2.5 seconds.  Thats a lot of time for a user to wait for the page to load.  

email_report_count is a view, meaning it is computed every time the page loads.  Nothing is cached.  We decided to change this view to something called a "materialized view", which caches the data.  Look at the same page query performance when we use a materialized view.  

![image (3)](https://user-images.githubusercontent.com/6232068/142915055-95f45b66-a053-431c-8bad-7fbd345d93a5.png)

About .5 seconds.  Still not great, but MUCH better.  2 seconds of page load time shaved off.  

This query will also save time on the form/view/{index} page for individual pages.

The downside of using a "Materialized View", is we need to recompute to make it accurate. We will update every time someone creates a report, or updates an email in the existing report.  This will probably slow down the report creation process, but we feel that it is worth the cost to save time displaying report information because

1. Reading is done more often than writing
2. The amount of time saved on the report read is greater that the time spent writing.

To test:

1. Check email counts on various records on dev.
2. Create a new report with an email address and make sure the count is correct.  
3. Change a report's email.  Make sure all reports email counts are updated accordingly.

**Comment by blaughman** [comment]
Changing emails in Staging was seamless.  System responded quickly and as expected.  Ready for Production.
