### ISSUE TITLE
DRS - 'other agency' letter (translated)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1154]
## User story:
As a DRS intake specialist, I want external agency referral letters translated so that I can reply to submissions in languages other than English.

## Objective:
Reduce backlog

## Key result:
Time to close will decrease 

## Ticket background:
DRS has/had a backlog of nearly 1000 reports that needed to be sent to four external agencies.  Most, if not all, reports were in English.  With the implementation of these referral letters in other languages, no report will go unanswered.

## Acceptance criteria:
1) Given I am on the complaint detail page
when I select 'Contact complainant'
then I see a menu with a language selection menu and a form letter selection menu

2) Given I am in 'Contact complainant' menu
when I select any language
then I see the four DRS referral letters available for selection

## Language Implementation
- [ ] Traditional Chinese
[1405596.Chinese-Tradtional.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7677010/1405596.Chinese-Tradtional.final.docx)
- [ ] Simplified Chinese
[1405595.Chinese-Simplified.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7677013/1405595.Chinese-Simplified.final.docx)
- [ ] Korean
[1405587.Korean.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7677014/1405587.Korean.final.docx)
- [ ] Vietnamese
[1405577.Vietnamese.final (4) (002).docx](https://github.com/usdoj-crt/crt-portal-management/files/7677026/1405577.Vietnamese.final.4.002.docx)
- [ ] Tagalog
[1405593.Tagalog._Final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7677018/1405593.Tagalog._Final.docx)
- [ ] Spanish
[DRS Referral Letter (Spanish).docx](https://github.com/usdoj-crt/crt-portal-management/files/7678305/DRS.Referral.Letter.Spanish.docx)

**Comment by blaughman** [comment]
Traditional Chinese Checklist:
- [ ] EEOC Referral Letter
- [ ] Dept of Ed Referral Letter
- [ ] HHS Referral Letter
- [ ] Dept of Transportation Referral Letter

**Comment by blaughman** [comment]
Simplified Chinese Checklist:
- [ ] EEOC Referral Letter
- [ ] Dept of Ed Referral Letter
- [ ] HHS Referral Letter
- [ ] Dept of Transportation Referral Letter

**Comment by blaughman** [comment]
Vietnamese Checklist:
- [ ] EEOC Referral Letter
- [ ] Dept of Ed Referral Letter
- [ ] HHS Referral Letter
- [ ] Dept of Transportation Referral Letter

**Comment by blaughman** [comment]
Tagalog Checklist:
- [ ] EEOC Referral Letter
- [ ] Dept of Ed Referral Letter
- [ ] HHS Referral Letter
- [ ] Dept of Transportation Referral Letter

**Comment by blaughman** [comment]
Spanish Checklist:
- [ ] EEOC Referral Letter
- [ ] Dept of Ed Referral Letter
- [ ] HHS Referral Letter
- [ ] Dept of Transportation Referral Letter

**Comment by blaughman** [comment]
English Version of the letter
[DRS Referral Letter.docx](https://github.com/usdoj-crt/crt-portal-management/files/7678934/DRS.Referral.Letter.docx)

@louh @billyhunt @ilodidoj

**Comment by louh** [comment]
@blaughman @randyabramson Need some further clarification on the translated letters.

- The line "Re:	Civil Rights Division Complaint – [Complaint ID] from the Disability Rights Section" in our current English letters is not translated in these other languages - please advise.
- There are translations for "Dear [Submitter Name]," and "Your record number is [Record Locator]." but these are not part of the current English letter. I assume I can ignore these?
- The addresses that go on the top of the letter have been completely translated, but I don't think that's the intention, right? Someone who delivers that letter would be unable to read the address. I would recommend leaving that portion in English, would that work for you?
- For the contact information in the body of the letter itself, I will keep the format of "(translated name) (English name in parenthesis)". Sounds good?
- The new contact information in the body of the EOCC letter that was just added last week is still awaiting translation. Should I go ahead and add the original EOCC information, or the untranslated (but correct) EOCC information for now?

**Comment by blaughman** [comment]
@louh @randyabramson 
- Sounds like we'll need translation for the Re: line
- Ignore those two lines
- Please leave the addresses in English
- Sounds good
- I'll check w/ Marta regarding this question
- Hold off until we get the updated translation.  No sense in adding something that isn't accurate.

**Comment by blaughman** [comment]
@louh @randyabramson This comment was added in the Spanish translation document regarding translating agency info.
"I left this in English (except for changing voice to voz) because the entire address is given, and complete addresses must remain in the source language as that is the only way an individual can properly locate a building. If you want, I can put a translation in hard brackets of each entity name but I don´t think it is necessary"

**Comment by louh** [comment]
Thanks @blaughman. I've gotten all the letters as far as I can get to with the guidance above, in the branch here: https://github.com/usdoj-crt/crt-portal/tree/louh/1154-drs-letters

Per standup today, I have re-used the subject line text in the `Re:` line, although the words aren't quite exactly the same, they are close enough.

We'll still need translations for the following two lines as part of the EOCC contact:

- "TTY for Deaf/Hard of Hearing callers only"
- "ASL Video Phone for Deaf/Hard of Hearing callers only"

**Comment by blaughman** [comment]
@louh @randyabramson @ilodidoj @billyhunt Spanish translation for the two lines as part of the EEOC contact
[12.23.21 Translation Request - Spanish.docx](https://github.com/usdoj-crt/crt-portal-management/files/7803251/12.23.21.Translation.Request.-.Spanish.docx)

**Comment by blaughman** [comment]
[1422842.Tagalog.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7856540/1422842.Tagalog.final.docx)
[1422839.Vietnamese.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7856541/1422839.Vietnamese.final.docx)
[1422844.Korean.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7856542/1422844.Korean.final.docx)
[1422835.Chinese_Traditional.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7856543/1422835.Chinese_Traditional.final.docx)
[1422832.Chinese_Simplified.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/7856544/1422832.Chinese_Simplified.final.docx)

**Comment by blaughman** [comment]
@louh I'm not seeing the letters available for selection in Dev - even after a hard refresh.  Any thoughts? 
![image](https://user-images.githubusercontent.com/52507395/149997721-6082a19c-d6b6-4c44-a6dc-c5ad61067675.png)

**Comment by louh** [comment]
@blaughman the deploy for this failed with an "out of memory" error. I'm re-running the job now. With any luck this was a temporary hiccup. Will keep you posted.

**Comment by louh** [comment]
@blaughman deploy went through, try validating again

**Comment by blaughman** [comment]
@louh @ilodidoj @billyhunt @randyabramson All of the translated letters are missing the Agency information at the top of the page
[CRT Complaint Records - Printed 'DRS - EOCC Referral Form Letter (Spanish)' template.pdf](https://github.com/usdoj-crt/crt-portal-management/files/7915177/CRT.Complaint.Records.-.Printed.DRS.-.EOCC.Referral.Form.Letter.Spanish.template.pdf)
The English versions are correct.

[English version.pdf](https://github.com/usdoj-crt/crt-portal-management/files/7915187/English.version.pdf)
.

**Comment by louh** [comment]
@blaughman Good call out, looking at it now.

**Comment by louh** [comment]
@blaughman Address headers added, please verify again!

**Comment by blaughman** [comment]
@louh Testing this in Staging.  The EEOC letter in Traditional and Simplified Chinese are both missing the EEOC contact information at the top of the printed form letter.
![image](https://user-images.githubusercontent.com/52507395/152559407-ee81e7d0-6e09-4476-a8b5-6f02b5ed44ed.png)

**Comment by louh** [comment]
@blaughman This is only in staging, right? Can you try clearing cache and reloading, then try again?

**Comment by blaughman** [comment]
Letters appear as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
This can't be tested in Production without creating erroneous activity logs.  Will rely on feedback from DRS regarding implementation.  Closing this card.
