### ISSUE TITLE
Change Requested - DRS EEOC Referral Letter

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1155]
The EEOC recommended a small change to the DRS - EEOC referral letter.  They indicated the requested additional information is the proper procedure for filing a complaint with the Agency.
[DRS-EEOC Referral Letter (EEOC Update).docx](https://github.com/usdoj-crt/crt-portal-management/files/7688306/DRS-EEOC.Referral.Letter.EEOC.Update.docx)

**Comment by blaughman** [comment]
Letter appears as intended in Dev. Moving to UAT.

**Comment by blaughman** [comment]
Letter appears as intended in Staging. Ready for Production.

**Comment by randyabramson** [comment]
Letter appears as intended on Production. Good to close.

**Comment by blaughman** [comment]
Requested edits are reflected in updated letter.  Closing this card.
