### ISSUE TITLE
Fix dashboard UX

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1156]
## User story:
As a CRT user, I want a cleaner experience on the report dashboard

## Ticket background:
The 'apply filters' button is hidden behind the intake specialist drop down.  For a user to run a report they must click off of the intake specialist menu for the 'apply filters' button to be available for selection.

## Proposed solution
Move the 'apply filters' and 'clear all filters' selections from their current location.

## Assumptions
- More categories/filters will be added to the dashboard in the future and this design should reflect that expectation.

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson 

Here's a 3 for 1 holiday treat. I created designs for the: 

1. filters buttons
2. dropdown combo-box
3. table columns

2 and 3 can be iterated, but it seemed like a nice start to explore ideas for the table's content to support team management and intake specialists' performance review prep.

### 1. filters buttons
![Reportal Portal Nav - Page 2 0](https://user-images.githubusercontent.com/92807659/145649160-8c37920a-1928-4aa1-b5bf-86e26b001e13.jpg)

### 2. dropdown combo-box
![Reportal Portal Nav - Page 2 1](https://user-images.githubusercontent.com/92807659/145649173-9ae9b90b-61da-466b-94cc-724c47aa470e.jpg)

### 3.  table columns
![Reportal Portal Nav - Page 2 2](https://user-images.githubusercontent.com/92807659/145649192-25b073eb-ea67-4486-a937-efb55f68e18c.jpg)

**Comment by louh** [comment]
Per standup today:

1. buttons are already on the right as a result of previous work (see https://github.com/usdoj-crt/crt-portal/pull/1060/commits/728fe53768cc6e28a01d48b890108ca97606795f). While the mockup shows buttons on the same line as filters, we determined that making this change was unnecessary right now, for instance, in case the list of filters grow.
2. we will improve the two-step process of clicking into the combo box
3. we haven't separated out the activity type for the table view yet, so we'll kick this part into the future.

**Comment by blaughman** [comment]
Feature looks and works as intended.  Moving to UAT.

**Comment by blaughman** [comment]
Feature looks and works as intended on Staging.  Ready for Production.

**Comment by randyabramson** [comment]
Alignment is a bit off in EDGE. Looks fine in CHROME
<img width="561" alt="team-management" src="https://user-images.githubusercontent.com/6254621/147610940-3d11547b-9ae2-46c2-a0ac-f3fd5f20bf59.PNG">

**Comment by blaughman** [comment]
Looks and performs as expected in Production.  Closing this card.
