### ISSUE TITLE
DESIGN - Experience Flow for Bulk Actions (close without accessing detail page)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1157]
## User story:
As a Product Owner, I want to understand the user experience for trying to bulk close reports that haven't been viewed.

## Objective:
Eliminate the possibility of reports being closed without being viewed.

## Key result:
Minimize red flags on a GAO audit.

## Ticket background:
CRT users can bulk close reports without viewing a report.  The GAO audit was concerned with the amount of time between a report submission and when CRT staff views the report.  CRT users routinely close repeat writers based on the information available on the view all table.  We need to let CRT staff know when they are trying to close a report that hasn't been viewed so they can correct that oversight.  

## Mockup(s)

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson here are annotations detailing the flow and design for the bulk actions error messages on closing reports that haven't been viewed or opened.

### Flow Annotations

1. User selects reports with Status = New 
2. User clicks on **Actions** button to navigate to Update multiple records page
3. User selects **Closed** in Status input field
4. Error message appears stating only reports with OPEN status can be closed
5. Disable **Apply changes to # records** button

### Design: Error message
![change status](https://user-images.githubusercontent.com/92807659/148566667-5639e56f-59ba-4c4a-888d-510e4667389a.jpg)

**Comment by blaughman** [comment]
@randyabramson @chinelo-ikejimba This looks like a good flow for this process.  I'm wondering if we should tweak the language to say "Only reports that have been viewed can be closed."  For most of these reports, they will move from "New" to "Closed."  The user might think they have to change the status from new to open before they can close those records.  Interested in your thoughts.

**Comment by randyabramson** [comment]
Per today's stand up, I believe we are going to:

1. Change the activity log to read 'viewed' instead of 'opened'
2. Get the carrot drop to trigger a 'viewed' status (this may involve the API work)
3. Then we will return to this ticket for implementation.

Nice work @chinelo-ikejimba  !!!

**Comment by chinelo-ikejimba** [comment]
Sounds good.

I updated the image and design handoff with the terminology of "viewed" for the time being.
