### ISSUE TITLE
Proform Required Fields

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1158]
## User story:
As a Product Owner, I want the 'CRT Receipt Date' and 'Intake Type' as required fields for a record submission.

## Objective:
The goal of this ticket is to produce records with more consistent data.  This will increase the public's trust in our process.

## Key result:
Increased data reliability

## Ticket background:
The receipt date and when the record is added to the portal are often two different times.  When a response is generated for the following mail types "letter, phone, fax and email" the date of intake is not accurate.  The CRT Receipt Date should be inserted into the response for these four mail types.  

## Acceptance criteria:
1. Given I click 'Add New Record' on the view all table
when the proform opens
then my cursor is in the month field for CRT receipt date

2. Given I am on the proform
when I have successfully entered a month/day/year in the CRT receipt date
then I am directed to the Intake format field

3. Given I am in the Intake format field
when I select one of the following selections, "letter, phone, fax or email"
then I am directed to the contact portion of the proform

## Technical Notes
- The CRT Receipt Date should be captured in the Reports section of the Admin Console
- Month, day and year are required input (should be validated for acceptable values - Month 1-12 Day 1-31 Year 2000 and forward).  We will need an error message for CRT receipt date.  Let's use same format as public-facing side, but make day required as well.
![image](https://user-images.githubusercontent.com/52507395/145635028-1f0a5499-67af-4dbf-931e-ff7722aa341b.png)
- We need an Intake type error message as well.  Can be similar to the image below but use "Please select an intake type."
![image](https://user-images.githubusercontent.com/52507395/145634827-dfb74391-9d18-4ed4-abf7-86cdc95a721b.png)
- Can we require this information before a CRT user can proceed on the proform?
- Year should be a required four digit number (promotes data reliability)

**Comment by billyhunt** [comment]
Here are some suggested tests for this card and https://github.com/usdoj-crt/crt-portal-management/issues/1166

## Suggested Tests

### Pro Form
+ [ ] Check for field validations on the pro form for the intake format, date, and Primary concern. You should not be able to submit without these.
+ [ ] Check to make sure messages are accurate for the above fields.

### Report Detail Form CRT Date validation
+ [ ] Go to a report detail, and modify the crt_receipt_month to something out of bounds (eg 13).  Make sure you cannot save and get a valid error message.
+ [ ] Go to a report detail, and modify the crt_receipt_month to add a non integer (eg "AF").  Make sure you cannot save and get a valid error message.
+ [ ] Go to a report detail, and modify the crt_receipt_day to something out of bounds (eg 0).  Make sure you cannot save and get a valid error message.
+ [ ] Go to a report detail, and modify the crt_receipt_day to a non integer (eg "$").  Make sure you cannot save and get a valid error message.
+ [ ] Go to a report detail, and modify the crt_receipt_year to something out of bounds (eg 1999).  Make sure you cannot save and get a valid error message.
+ [ ] Go to a report detail, and modify the crt_receipt_year to a non integer (eg "N0PE").  Make sure you cannot save and get a valid error message.
+ [ ] Go to a report detail, and add a year in the future.  Make sure you cannot save and get a valid error message.

**Comment by blaughman** [comment]
All recommended tests conducted and passed.  Moving to UAT.

**Comment by blaughman** [comment]
Unaccepted values were not allowed in Production.  Functions as intended.  Closing this card.
