### ISSUE TITLE
Update Form letter responses based upon intake type

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1159]
## User story:
As a Product Owner, I want form letter responses for non web-based submissions (letter, phone, fax, email) to incorporate the CRT receipt date in the body of the response.

## Objective:
Increase public trust with responses incorporating more accurate information.

## Ticket background:
When generating responses to records in the portal, all intake types incorporate the date of intake using the submission date.  For non web-based submissions, the CRT receipt date is the most appropriate date to use.

## Acceptance criteria:
1. Given I am on a complaint detail page for a non web-based submission (letter, phone, fax or email)
when I select 'Contact complainant'
then I see the form letter modal appear

2. Given I have selected a form letter response
when I see the the 'date of intake' in the response
then I see the 'CRT receipt date' populated in the letter.

**Comment by billyhunt** [comment]
After conversation with @blaughman, the logic will be as follows.  

If there is a crt_receipt_date AND the intake type is not 'web', then we will use crt_reciept_date in all form letter responses.  If not, we will use the create_date (the current process).  

Does this make sense to everyone cc @randyabramson @chinelo-ikejimba @louh @ilodidoj

**Comment by louh** [comment]
This sounds good to me!

**Comment by chinelo-ikejimba** [comment]
👌🏾 makes senses @billyhunt

**Comment by billyhunt** [comment]
## Testing Instructions
+ [ ] On a report with an intake_type of "web" (created through the normal report process), add a crt_reciept_date.  Check the form letters and make sure the create date is used, NOT the crt_reciept_date
+ [ ] On a report with an intake_type of "web" (created through the normal report process), make sure there is no crt_reciept_date.  Check the form letters and make sure the create date is used, NOT the crt_reciept_date
+ [ ] On a report with an intake_type of something other than "web" (created through the pro form), add a crt_reciept_date.  Check the form letters and make sure the crt_reciept_date is used.
+ [ ] On a report with an intake_type of something other than "web" (created through the pro form), add an invalid crt_reciept_date (for example, leave the month blank).  Check the form letters and make sure the create_date is used.

**Comment by blaughman** [comment]
All tests passed in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
## Staging Testing Instructions
+ [ ] On a report with an intake_type of "web" (created through the normal report process), add a crt_reciept_date.  Check the form letters and make sure the create date is used, NOT the crt_reciept_date
+ [ ] On a report with an intake_type of "web" (created through the normal report process), make sure there is no crt_reciept_date.  Check the form letters and make sure the create date is used, NOT the crt_reciept_date
+ [ ] On a report with an intake_type of something other than "web" (created through the pro form), add a crt_reciept_date.  Check the form letters and make sure the crt_reciept_date is used.
+ [ ] On a report with an intake_type of something other than "web" (created through the pro form), add an invalid crt_reciept_date (for example, leave the month blank).  Check the form letters and make sure the create_date is used.

**Comment by blaughman** [comment]
ADM user confirmed CRT receipt date is showing on a response letter in Prod.  Closing this card.
