### ISSUE TITLE
SPIKE: Order of search operators

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1161]
We are trying to do a personal description search on 'lease OR repossession' AND 'veteran', but many of the results that surface do NOT have the word 'veteran' in the personal description

Sample search here: 
https://crt-portal-django-prod.app.cloud.gov/form/view/?status=new&status=open&violation_summary=lease%20OR%20repossession%20AND%20veteran&no_status=false

Sample result that does NOT include 'veteran'
https://crt-portal-django-prod.app.cloud.gov/form/view/122669/?next=%3Fper_page%3D15%26status%3Dnew%26status%3Dopen%26violation_summary%3Dlease%20OR%20repossession%20AND%20veteran%26page%3D1&index=0

cc: @billyhunt

**Comment by billyhunt** [comment]
@randyabramson and @blaughman 

I looked into this, and the way we have it set up, the search is broken up by 'OR' first, and then AND.  So the search lease OR repossession AND veteran breaks down to 

'lease' OR 'repossession AND veteran'

So, until we add quotes, to do the search you would want to do, use

"lease AND veteran OR repossession AND veteran"

to get the results you are after.

**Comment by randyabramson** [comment]
Ah...OK @billyhunt  thanks for the quick analysis. I think we need to flesh this out as a proper card and prioritize this in an upcoming sprint.

Randy
