### ISSUE TITLE
SPIKE - Controlled Correspondence Requirements

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1168]
## User story:
As a UX/UI expert, I want to understand the requirements associated with controlled correspondence so that I can design the user experience.

## Objective:
The goal of this ticket is to document the needs of CRT staff who process controlled correspondence.

## Ticket background:
The portal team is tackling the task of incorporating controlled correspondence into the portal.  This will continue the process of making the portal the one stop shop for all types of incoming correspondence.

## Technical Notes/Questions
- Should controlled correspondence be a standalone page - like the Team Management page?
- Do we modify the proform?
- Loop Amanda and Sean into our thoughts on incorporating this material
- Loop in Anthony for reporting purposes
- Will need to update the database dictionary

**Comment by chinelo-ikejimba** [comment]
Currently running system demonstrations with CRT staff to understand their process, pain points, concerns, and ideas.

**Comment by chinelo-ikejimba** [comment]
Completed 8 total contextual interviews with individuals in the following CRT sections:
- ADM
- DRS
- ELS
- VOT
