### ISSUE TITLE
SPIKE - Performance enhancements

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1176]
I looked into two areas of improvement on the site this week.  

1.  On the report detail page, our "frequent fliers" who have a lot of reports, generate many small queries.  One for each report.

![image](https://user-images.githubusercontent.com/6232068/149348619-1e8cc45b-62f2-472d-9990-b780fceb58a3.png)
Notice the number of sql queries, 525, which is 25 normal ones and then one for every complaint with the same email.  We currently have no upper limit on this, which has serious performance and security concerns.

I propose that we had a maximum upper limit of records we would display in the Total Complaints box, a link to see more (or perhaps lazy loading), and offer some of the most important information to Intake Specialists at the top of the box (@chinelo-ikejimba)

2. The other performance issue looked at was the one we have already attended to to see if additional gains are possible.  Specifically, I implemented a solution @LindsayYoung  had created but not merged in, because she had to leave before it could be completed, to compare how that worked with our existing solution.  

The results are interesting.

Current query for related emails
<img width="1990" alt="Screen Shot 2022-01-13 at 9 00 46 AM" src="https://user-images.githubusercontent.com/6232068/149400180-02588900-d41e-4529-840a-034406d4d152.png">

Lindsay's solution.  
<img width="1997" alt="Screen Shot 2022-01-13 at 9 01 09 AM" src="https://user-images.githubusercontent.com/6232068/149400287-6f2d7731-74b7-439c-94f8-56e4ed88f31d.png">

Look at the SQL time for both.  Lindsay's is about 120ms faster.  A little over a 10th of a second.  A solid improvement, but possibly not enough to justify the changeover now.  I think there are ways to get performance improvements that would get a better return on investment, for now at least.

**Comment by blaughman** [comment]
Staging is working as expected.  Ready for Production.
