### ISSUE TITLE
Update/Remove Hate Crime / Human Trafficking Language from Landing Page?

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1181]
## User story:
As a Product Owner, I want to remove, or update, hate crime language on the landing page to reflect the current experience.

## Objective:
The goal of this ticket is to reduce confusion for the public.

+ [x] Add "Get help for hate crimes" button to bottom "Victim of a hate crime" section of home page. (see attached design doc)

+ [x] Link to this https://civilrights.justice.gov/hate-crime-human-trafficking

+ [x] Add translations

+ [x] add translated alt text? 

Link to 

## Key result:
We want the public to have a clear understanding that the FBI is the appropriate Agency to receive hate crime reports.

## Ticket background:
We removed the hate crime question and incorporated a standalone page with links to the FBI for hate crime reports.  The landing page still explains hate crimes/human trafficking even though those complaints are directed elsewhere.

## Technical Notes
- The FBI link is an internal site and will not need a modal

## Translations
- [x] English
Get help for hate crimes
- [x] Spanish
Consiga ayuda en relación con un delito de odio
- [x] Traditional Chinese
為尋求仇恨犯罪的幫助
- [x] Simplified Chinese
为寻求仇恨犯罪的帮助
- [x] Vietnamese
Nhận sự giúp đỡ khi gặp phải những hành vi phạm tội do thù hận
- [x] Tagalog
Humingi ng tulong para sa mga krimen ng pagka-poot
- [x] Korean
증오 범죄에 대한 도움 요청

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson 

To stay consistent with the Victim of Human Trafficking navigation on the landing page, the design places a button in the Victim of a Hate Crime section.

The button navigates viewers to: https://civilrights.justice.gov/hate-crime-human-trafficking

<img width="536" alt="Screen Shot 2022-01-24 at 5 03 50 PM" src="https://user-images.githubusercontent.com/92807659/150872602-cf6b3436-2261-4edc-a725-dc7e795353f0.png">



[Design Handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Aug-2021-Working-pages-(Copy)?node-id=540%3A6946)

**Comment by blaughman** [comment]
@chinelo-ikejimba @randyabramson This looks good to me.  We can add this to the ready for dev swimlane.

**Comment by billyhunt** [comment]
+ [ ] Refresh your cache.  Then go to the home page, click "Workplace discrimination or other employment-related problem".  From the dropdown select "Victim of a hate crime"
+ [ ] is the "Get help for hate crimes" button there?  
+ [ ] Click the button and make sure you are taken to the "hate-crime-human-trafficking" page.

**Check the following languages**

+ [ ] Spanish
Consiga ayuda en relación con un delito de odio
+ [ ] Traditional Chinese
為尋求仇恨犯罪的幫助
+ [ ] Simplified Chinese
为寻求仇恨犯罪的帮助
+ [ ] Vietnamese
Nhận sự giúp đỡ khi gặp phải những hành vi phạm tội do thù hận
+ [ ] Tagalog
Humingi ng tulong para sa mga krimen ng pagka-poot
+ [ ] Korean
증오 범죄에 대한 도움 요청

**Comment by blaughman** [comment]
All tests passed.  Moving to UAT.
