### ISSUE TITLE
Change activity log language from 'Report Opened' to 'Report Viewed'

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1182]
## User story:
As a Product Owner, I want the activity log to say 'Report Viewed' instead of 'Report Opened' when a CRT user first views a report.

## Objective:
This will reduce confusion in the activity log when audits are performed.

## Key result:
Less audit questions

## Ticket background:
When a CRT user first views a report, the activity log captures this as 'Report Opened.' A user changing the status of a report will also capture that activity as the status changing from "New or Closed" to "Open." This has confused users and we are hoping to minimize confusion in the next GAO audit.

## Acceptance criteria:
Given I am on the view all table
when I select a record and go to the complaint detail page
then I see "Report viewed:
"Username viewed report at..."

**Comment by blaughman** [comment]
Need  to update the portal dictionary once this is complete.

**Comment by blaughman** [comment]
#977

**Comment by billyhunt** [comment]
Test checklist: 

+ [ ] From the filter page, open an unopened report, make sure that the activity log reads "Report viewed" and not "Report Opened
+ [ ] From the the report detail page, click the "Next" button to an opened report, make sure that the activity log reads "Report viewed" and not "Report Opened
+ [ ] Open a previously opened report, make sure there is only one "Report Viewed" entry in the activity log.

**Comment by blaughman** [comment]
Tests passed in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Functions as intended in Staging.  Ready for Production.
