### ISSUE TITLE
Controlled Correspondence Requirements (synthesis)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1183]
## User story:
As a product owner, I want to understand the needs of users associated with controlled correspondence.

## Findings

- Share opportunity areas
- Highlight potential blockers
- Provide design recommendations

**Comment by chinelo-ikejimba** [comment]
@randyabramson @blaughman 

Here's my draft synthesis document outlining the workflow process for the CRT to complete controlled correspondence with some opportunity areas highlighted.

Let me know your feedback and I can edit as needed.

![Draft Controlled Correspondence Process](https://user-images.githubusercontent.com/92807659/151583597-4a647d7f-6b00-4163-8feb-86b9183ec5e4.png)

**Comment by blaughman** [comment]
@chinelo-ikejimba Great job detailing the many steps in the lifecycle of a controlled correspondence letter.

**Comment by chinelo-ikejimba** [comment]
@billyhunt @louh 

Tagging you two for visibility on the synthesis of controlled correspondence workflow from my previous comment above.

**Comment by randyabramson** [comment]
Great work, @chinelo-ikejimba !

**Comment by blaughman** [comment]
Requirements gathered and synthesized.  Will reopen this card as soon as JMD gives us feedback on eCATS enhancements, licensing, etc.
