### ISSUE TITLE
TECH TASK: upgrade Python version to 3.9.9

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#1185]
## User story:

As a developer i should be able to upgrade current python version 3.9.7 to 3.9.9
CI/CD pipeline and cloud.gov now supporting python 3.9.9 during CI/CD deployment.
Python 3.9.9 change log for reference [here](https://docs.python.org/release/3.9.9/whatsnew/changelog.html#python-3-9-9-final).

## Objective:

Avoid any CI/CD Blocker during deployment.

## Key result:

CI/CD should log should display deployed python version 3.9.9 instead of 3.9.7

## Ticket background:

Cloud.gov and CI/CD have upgraded their build pack which support 3.9.9 can cause future CI/CD deployment to fail with older python version 3.9.7.

## Acceptance criteria:

 [ ] Check DEV CI/CD log showing python version 3.9.9

**Comment by blaughman** [comment]
No issues found during Dev bug bashing.

**Comment by blaughman** [comment]
No issues in Staging when testing.
