### ISSUE TITLE
A | B form letter testing

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1187]
## User story:
As a Product Owner, I want feedback on two types of responses so we can deliver better outgoing messaging.

## Key result:
Increase public trust in our processes

## Ticket background:
We want to showcase two different response types to intake specialists to drive future development.  One response will have links and a list of resources all in one.  The other response will have a 'list of resources' link which will direct the recipient to a standalone page with the resources displayed in a more presentable format (focus on mobile view).

**Comment by louh** [comment]
@blaughman  @randyabramson  Here are screenshots of two options we demo'ed today. Please download and send to anyone who wants to take a closer look!

Option A: Text email, shorter content, link to resource page on portal website.

![Screenshot 2022-02-03 at 16-41-31 MailHog](https://user-images.githubusercontent.com/2553268/152438094-f758093b-47e8-4d4a-9ff6-6ab38c293e29.png)

![Screenshot 2022-02-03 at 16-41-45 Civil Rights Division - Department of Justice - Get help for hate crimes and human traffi](https://user-images.githubusercontent.com/2553268/152438099-b432b178-95a3-4009-bf45-4cd554fa8167.png)

Option B: HTML email with formatted resource list.

![optionB](https://user-images.githubusercontent.com/2553268/152438114-a43ea2f3-a28e-4b44-8174-0fe69ad96bfd.png)

**Comment by louh** [comment]
Mobile views
![Screen Shot 2022-02-03 at 17 16 11](https://user-images.githubusercontent.com/2553268/152438356-3689a0c3-7265-41dc-a1f0-105623be927a.png)
![Screen Shot 2022-02-03 at 17 15 51](https://user-images.githubusercontent.com/2553268/152438357-f2af6a42-45a8-4275-8bd6-0ba46dc11775.png)

**Comment by blaughman** [comment]
Findings complete.  Closing this card.
