### ISSUE TITLE
Wireframe - Updated Helper text for Search 2.0

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1194]
## User story:
As a Product Owner, I want the search helper text to capture the new search features so that end users clearly understand the full capabilities of the function.

## Objective:
Enhance search results for relevant records

## Key result:
Better search resulting from increased understanding.

## Ticket background:
As developers add code to enhance intake specialists search capabilities, we need to update our helper text in the filter area of the view all table.  This may require a bigger popup modal to capture all the available functions.  We need a wireframe to capture this new experience.

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson @billyhunt @louh 

Please share feedback on these updated designs for the Advanced Search helper text.

**Image 1. Updated advanced search language with View Search Examples link.**
![Search - advanced tools](https://user-images.githubusercontent.com/92807659/154314096-b216fccf-dd6f-412b-ab28-6aead23446a3.png)


**Image 2. Search Examples page (navigated to through "View Search Examples" link).**

![Search Examples - page](https://user-images.githubusercontent.com/92807659/154314847-4a057cec-7ce7-4d15-9bc0-94bdea6e0e73.png)

**Comment by louh** [comment]
@chinelo-ikejimba The last example should be `Mask AND (Vaccine OR Shot)` (the explanation text has it right, but other than that, the instructions are correct.

@randyabramson @blaughman To make another page, this will need its own path (URL). Something like `/form/help/search-examples`. What do you suggest?

**Comment by blaughman** [comment]
@louh @chinelo-ikejimba @randyabramson @ilodidoj @billyhunt I have no issue with the suggested URL, but would like Imran to weigh in on this.

**Comment by chinelo-ikejimba** [comment]
Thanks @louh for the feedback, I updated the design to reflect that correction.

Here is the [Design Handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Aug-2021-Working-pages-(Copy)?node-id=644%3A9323) for the Advanced Search screens.

**Comment by blaughman** [comment]
Appears and functions as expected in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Appears and functions as intended in Staging.  Ready for Production.
