### ISSUE TITLE
Add a standalone page for HCE resources

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1199]
## User story:
As a product owner, I want a standalone page with HCE's resources list so that the public will receive more meaningful responses.

## Objective:
The goal of this ticket is to improve the public users experience.

## Key result:
This will increase the public's trust in our processes and redirect the public to other agencies that may be of help to them.

## Ticket background:
After A|B testing with our intake staff, we decided to adopt a hybrid approach to outgoing messaging.  This standalone page will be our first attempt at utilizing this new approach.  

## Acceptance criteria:
1) Given I am a public user receiving a new HCE form letter
when I get to the bottom of the response 
then I see a 'List of Resources' link

2) Given I am a public user receiving a new HCE form letter
when I click on the 'List of Resources' link
then I am directed to a standalone page with the resources and clickable links

## Technical Notes
- The standalone page will be in the same format as the hate crimes / human trafficking page
- Standalone page will need to be accessible
- Page will need to follow guidance for external redirects
- Will need a URL for the new page

## Source of Truth
[HCE resources page (updated changes).docx](https://github.com/usdoj-crt/crt-portal-management/files/8099228/HCE.resources.page.updated.changes.docx)
[Housing Resources - Spanish Translation.docx](https://github.com/usdoj-crt/crt-portal-management/files/8119315/Housing.Resources.-.Spanish.Translation.docx)

**Comment by louh** [comment]
The source of truth document (https://github.com/usdoj-crt/crt-portal-management/issues/1112) uses the URL `civilrights.justice.gov/housing-resources` for the standalone page, so that's where I'll put it.

**Comment by louh** [comment]
@blaughman @randyabramson The link for Office of Public & Indian Housing is no longer on the "source of truth" document. Can you confirm that's supposed to go away?

**Comment by blaughman** [comment]
@louh I'll check with HCE regarding this issue.

**Comment by blaughman** [comment]
@louh This is the link for that resource:
https://www.hud.gov/program_offices/public_indian_housing/pha/contacts

**Comment by louh** [comment]
Cool, thanks for confirming @blaughman. That's the same link as in the original letter, so nothing to change on my end.

**Comment by louh** [comment]
@blaughman Thanks - great catch, this appears to be a Chrome-specific issue. I'll make a fix soon.

**Comment by blaughman** [comment]
@louh Confirmed with HCE that they want to keep the ABA information with the updated link.  I updated the source of truth in the card.  Thanks for your understanding on this.

**Comment by blaughman** [comment]
@louh @ilodidoj @billyhunt The Spanish translation was added to the Source of Truth.  

cc: @randyabramson @chinelo-ikejimba

**Comment by blaughman** [comment]
HCE approved the content of the standalone page in Dev.  All links are working as intended.  Moving to UAT.

Great work @louh

**Comment by blaughman** [comment]
Page functions as intended in Staging.  Keyboard navigation also worked as intended.  Ready for Production.

**Comment by blaughman** [comment]
Page functions and appears as intended in Production.  Closing this card.
