### ISSUE TITLE
Translation Checklist

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1200]
## User story:
As a Product Owner, I want a translation checklist so that translation requests are less confusing.

## Objective:
Improve synergy within the portal team.

## Ticket background:
A checklist for translated material will lead to less confusion for engineers when implementing the new material.

**Comment by billyhunt** [comment]
@blaughman can you share this checklist in this ticket?

**Comment by ilodidoj** [comment]
@billyhunt @blaughman  Checklist is an internal process, not for open source public sharing.  You can have the link to get from  here or share via internal email attachment / link (preferred)

**Comment by billyhunt** [comment]
I looked over the checklist and it looks good to me.

**Comment by blaughman** [comment]
Checklist can be accessed at:
http://crtspace/sites/SP2013/II/crtcollaboration/DocumentForCollaboration/Complaint%20Portal/Translation%20Checklist
