### ISSUE TITLE
EOS - Dept of Ed OCR Referral Form Letter

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1204]
## User story:
As a Product Owner, I want to add a referral letter for EOS (Educational Opportunities Section) so that they can redirect reports to the Department of Education.

## Objective:
Provide a tool to remove a blocker from closing reports.

## Key result:
EOS backlog will decrease.

## Ticket background:
If EOS is unable to assist with an incoming report, they primarily refer a report to one of two federal agencies - Dept of Ed or EEOC.  They will utilize the same process that DRS uses with their referrals to other agencies.

## Acceptance criteria:
1) Given I am on the complaint detail page
when I click on the 'Contact complainant' button
then I see a list of form letters

2) Given I am on the 'Contact complainant' list of form letters
when I scroll the list sorted in alphabetical order
then I see a form letter labeled 'EOS - Department of Ed OCR Referral Form Letter'

## Technical Notes
- The EOS letters will use the same template as the DRS referral letters
- the Subject line will indicate the letter is from the Educational Opportunities Section
- This form letter will need translation, we will implement the English version first
- This letter should capture the email and physical mailing address if both are present

## Source of Truth
[EOS - Dept of Ed OCR Referral Form Letter.docx](https://github.com/usdoj-crt/crt-portal-management/files/8083058/EOS.-.Dept.of.Ed.OCR.Referral.Form.Letter.docx)

**Comment by blaughman** [comment]
@billyhunt @ilodidoj  The output is not matching the source of truth.
Output:
[EOS - Dept of Ed output.pdf](https://github.com/usdoj-crt/crt-portal-management/files/8217876/EOS.-.Dept.of.Ed.output.pdf)
Source of Truth snip:
![image](https://user-images.githubusercontent.com/52507395/157528090-4788f6b8-247b-4b44-8987-8b58b593c702.png)

**Comment by blaughman** [comment]
@billyhunt @ilodidoj Cancel that.  The printout appears as intended.  I was only testing email.  Long day.

**Comment by blaughman** [comment]
@ilodidoj @billyhunt The link to the Department of Ed website should be clickable in the email.  Can we get this fixed before it deploys to Staging?
![image](https://user-images.githubusercontent.com/52507395/158185603-e20ab560-b222-43c2-83d4-c7343afdfc6c.png)

**Comment by billyhunt** [comment]
Yes.  I am on it!

**Comment by blaughman** [comment]
[Issue resolved.  Functions and appears as intended.  Moving to UAT.

**Comment by blaughman** [comment]
Functions as intended in Staging.  EOS confirmed function and appearance.  Ready for Production.
