### ISSUE TITLE
EOS - EEOC Referral Form Letter

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1205]
## User story:
As a Product Owner, I want to add a referral letter for EOS (Educational Opportunities Section) so that they can redirect reports to the EEOC.

## Objective:
Provide a tool to remove a blocker from closing reports.

## Key result:
EOS backlog will decrease.

## Ticket background:
If EOS is unable to assist with an incoming report, they primarily refer a report to one of two federal agencies - Dept of Ed or EEOC.  They will utilize the same process that DRS uses with their referrals to other agencies.

## Acceptance criteria:
1) Given I am on the complaint detail page
when I click on the 'Contact complainant' button
then I see a list of form letters

2) Given I am on the 'Contact complainant' list of form letters
when I scroll the list sorted in alphabetical order
then I see a form letter labeled 'EOS - EEOC Referral Form Letter'

## Technical Notes
- The EOS letters will use the same template as the DRS referral letters
- the Subject line will indicate the letter is from the Educational Opportunities Section
- This form letter will need translation, we will implement the English version first
- This letter should capture the email and physical mailing address if both are present

## Source of Truth
[EOS - EEOC Referral Form Letter.docx](https://github.com/usdoj-crt/crt-portal-management/files/8083070/EOS.-.EEOC.Referral.Form.Letter.docx)

**Comment by blaughman** [comment]
@billyhunt @ilodidoj Was this merged into Dev?  I don't see it on the menu of available form letters.
![image](https://user-images.githubusercontent.com/52507395/157522563-73385a49-114b-49b6-b4a3-7a1f9673ddb8.png)

**Comment by blaughman** [comment]
This letter appears and functions as intended in Dev.  EOS attorney (MD) approved the content as well.  Moving to UAT.

**Comment by blaughman** [comment]
@billyhunt @ilodidoj I found the same issue on this card as well.  We will need to update the first paragraph to capture the date of intake for each individual report.
![image](https://user-images.githubusercontent.com/52507395/158400806-19a4827e-7392-4e50-8a76-2966f8994664.png)

**Comment by billyhunt** [comment]
@blaughman A fix is in.  Can you confirm on dev?

**Comment by blaughman** [comment]
Functions as intended in Staging.  EOS confirmed function and appearance.  Ready for Production.

**Comment by blaughman** [comment]
Letter is functioning as expected in Production.  Closing this card.
