### ISSUE TITLE
console.log errors when trying to print a template

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1210]
I noticed some errors when trying to print templates on dev.  To reproduce.  Go in to print a letter, then click cancel.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/6232068/156049726-61d94593-a979-4541-8bc9-db391a57b063.png">

**Comment by louh** [comment]
Possibly related? https://github.com/usdoj-crt/crt-portal-management/issues/1144

**Comment by billyhunt** [comment]
Probably.  I will check out both.

**Comment by blaughman** [comment]
Tested canceling various form letters in Dev - no errors present.  Moving to UAT.

**Comment by blaughman** [comment]
No issues detected in Production.  Closing this card.
