### ISSUE TITLE
Fix Bug in forms API endpoint.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1215]
Certain custom form letters are creating a javascript error if a report does not have an address associated with it.  Its probably not a huge huge deal, because it only happens if there is no contact information at all, so there is not much use for a response from the DOJ.  That being said, it needs to be fixed.  

<img width="2154" alt="image" src="https://user-images.githubusercontent.com/6232068/156594159-9774e3f0-a2e2-49e7-bdfd-b07e77e08b81.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/6232068/156594189-03613695-44c7-4b11-9f55-2c6b1d7cdffa.png">

**Comment by blaughman** [comment]
All tests passed in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
No errors in Staging.  Ready for Production.

**Comment by blaughman** [comment]
No errors in Production.  Closing this card.
