### ISSUE TITLE
View all table displays same report multiple times on queries with multiple selections in filters

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1216]
## Summary
During on-screen pairing, EOS noted that a query with multiple selections in the 'reported reason' filter produced results with one record displaying multiple times in the view all table.  

## Detail
One report is being displayed multiple times if the public submission checked multiple reasons for discrimination.  The result totals are skewed very badly as a result.

### Steps To Reproduce

1. select multiple boxes in the reported reason filter and apply the filter
2. check view all table for one report ID displayed multiple times

### Expected Behavior
One report should display one time despite how many types of discrimination are associated with that report.

### Actual Behavior
One report can display as many as 14 times if all 'reported reason' boxes were checked when submitting that report and the CRT user checked all the 'reported reason' boxes when running a query.

## Suggested Actions
One report displays in the view all table regardless of how many categories match the query.

## Screen Captures of behavior
Filters
![image](https://user-images.githubusercontent.com/52507395/156806129-358422b7-c899-420b-900b-b837a208e6ea.png)
Results
![image](https://user-images.githubusercontent.com/52507395/156806252-46f90e62-178d-4f61-b4f6-a8214d81424e.png)

**Comment by blaughman** [comment]
After testing in Dev, this unexpected behavior is no longer present.  Moving to UAT.

**Comment by randyabramson** [comment]
On staging, I no longer see the bug described above. Working as intended.

**Comment by blaughman** [comment]
Query records appear as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Production records are not displaying duplicates records in queries.  Closing this card.
