### ISSUE TITLE
SPIKE - Additional team management page feature(s)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1217]
## User story:
As a CRT user, I want to know how many, and what type of, form letters my section sends out so I can report the data to management.

## Objective:
Enhance reporting functions of the portal.

## Key result:
Increased transparency with section's responses to incoming inquiries.

## Ticket background:
As the portal matures, we want to build out the team management page based upon feedback from intake specialists. The intake staff voted to green light the form letter count feature as their highest priority.  We want to understand if the suggested layout and function are feasible given the tools at our disposal.

## Mockup
@chinelo-ikejimba captured the suggested layout using feedback from the intake staff.  That feedback was visualized in card #1214.

**Comment by ilodidoj** [comment]
@billyhunt @randyabramson my personal thought and practices, lessons learned during working with gsa/18f; keeping new features as a separate card (adding graph / chart) is better managed than lumping all together.  It helps others to see, review and adopt to a pattern for the new feature in portal development.

**Comment by ilodidoj** [comment]
@billyhunt @randyabramson @blaughman it also helps isolate any issues related to introduction of a specific new feature, troubleshoot and resolve accordingly.

**Comment by billyhunt** [comment]
Sounds good! We can make a separate ticket for the JS portion.

**Comment by blaughman** [comment]
Closing this card.  A number of cards have been created as a result of this research.
