### ISSUE TITLE
Remove form letters as available selections in Production

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1223]
## User story:
As a Product Owner, I only want to see the intended form letters in the dropdown list when I select the 'contact complainant' button.

## Objective:
Reduce 'noise' in the form letter menu.

## Key result:
Minimize instances of the wrong form letter sent out.

## Ticket background:
There are a number of form letters in the dropdown list that either have been replaced with a newer form letter, or were test email templates that should not be in there.

## Acceptance criteria:
1) Given I am on the complaint detail page
when I select the contact complainant button
AND I select the template dropdown
then I only see the intended form letters for selection

## Technical Notes:
Here are the letters that should appear in the menu
- [ ] CRM R1 Form Letter
- [ ] CRM R2 Form Letter
- [ ] CRM - Referral to FBI
- [ ] CRT Auto response
- [ ] CRT - Comments & Opinions
- [ ] CRT - Constant Writer
- [ ] CRT - EEOC Referral Letter
- [ ] CRT - No Capacity
- [ ] CRT - Non-Actionable
- [ ] CRT - Request for Agency Review
- [ ] DRS - Dept of Ed Referral Form Letter
- [ ] DRS - DOT Referral Form Letter
- [ ] DRS - EEOC Referral Form Letter
- [ ] DRS - HHS Referral Form Letter
- [ ] EOS - Dept of Ed Referral Form Letter
- [ ] EOS - EEOC Referral Form Letter
- [ ] HCE - Form Letter
- [ ] IER - Form Letter
- [ ] SPL - Referral for PREA Issues
- [ ] SPL - Standard Form Letter
- [ ] Trending - General COVID inquiries

## Pending Translation
- HCE Form Letter
- SPL Standard Form Letter
- EOS Referral Letters

**Comment by billyhunt** [comment]
@blaughman can you add which form letters would you like removed?

**Comment by blaughman** [comment]
@billyhunt 
HCE - Referral for Housing/Lending/Public Accommodation
All four HCE test emails
Trending - Arbery
Trending - Floyd

**Comment by blaughman** [comment]
@billyhunt Yes, please remove those letters as well.  Thanks.

**Comment by blaughman** [comment]
Form letter menu appears as intended in all languages in Dev.  Moving to UAT.

**Comment by randyabramson** [comment]
@blaughman  @billyhunt  @eileen-nava  @ilodidoj  On staging, I still see the following letters available (that are not on the master list above). I see these after doing the 'deluxe' refresh (developer tools > clear cache and hard refresh):

* TEST HCE FORM LETTER FULL HTML
* TEST HCE FORM LETTER HYBRID
* TEST HCE FORM LETTER (TEXT WITH EXTERNAL SOURCES)

**Comment by billyhunt** [comment]
As I recall we decided to keep those in until we do the HTML auto reply.  Is that correct @ilodidoj?

**Comment by blaughman** [comment]
Menu appears as intended in Production.  Closing this card.
