### ISSUE TITLE
Force emptying of cache and hard reload on production release

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1224]
## User story:
As a Product Owner, I want the system to force a hard reload so that end users can enjoy the latest content without disruption.

## Objective:
Enable access to new content when it is deployed without manual processes

## Key result:
Reduce unexpected behaviors in the product.

## Ticket background:
Every production release, end users must be reminded to do a hard refresh of their browser to enjoy the latest content.  The latest production release required a number of users to take additional steps to enable the update.  We are hoping to eliminate the need for end users to manually refresh their browser.

## Acceptance criteria:
1. Given I am an end user
when a new production release is deployed
then I have access to the new content without performing any manual tasks

**Comment by billyhunt** [comment]
After pairing with @eileen-nava and @ilodidoj we decided not to implement an automated solution at this time, as the chances of problems creeping in is not worth it.  Here is a prototype of a solution (works locally, untested in the cloud) that might be worth checking in a bit.  https://github.com/usdoj-crt/crt-portal/tree/bh/1224-cache-bust-prototype

For now, we are going to cache bust by hand.  When a developer modifies a javascript file, they can add a version number to it in the template.  

For example

`<script src="{% static 'js/form_letter.min.js' %}"></script>`
would be changed to 
`<script src="{% static 'js/form_letter.min.js?version=2.0' %}"></script>`
