### ISSUE TITLE
Special Campaigns Research (Phase 1)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1226]
## User story:
As a CRT user, I want to understand outreach campaigns so I can utilize the portal as part of the process.

## Objective:
Intake reports associated with links embedded in outreach materials.

## Key result:
Metrics associated with effectiveness of outreach campaigns
Increased data consistency

## Ticket background:
Numerous sections utilize outreach campaigns to spotlight topics of interest to the Division.  We are hoping to add a link to the portal as part of these efforts, and denote that a report was associated with a particular campaign.

**Comment by chinelo-ikejimba** [comment]
Thanks for sharing those 2 problems @randyabramson, I noted them down as objectives to address through the research.

**Comment by chinelo-ikejimba** [comment]
[Justice Department Special Campaigns - Research Plan.pdf](https://github.com/usdoj-crt/crt-portal-management/files/8342183/Justice.Department.Special.Campaigns.-.Research.Plan.pdf)
