### ISSUE TITLE
Design - HTML version of auto-reply

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1228]
## User story:
As a Product Owner, I want to incorporate HTML formatting into the auto reply to improve our trust with the public.

## Objective:
Improve outbound messaging

## Key result:
Increased public trust

## Ticket background:
Now that we can incorporate HTML into our emails, we want to add this formatting to the auto-reply automatically generated by the system at the time of a public submission.  This is the most frequently used form letter in the system.

## Mockup
[Design Handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Reporting-Portal-Designs-and-Handoff?node-id=777%3A7533)

<img width="782" alt="Yes typography" src="https://user-images.githubusercontent.com/92807659/159059655-e1dfb94b-1e3e-4e61-8f83-45c29a390534.png">

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson here are design options for the auto-reply email.

Let me know if option you prefer.

---

### Option 1. Simple text
<img width="782" alt="No typography" src="https://user-images.githubusercontent.com/92807659/158630360-f12aa6e5-ed7b-4545-94cd-b8dc15dc918b.png">

---

### Option 2. Typography
<img width="782" alt="Yes typography" src="https://user-images.githubusercontent.com/92807659/158630438-8a4b1211-b3af-422b-9e63-f5c3ad0f838e.png">

**Comment by blaughman** [comment]
I'm a fan of option 2.  It makes the three expectations stand out more for the reader.

**Comment by randyabramson** [comment]
Yes...definitely option 2. Nice work @chinelo-ikejimba !

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson glad to hear you both vote for Option 2!

We can regard it as a template until the auto-reply wording gets reviewed by the Plain Language folks.

@billyhunt @eileen here is the [Design Handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Reporting-Portal-Designs-and-Handoff?node-id=777%3A7533)

**Comment by blaughman** [comment]
Closing this card.  Superseded by card #1251.
