### ISSUE TITLE
HCE Form Letter - Traditional Chinese

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1237]
## Source of Truth
[Traditional Chinese HCE Form Letter.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/8336139/Traditional.Chinese.HCE.Form.Letter.final.docx)

## Technical Notes
This letter will be listed as HCE - Form Letter (Traditional Chinese) in the dropdown menu

**Comment by billyhunt** [comment]
Since I am already in the traditional chinese translation, and there is some weirdness when I compile with HCE resources, I am going to take this ticket if its ok with you @ilodidoj

**Comment by blaughman** [comment]
Functions and appears as intended.  Moving to UAT complete.

**Comment by blaughman** [comment]
Letter appears and functions as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letter generated properly in Production, but not sent, and transaction was canceled.
