### ISSUE TITLE
HCE Form Letter - Spanish

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1242]
## Source of Truth
[HCE Form Letter - Spanish_SP.docx](https://github.com/usdoj-crt/crt-portal-management/files/8344167/HCE.Form.Letter.-.Spanish_SP.docx)

## Technical Notes
This letter will be listed as HCE - Form Letter (Spanish) in the dropdown menu

**Comment by blaughman** [comment]
@billyhunt @eileen-nava @ilodidoj @randyabramson @chinelo-ikejimba It appears some of the links aren't clickable in the form letter.  
[HCE Form Letter - Spanish test reply.pdf](https://github.com/usdoj-crt/crt-portal-management/files/9212263/HCE.Form.Letter.-.Spanish.test.reply.pdf)

**Comment by blaughman** [comment]
For comparison, the English version has clickable links throughout the form letter.
[HCE Form Letter - English test reply.pdf](https://github.com/usdoj-crt/crt-portal-management/files/9212274/HCE.Form.Letter.-.English.test.reply.pdf)

**Comment by billyhunt** [comment]
I have looked into this, and the form letters are the same.  Something with the internationalization (translation) system is making the links act differently.  This is probably not going to be a quick fix.  Let me know if you would like me to look into fixing the system.

**Comment by ilodidoj** [comment]
@billyhunt @blaughman original source of truth Spanish word document may also not have correct URL.  Need to check for HTTP or HTTPS, also link include local desktop location instead of public site link. Let's all pair before making changes.

**Comment by blaughman** [comment]
Letter is working as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letter is available for selection and appears as intended in Production.  Closing this card.
