### ISSUE TITLE
HCE Resource Page - Spanish

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1248]
## Source of Truth
[Housing Resources - Spanish Translation.docx](https://github.com/usdoj-crt/crt-portal-management/files/8344256/Housing.Resources.-.Spanish.Translation.docx)

## Technical Notes/Questions
- Can we link this page from the HCE Form Letter (Spanish)?

**Comment by billyhunt** [comment]
No we cannot link to the spanish language translation.  The way translations work, they do not have unique urls.

**Comment by billyhunt** [comment]
@blaughman Can I get a translation for "Housing section resources" (the page title)

**Comment by billyhunt** [comment]
@blaughman checked, and its "Recursos de la Sección de Vivienda"

**Comment by blaughman** [comment]
Page appears as intended.  Moving to UAT.

**Comment by blaughman** [comment]
Page appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Page appears and functions as intended in Production.  Closing this card.
