### ISSUE TITLE
HTML Auto-reply form letter

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1251]
## User story:
As a CRT user, I want HTML formatting added to the auto-reply form letter so that the public receives more professional looking correspondence.

## Objective:
Improve the appearance of outgoing correspondence.

## Key result:
Increase public trust

## Ticket background:
Every complainant that files a report on the portal receives an auto-reply upon submission. Currently, that auto-reply is in plain text.  We want to add HTML formatting for a more professional looking response.

## Acceptance criteria:
1) Given I am on the public-facing complaint form
when I click the 'Submit Report' button
then I will receive an auto-response with HTML formatting

## Source of Truth
We are using Option 2 - Typography from card #1228 
[HTML Auto-reply.pdf](https://github.com/usdoj-crt/crt-portal-management/files/8363664/HTML.Auto-reply.pdf)

## Technical Notes/Questions
- When this is added we will need to remove the plain-text letter from the selection menu.

**Comment by billyhunt** [comment]
Moving back to dev ready as we reprioritize.

**Comment by billyhunt** [comment]
@blaughman @randyabramson @ilodidoj @eileen-nava Can you look at this email and let me know what you think?  


<img width="722" alt="auto-reply-email" src="https://user-images.githubusercontent.com/6232068/170083915-1cbdf096-5001-4357-9356-59a60253a64e.png">

**Comment by chinelo-ikejimba** [comment]
Nice progress @billyhunt!

Please adjust with the following notes:

1. Remove the divider lines above "What to Expect" and "What You Can Do Next" but keep the divider line above "Please note: Each week..."
2. Bold "Please note:"
3. Italicize the full section of "Please note: Each week, we receive...."
4. Resize the widths of the icons to make them more proportionate. They look squished in height.

After those adjustments, it'll be good to go.

**Comment by blaughman** [comment]
Functions and appears as intended in Outlook and Gmail.  Moving to UAT.

**Comment by blaughman** [comment]
Functions as intended in Staging when sending via Outlook.  Personal gmail account was not in the approved domains, so unable to confirm in that system.  Closing this card.
