### ISSUE TITLE
Create API Endpoint for Reports Viewed

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1252]
## What does this change?

Adding an endpoint to see reports accessed for new Team Management Page.

## Screenshots (for front-end PR):

**Home API endpoint**
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/6232068/160453900-12c6b474-95c1-4434-a9c6-c57f650c4a76.png">

**With no Arguments**
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/6232068/160457464-18b8c581-5ce4-4b23-bd1a-eca39b96f8dc.png">

**With arguments**
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/6232068/160457636-d35d43d8-602b-4e62-9460-49444bae16be.png">

**Logged out**
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/6232068/160454039-9717098a-a37e-4f3f-94cf-df689f4c040e.png">

**Comment by billyhunt** [comment]
@blaughman 

Here is a checklist.

+ [ ] Make sure the Report Count api endpoint is available at http://localhost:8000/api
+ [ ] Check the Report Count API to make sure its functioning.  For example, the following link should return a count of all reports accessed in March by "USER_1" http://localhost:8000/api/report-count/?create_date_start=2022-03-01&create_date_end=2022-03-31&intake_specialist=USER_1
+ [ ] Log out and make sure you cannot access http://localhost:8000/api/report-count You should get the following message. "detail": "Authentication credentials were not provided."

**Comment by blaughman** [comment]
@billyhunt I'm not sure I can test this.  Clicking on the link in the first test check produced this result:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/52507395/161097297-034cf63f-cce8-42ce-8802-9cf3518c33bf.png">

**Comment by billyhunt** [comment]
Hi Bill.  Sorry I missed this.  I updated the links to work with staging.  Can you check it out and let me know if it works?
