### ISSUE TITLE
Pairing session(s) - Design/UX

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1255]
Chinelo and Becky will pair to talk shop.

Potential topics:
- Where will the VOT pamphlet reside?
- User testing
- Homepage 2.0 / Education center

**Comment by chinelo-ikejimba** [comment]
[User research plan](http://crtspace/sites/SP2013/II/crtcollaboration/_layouts/15/WopiFrame2.aspx?sourcedoc={4ba83eae-1a25-4d6e-ab85-e07d222ad99c}&action=view&wdAccPdf=0&wdparaid=A3F917) created to carry out the following phases for addressing interest in education materials on the public-facing CRT complaint portal
- Discovery
- Design
- Delivery

Discovery phase of interviewing stakeholders and producing updated personas begins in Sprint 69.

**Comment by chinelo-ikejimba** [comment]
User feedback sessions progress:
- PRA approved for conducting research
- Participants recruited
- Sessions scheduled

Card good to close.
