### ISSUE TITLE
Special Campaigns Research (Phase 2)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1256]
## User story:
As a product team member, I want to understand how sections use outreach to connect with the public so that I can integrate those efforts into the portal.

## Objective:
With the research plan in place, we can now interview stakeholders.

## Key result:
- Greater understanding of outreach efforts

## Ticket background:
Sections have previously used 800 numbers and email boxes for special campaigns.  We're hoping to add the portal as a viable intake solution for those campaigns.  

## Related Work
#1226 - Phase 1 (Research Plan)

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson 

**Participant recruitment update**

SPL clarified that they are only comfortable involving their staff/interns in providing design feedback. SPL is **not** comfortable involving their community outreach contacts.

I'll make arrangements with Regan (when she's back in office) to schedule sessions with SPL staff/interns.

**Comment by blaughman** [comment]
Closing this card.  Next steps are cards #1267 and #1268.
