### ISSUE TITLE
SPIKE - Surge playbook

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1257]
## User story:
As a product owner, I want to plan for surges to ensure the stability of the system.

## Technical Notes/Findings:

**Comment by randyabramson** [comment]
Scratch doc here: http://crtspace/sites/SP2013/II/crtcollaboration/DocumentForCollaboration/Complaint%20Portal/Surge%20Playbook/Surge%20Playbook%20SCRATCH.docx?d=w4bd575685af54608a24c17b0f2dd346c

**Comment by blaughman** [comment]
@billyhunt Can you add to the scratch doc?  We were hoping to capture your thoughts on how a person can likely break our system.

**Comment by randyabramson** [comment]
Updated draft - http://crtspace/sites/SP2013/II/crtcollaboration/DocumentForCollaboration/Complaint%20Portal/Surge%20Playbook/Surge%20Playbook%20DRAFT%20v3.docx?d=w860e57a07e0a4c0d8463179748fecbc9

**Comment by randyabramson** [comment]
@blaughman  @billyhunt  @ilodidoj  @chinelo-ikejimba  @eileen-nava  

I think this document is in good shape, but there are some open questions in there that I could use your help on. Maybe in the next cards meeting, we can review it as a group:

http://crtspace/sites/SP2013/II/crtcollaboration/DocumentForCollaboration/Complaint%20Portal/Surge%20Playbook/Surge%20Playbook%20DRAFT%20v4.docx?d=w4419c4d559b9418fb0d2c1f3343def5c
