### ISSUE TITLE
SPIKE - Email Send Failure Alerts

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1259]
**Background:** We currently use the GovDelivery platform to send out Emails directly from the Reporting Platform. Emails are sent manually (one by one) but our ‘auto-reply’ responses are automatically sent. We can see Email send failures in the Admin console, but our team doesn’t regularly look at that failure volume. Hence, we are concerned that there might be a breakage between the Portal and GovDelivery and we wouldn’t know about it. The result is that the public wouldn’t be getting auto-replies from us and we would not be aware of the issue. 

**Current Failure Performance:** 
February, 2022 – 11,508 total sent (252 failed, about 10 per day) 
March, 2022 – 9,959 total sent (203 failed, about 9 per day) 

**Development Ask:** We would like an automated Email alert sent to Bill Laughman, Imran Lodi and Randy Abramson any time failures exceed 20 per day. 

Note: It would be ideal if this alert was sent outside the GovDelivery system, if possible.

**Comment by blaughman** [comment]
Closing this card for now.  We will research a report from the admin console to flag any day where less than XXX letters were sent.
