### ISSUE TITLE
TECH TASK: Troubleshooting CI/CD deployment issue

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#1260]
## Summary

CI/CD Deployment is failing in prod env for deployment.
We are exploring the issue.

### Steps To Reproduce

1. Deploy the release branch on prod env
2. View log for deployment task
3. Log display USDSWS gulp resolve error
<img width="1075" alt="Screen Shot 2022-04-07 at 11 31 42 AM" src="https://user-images.githubusercontent.com/53233196/162236628-d490bab9-63d6-4713-97aa-5e8e31bb605e.png">

https://github.com/uswds/uswds-gulp/commit/4f2e1ef06f5fde76cba2b136b683ab22a258e6a8

**Comment by blaughman** [comment]
@billyhunt Is the deploy issue resolved?  Can we close this card now, or wait until the next Production release?

**Comment by billyhunt** [comment]
It is working in staging and dev, but not prod yet.  I would suggest we keep it open until the prod release.
