### ISSUE TITLE
Spike - Exact Match filter

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1276]
## Background:
We have identifed a new repeat writer who is submitting up to 105 reports per day (with the exception of Sunday). We're concerned that we might see 'write in campaigns', possibly from various writers that don't supply email addresses.

An 'exact match' and 'near exact match' filter on the personal description will help us find these reports quickly.

We see several phases of this project:

1. An 'exact match' filter - personal description is exactly the same across multiple reports
2. A 'near exact match' filter - 80% of the text in the personal description is the same
3. A new 'repeat writer' dashboard - lists both repeat writer names and trending 'exact matches' across personal description

**Comment by ilodidoj** [comment]
@randyabramson @chinelo-ikejimba can you please also provide some design guideline for this on filter tabs how this would look like.

**Comment by randyabramson** [comment]
@ilodidoj Let's discuss what is possible with the team and go for a MVP for phase 1. Once we get that down, we can turn it over to @chinelo-ikejimba for testing/design.

**Comment by blaughman** [comment]
MVP - exact match of personal description.

**Comment by eileen-nava** [comment]
@randyabramson I'm writing up tickets related to this and investigating how to identify exact/near matches at the database level.  Could you please clarify what you mean by
> trending 'exact matches' across personal description
Do we want to flag if there's been a recent spike in personal descriptions matching?  If so, how many exact matches would we want to see, and in what time period, before flagging it as a trend?
Thanks!

**Comment by eileen-nava** [comment]
I've specced out a technical approach to this and made more concrete tickets about implementation, such as #1290.  Is it okay if I mark this spike as done?

**Comment by blaughman** [comment]
That works for me.  Closing this card.
