### ISSUE TITLE
Assess/Update Maintenance Pages

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1295]
## User story:
As a CRT user, I want the maintenance pages assessed/updated to reflect current procedures.

## Objective:
Ensure the public is aware with appropriate pages/messaging if we are experiencing any technical issues.

## Key result:
Increased public trust

## Ticket background:
Maintenance pages were created over two years ago.  We need to assess these pages are still accurately reflecting our current procedures.  Any needed updates should be reflected with new cards.

**Comment by randyabramson** [comment]
@blaughman @ilodidoj  @chinelo-ikejimba 

Here's my assessment of error pages:

1. Root directory error page - not present:
If I add characters to the root URL, https://civilrights.justice.gov/dwwq, I get the odd, brown Welcome to DOJ Federated Services page

2. Report error page - present:
If I add characters to the report url, I get the correct error page. Ex: https://civilrights.justice.gov/report/wefw
@blaughman  - do you want the email there?

Note: original error card is at https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/usdoj-crt/crt-portal-management/707

Question for @ilodidoj  - if the system is completely down, should we run a drill of how we can redirect the url to a different domain that would house the error page of how else to contact us?
