### ISSUE TITLE
Update ClamAV

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1298]
Periodically we need to update our clamAV-rest local docker and circle ci/cd docker to the latest release version.
This PR will update the calmAV version to ajilaag/clamav-rest:20220511
Ref: [Git source](https://github.com/ajilaag/clamav-rest)
Ref: [Docker Image](https://hub.docker.com/r/ajilaag/clamav-rest/tags)

**Comment by ilodidoj** [comment]
This been deployed to prod a while ago.  Closing the card..

**Comment by ilodidoj** [comment]
completed and deployed.
