### ISSUE TITLE
Update localstack

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1299]
Our version of localstack, which mimics AWS S3 buckets, is behind, and needs to be updated.
For current localstack documentation go here: [Local stack docs](https://docs.localstack.cloud/overview/)
For latest docker image for localstack go here: [Local stack official docker image](https://hub.docker.com/r/localstack/localstack)

**Comment by ilodidoj** [comment]
completed and deployed.

**Comment by ilodidoj** [comment]
completed and deployed to prod.
