### ISSUE TITLE
Address some issues on form-letters endpoint

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1302]
I found some issues with the form-letters endpoint that need to be addressed.  We are not using this endpoint currently, but need to make these changes before we can do the work on the team-management page.

**Comment by billyhunt** [comment]
- [ ] check in https://crt-portal-django-dev.app.cloud.gov/admin/actstream/action/ and make sure there is an action in there that says "not_approved_email@a.com not in allowed domains, not attempting to deliver CRT - Non-Actionable." (If not, try and send an email that is not approved).
- [ ] Go to http://crt-portal-django-dev.app.cloud.gov/api/form-letters/?assigned_section=ADM
- [ ] See if you get results.  
- [ ] Make sure you do not get a 500 error.

**Comment by ilodidoj** [comment]
@billyhunt @eileen-nava @JackRyan1989 just fyi, we only restrict email contacts on dev and stage; therefore, results to similar error as mentioned here for wrong email as well as wrong domain.  We allow any email address in prod as long as it fits the email address format.  There will be no action item entry on the activity table for failed email by the system or TMS client. Only on the TMS error field will capture any error return through webhook or initial TMS client msg sent.

**Comment by billyhunt** [comment]
Yeah, I don't think the error will happen on production.  Just dev and staging.

**Comment by blaughman** [comment]
This functions as expected in Staging.  Closing this card since it won't affect Production.
