### ISSUE TITLE
Fix bad DB migration that is removing the Disability Protected Class on new databases.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1309]
0067_populate_new_choice_fields.py is removing the disability Protected class.  We don't see the problem on prod, dev, or staging now, (I wonder if someone modified it in the admin panel), but if we ever refreshed the database it would crop up.  We should write a targeted migration to add this class back if it is removed.

Local DB
<img width="585" alt="image" src="https://user-images.githubusercontent.com/6232068/173871898-c5a22c7a-2afb-45a9-a149-401fbeb53c83.png">
(notice the disability option is not available).

**Comment by blaughman** [comment]
Disability appears in Production.  Closing this card.
