### ISSUE TITLE
Spanish - Landing Page - Contact the FBI link

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1314]
## Summary
Text is invisible after the upgrade

## Detail
Post upgrade
<img width="348" alt="image" src="https://user-images.githubusercontent.com/52507395/174356294-fd9e9475-72f0-42ae-81fa-d2f4c95623d9.png">

Pre-upgrade
<img width="338" alt="image" src="https://user-images.githubusercontent.com/52507395/174356389-7222d669-4140-4c62-a626-0b9c2b2e84b4.png">

**Comment by billyhunt** [comment]
@blaughman and @randyabramson, I am working on this PR, and @JackRyan1989 pointed out that it used to have an external link.  

https://github.com/usdoj-crt/crt-portal/pull/1196

My question is, do we still want the external icon? I didn't think we used it on links to other parts of the Department of Justice.

**Comment by blaughman** [comment]
Link appears as intended.  Moving to UAT.

**Comment by blaughman** [comment]
Link appears as intended in Production.  Closing this card.
