### ISSUE TITLE
Participant Recruitment Education Center

### ISSUE THREAD

**Issue by chinelo-ikejimba** [usdoj-crt/crt-portal-management#1316]
## Objective:
Recruit design research participants to schedule sessions for Education Center interviews on the public-facing Reporting Portal.

## Key result:
Recruit minimum of 5 (max of 15) participants per approved PRA request.

## Ticket background:
[Portal User Experience Research Plan doc](http://crtspace/sites/SP2013/II/crtcollaboration/_layouts/15/WopiFrame2.aspx?sourcedoc={4ba83eae-1a25-4d6e-ab85-e07d222ad99c}&action=view&wdAccPdf=0&wdparaid=A3F917)

## Acceptance criteria: 

- [x] Launch recruiting Touchpoints module (launches after report submission)
- [x] Export contacts from Touchpoints module
- [x] Start screening and scheduling sessions with selected participants

**Comment by chinelo-ikejimba** [comment]
@randyabramson 

How does this language sound for replacing the current Touchpoints module at the end of the CRT report form with one for research recruitment? 

Also, let us know if we need additional approval from leadership before we launch the recruitment module.

> **Blue tab** [that triggers Touchpoints module to appear] 
> Volunteer for remote design research?
> 
> **Modal content**
> DOJ/CRT – Volunteer for our remote design research sessions
> If you are interested in being selected to share your feedback about the Civil Rights Reporting Portal website with our design research team, please enter your name and email below.
> 
> Volunteer spaces for design research feedback sessions are limited. Our design research team might contact you with the email that you share in this short form in order to schedule a remote session with you. 
> 
> _Please note: Participation in design research feedback sessions will not affect the processing of reports submitted through the Civil Rights Porting Portal._
>
>[GSA Privacy Statement for design research](https://www.gsa.gov/reference/gsa-privacy-program/privacy-act-statement-for-design-research)

(cc @beckyslogeris @blaughman)

**Comment by beckyslogeris** [comment]
@chinelo-ikejimba - I'm worried that folks might not know what remote design research is... what about this?

**Blue tab** 
Help us improve this site

**Modal content**
Share your thoughts!
We are working to improve the Civil Rights Reporting Portal and want to hear your feedback. Feedback sessions will be online and participants will be paid for their time. Spaces are limited. If you are interested, please enter your name and email below.

_Please note: Participation in feedback sessions will not affect the processing of reports submitted through the Civil Rights Porting Portal._

**Comment by beckyslogeris** [comment]
LOL @randyabramson - great minds think alike ;)

**Comment by chinelo-ikejimba** [comment]
Thanks @beckyslogeris and @randyabramson for the feedback.

I'm fine going with the rewording Becky wrote. Sound good Randy?

**Comment by randyabramson** [comment]
@chinelo-ikejimba  @beckyslogeris  - I realize that the language above matches Becky's minus the issue we discussed over Email.

Anyway...jumping to the headline...the above is APPROVED by Killian! Free to move forward.

**Comment by chinelo-ikejimba** [comment]
06/29/22 - Touchpoints recruitment module included in deployed staging and working as expected.

**Comment by chinelo-ikejimba** [comment]
07/05/22 - Volunteer contacts being exported from Touchpoints module.
