### ISSUE TITLE
Feedback from Intake Specialists re: Routing Guide

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1317]
## Ticket background:
In ticket #1306 @chinelo-ikejimba laid out the desig for a new routing guide. We want to use this ticket to record feedback on these designs from Intake Specialists

**Comment by chinelo-ikejimba** [comment]
06/23/2022 - Intake Specialists voted for the Page View with both a print option and the ability open the page as a separate tab.

Next Steps
- [ ] Add print page button to Page View design
- [ ] Check with devs on printing page and making page open in a separate tab

---
**Top vote: Page View design**
<img width="1582" alt="routing guide - page view" src="https://user-images.githubusercontent.com/92807659/175360905-e700bf54-5183-4829-88f0-24a6a34648c0.png">

**Comment by randyabramson** [comment]
@chinelo-ikejimba - for record keeping, here are the initials of the folks who supported the 'new page' option

* AS likes the idea of putting the guide in a new tab as opposed to the modal; AB and NT supports this idea
* Support for a ‘print this page’ option

**Comment by chinelo-ikejimba** [comment]
Feedback recorded. Ticket is set to close.
