### ISSUE TITLE
update padding on button on search example page.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1322]
The padding on the "Back to All" button on the search example page needs adjustment.  

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/6232068/175322430-c74e4b23-ffd8-42fc-9d50-fd34b10f9018.png">

**Comment by blaughman** [comment]
Appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Appears as intended in Production.  Closing this card.
