### ISSUE TITLE
Need to update translation on landing page.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1329]
An updated link section on the landing page is in english when it should be in a native language. 

<img width="448" alt="image" src="https://user-images.githubusercontent.com/6232068/176200369-482fc7eb-11d0-4c97-86cb-be404b37b598.png">

**Comment by blaughman** [comment]
All test passed in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
All tests passed in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Language is translated on the landing page.  Closing this card.
