### ISSUE TITLE
'X' is missing on iPhone when clicking the "Here's how you know" link at the top.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1331]
When viewing the site on an iPhone, if you click "Heres How you Know" the "X" svg on the grey button to close the window is missing at the top.  
![Contact the Civil Rights Division  Department of Justice](https://user-images.githubusercontent.com/6232068/176253002-1462ef7c-b647-4307-a625-a4fa80412c32.jpeg)

**Comment by blaughman** [comment]
'X' appears in mobile (Safari).  Moving to UAT.

**Comment by blaughman** [comment]
X now appears on mobile.
