### ISSUE TITLE
Menu button for both Chinese languages - Mobile

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1337]
Post-update is vertical:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/52507395/176728352-d746f51a-08d4-4ebd-8715-622628ca744a.png">

Current Production experience:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/52507395/176728469-ca318ea4-c3b0-40b7-95c1-a6c9259307ac.png">

**Comment by blaughman** [comment]
@billyhunt @eileen-nava @ilodidoj I'm still getting this after clearing the cache and hard refresh
<img width="182" alt="image" src="https://user-images.githubusercontent.com/52507395/177599351-f2b3c1ea-58f6-4c47-870a-ec7a181eefdc.png">
Thoughts?

**Comment by eileen-nava** [comment]
I approved [the PR that fixes this bug](https://github.com/usdoj-crt/crt-portal/pull/1204#pullrequestreview-1030268037) but we haven't merged it yet.  You'll see the fix after we merge it.  Thanks for pointing this out!

**Comment by blaughman** [comment]
Button appears as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Appears as intended in Production.  Closing this card.
