### ISSUE TITLE
Menu button needs translation on mobile - (Vietnamese, Korean, & Spanish)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1342]
## Current Experience
<img width="182" alt="image" src="https://user-images.githubusercontent.com/52507395/177600513-ad19c72b-ff26-406a-b55a-ceda967b2a3f.png">

<img width="183" alt="image" src="https://user-images.githubusercontent.com/52507395/177600578-24522515-db7d-41b2-a254-0e003debc964.png">

<img width="181" alt="image" src="https://user-images.githubusercontent.com/52507395/177600698-300d5d25-dde7-48b3-b81d-7fc66aaf87b1.png">

**Comment by billyhunt** [comment]
See https://github.com/usdoj-crt/crt-portal-management/issues/1329 for PR

**Comment by blaughman** [comment]
Menu buttons appear as intended in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Menu button appears as intended in all languages in Production.  Closing this card.
