### ISSUE TITLE
Remove down arrows on language selection buttons

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1344]
## Screenshots (for front-end PR):

Before: (Note pesky down arrows next to language buttons)
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/6232068/177825048-d3a34052-634c-4e94-b725-88ce6fa05f1a.png">

After:
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/6232068/177824841-69ccfcc6-7fc7-4942-ba2c-a6ac79fb745b.png">

**Comment by blaughman** [comment]
Down arrows are no longer next to the buttons.  Moving to UAT.

**Comment by blaughman** [comment]
Arrows do not appear in Production.  Closing this card.
