### ISSUE TITLE
Phone number filter

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1345]
## User story:
As a CRT User, I want a filter for phone numbers of public complainants so that I can find reports more efficiently.

## Objective:
Locate reports absent a name or email

## Key result:
Increased efficiency of CRT users

## Ticket background:
A number of public complainants leave voicemails that are then added to the portal by CRT staff.  CRT staff have requested a phone number filter because there are times the public doesn't leave a name, or the name is unintelligible on the voicemail.  This feature has been requested previously, but concerns were voiced about the lack of consistency of this data field.

## Acceptance criteria:
1) Given I am on the view all table
when I look in the filters area
then I see a text box filter labeled 'phone number'

2) Given I am in the phone number text box
when I enter a phone number
then I can only enter numerical characters

3) Given I am in the phone number text box
when I enter non-numerical characters in the text box
then I see an error message indicating 'Numerical characters only'

## Technical concerns/questions
- Would it make more sense to allow CRT users to put in (, ), - and strip them out after apply filters is clicked? (This seems to be the consensus)
- The appearance and function should match the other filters on the view all table.

**Comment by chinelo-ikejimba** [comment]
@blaughman @randyabramson @ilodidoj @billyhunt @eileen-nava @JackRyan1989 

Here's the design for the **Phone number** filter that's placed next to **Contact email**.

[Design handoff](https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Reporting-Portal-Designs-and-Handoff?node-id=1156%3A9777)

---
![phone number filter](https://user-images.githubusercontent.com/92807659/179087798-3f72ab39-b6a4-44f2-9f54-190d44b16e58.png)

**Comment by blaughman** [comment]
@chinelo-ikejimba @billyhunt @eileen-nava @ilodidoj I know Billy has been testing this.  Please work w/ Chinelo on the helper text format/location once we know how this needs to work.  We can either make a new card for the helper text, or add a wireframe to this card.  
cc: @randyabramson

**Comment by blaughman** [comment]
Filter works as intended in Staging.  Holding off on moving this card until deep dive participants have a chance to test as well.

**Comment by blaughman** [comment]
Feedback from DRS, "if we do not add space or add dash between numbers, you do not get a result, other than that I think it works with no other issues."  We can make another card for helper text, if needed.

**Comment by blaughman** [comment]
Functions as expected in Production.  Closing this card.
