### ISSUE TITLE
"Get Help" is not translated to Traditional Chinese on the human trafficking and hate crimes page

### ISSUE THREAD

**Issue by eileen-nava** [usdoj-crt/crt-portal-management#1349]
I found this bug in both prod and develop.

Prod Screenshot
![Screen Shot 2022-07-08 at 11 33 21 AM](https://user-images.githubusercontent.com/80347702/178024342-c76fa838-2bfb-4afe-aee2-9b0542c17669.png)

Develop Screenshot
![Screen Shot 2022-07-08 at 11 35 00 AM](https://user-images.githubusercontent.com/80347702/178024502-7e30a06c-bf0c-4f49-a147-e40a398eaa8a.png)

**Comment by blaughman** [comment]
Text is translated in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Translation appears in Production.  Closing this card.
