### ISSUE TITLE
Time zone fix

### ISSUE THREAD

**Issue by eileen-nava** [usdoj-crt/crt-portal-management#1351]
Time zone errors are a common cause of bugs in programming.  In order to improve code quality, I will do an audit of how we handle time zones in the codebase.

**Comment by eileen-nava** [comment]
Update: I reviewed the logs and found only one time zone warning, for report closed date.  I have a fix for this error and will submit it for review.

**Comment by blaughman** [comment]
Closing a report in Dev resulted in the correct timestamp applied to the record.  Moving to UAT.

**Comment by blaughman** [comment]
Closing a report in Staging resulted in the correct timestamp applied to the record.  Ready for Production.

**Comment by blaughman** [comment]
Closed records are accurately capturing the time in Production.  Closing this card.
