### ISSUE TITLE
Fix minimum date for report submission

### ISSUE THREAD

**Issue by eileen-nava** [usdoj-crt/crt-portal-management#1352]
When a user is submitting a report through the external site, they are able to submit a report for an event that occurred December 31, 1899.  They should only be able to submit a report from 1900 and later.

This error doesn't occur for the pro form.

**Comment by blaughman** [comment]
Error message appears requiring user to enter a date after 1900.  Functions as expected in Dev.  Moving to UAT.

**Comment by blaughman** [comment]
Functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Feature is working as expected in Production.  Closing this card.
