### ISSUE TITLE
Fix minimum date for `last_incident_year` for proform

### ISSUE THREAD

**Issue by eileen-nava** [usdoj-crt/crt-portal-management#1354]
Note: This ticket is related to ticket #1352 and to PR #1213.

When an internal user submits a report, they can choose an event date prior to 1900.  The proform currently has date validations on the `reciept date` [SIC] but not on the `last_incident_year`.  In order to make the external report and proform consistent, I will add a validation to `last_incident_year`.

**Comment by blaughman** [comment]
Minimum date functions as expected in Dev and Staging in all languages.  Ready for Production.

**Comment by blaughman** [comment]
Functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
This function can't be tested in Production without creating a bad record.  Closing this card.
