### ISSUE TITLE
Disaster Recovery Planning

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1355]
## User story:
As a product owner, I want to ensure we have plans in place for recovering from any expected/unexpected disasters.
- [x] Review existing internal Incident Drill and DR  document
- [x] Update internal Incident Drill and DR document with current information

## Objective:
Disaster planning and knowledge sharing

## Ticket background:
Any/all engineers should be prepared to recover from any disasters that may occur.  We want to ensure we have documentation for each potential disaster and clear explanations on how we recover from said disaster.  18F already had documentation for this.  We need to make sure the available documentation is still accurate and all possible scenarios are covered.

**Comment by ilodidoj** [comment]
@blaughman @randyabramson  @billyhunt please check the DR planning internal document for review. I posted the link on internal teams.
