### ISSUE TITLE
Education Center data synthesis

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1356]
Update this card with findings after synthesizing the data collected from user testing.

**Comment by chinelo-ikejimba** [comment]
Synthesis findings, including design recommendations, recorded in the follow PDF file to be reviewed on 08/09/22.

cc @blaughman @randyabramson @ilodidoj @billyhunt @JackRyan1989 

[Education Center  User Research Findings.pdf](https://github.com/usdoj-crt/crt-portal-management/files/9260923/Education.Center.User.Research.Findings.pdf)

**Comment by randyabramson** [comment]
This is really great @chinelo-ikejimba  and @beckyslogeris !!!

I was wondering if there were any insights about our navigation and how users would like to find the 'education' content. 

Looking at our NAV, I see we have links for 'Your Rights' and 'Report a Violation' - neither screams out to me on 'what we act on' or the like.

Just thinking out loud here...looking forward to your presentation!

cc: @blaughman

**Comment by chinelo-ikejimba** [comment]
Mural board link with initial findings and affinity map

https://app.mural.co/t/nava4113/m/nava4113/1652109188896/f61e17353d354a9f6dad8859a4f74b9f2cd89e6b?sender=u6e0432270361d5f6f7971140

cc @beckyslogeris @randyabramson @blaughman

**Comment by randyabramson** [comment]
BAT CAVE !!!!!   Thanks @chinelo-ikejimba  !!!
