### ISSUE TITLE
Add print capibility to rerouting page

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1364]
The new rerouting page should be printable.  This change will make sure the page is printed correctly, including the scrolling part in the middle.

**Comment by blaughman** [comment]
PDF shows all information as expected.  Moving to UAT.

**Comment by blaughman** [comment]
Print functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Functions as expected in Production.  Closing this card.
