### ISSUE TITLE
Election messaging

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1367]
We need to visualize the plan for election messaging.

The Voting Section indicated an approach with a banner and redirects for voter fraud, polling location questions, etc. is optimal.

Voting suggested the following verbiage:

**To report a threat against voters, threats against election officials, or election fraud, click here [tips.fbi.gov](https://github.com/usdoj-crt/crt-portal-management/issues/tips.fbi.gov) or call 800-CALL FBI.

If you are calling to find out your polling place location or hours, please refer to your state elections website or vote.gov.

Click here if you would like to report: 
-	Discrimination on the basis of race, color, or membership in a language minority group while voting or attempting to vote; 
-	Voter registration issues; 
-	Denial or lack of accessibility while voting;
-	Military or overseas absentee voting issues.**

**Issues to consider**

1. Is there any way to have this info on the home page or do we need a short 'Learn about voting issues, including voter fraud' banner/link at the top of the home page and links to a page formatted like https://civilrights.justice.gov/hate-crime-human-trafficking
2. Would we include a similar banner on the page 1 of the reporting portal form?
3. OR, would we have a small 'i' with a circle next to the voting primary reason module?
4. Note that there was interest in linking to the state by state resources: https://www.justice.gov/voting#Resources
5. Lastly, if we do a separate page, do we want to cherry pick more info from pages 11-12 from https://www.justice.gov/file/1517936/download?

**Comment by beckyslogeris** [comment]
@blaughman + @randyabramson - here's a draft timeline, let me know what you think:

- [ ] Week of Aug 8 - Design Mockups 
- [ ] Week of Aug 15 - Share w/ Bill & Randy
- [ ] Week of Aug 22 - User testing
- [ ] Week of Aug 29 - Revise mockups
- [ ] Week of Sept 5 - Share with voting
- [ ] Week of Sept 12 - Revise & finalize
- [ ] Week of Sept 19 - Hand off to dev

**Comment by randyabramson** [comment]
@beckyslogeris  this works! As @blaughman mentioned, as long as we get the design to dev by mid-September, we should be in good shape.

**Comment by randyabramson** [comment]
@beckyslogeris figma mocks here: https://www.figma.com/file/g9rb8IUGcgiJNJUNLrwG1T/CRT-Reporting-Portal-Designs-and-Handoff?node-id=1305%3A9773

**Comment by randyabramson** [comment]
@beckyslogeris  - here are my notes from the session with Bob. cc @blaughman 

1. Change first line text to say 'report a possible federal violation'

2. Change link order to place Vote.gov to second in lineup

3. Change vote.gov link to https://www.usa.gov/election-office 

4. Last link - Becky to flesh out last link to talk more about what you can see on each link

Additionally, we would like to launch this page in the 10/25 release.

Lasltly, we want to add the election examples from this page and link the 'learn more' language to this new page in the homepage module

**Comment by randyabramson** [comment]
Becky's lates mock here:
[Reporting Portal Voting Mockups_8.31.22.pdf](https://github.com/usdoj-crt/crt-portal-management/files/9464812/Reporting.Portal.Voting.Mockups_8.31.22.pdf)

**Comment by ilodidoj** [comment]
@randyabramson is the above final mockup dev team should follow, or we still finalizing?

**Comment by randyabramson** [comment]
@ilodidoj  - we are waiting for Bob and team to approve. Thanks for checking on status!

**Comment by blaughman** [comment]
@beckyslogeris I just noticed on the education page - can we swap the polling place and civil rights options on the nav menu to match the content that was shuffled per VOT's request?  

cc: @randyabramson @ilodidoj

**Comment by blaughman** [comment]
One more question - do we want the nav language to match the content on the right?  If so, one more small edit to the mock.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/52507395/187949833-2213aae2-d404-45c3-925a-5508cd80e0db.png">

**Comment by beckyslogeris** [comment]
Yes & yes! I'll do that now.

**Comment by blaughman** [comment]
Final copy for language on education page
[Portal.20220907-bob-edit (1).docx](https://github.com/usdoj-crt/crt-portal-management/files/9558090/Portal.20220907-bob-edit.1.docx)
