### ISSUE TITLE
Update linking on routing-guide svg

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1368]
There was an error in the link on the routing guide page that showed in dev, but not locally.  This PR will fix it. 

<img width="701" alt="image" src="https://user-images.githubusercontent.com/6232068/182945166-841a113c-285c-41f0-9d5a-c4ccda6d25f5.png">

**Comment by blaughman** [comment]
Appears as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Appears as intended in Production.  Closing this card.
