### ISSUE TITLE
add step one email to DB

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1370]
We want the email addresses listed in Step 1 of the rerouting guide to not be public, so we are adding them in the database.

Note: In the interests of time, we did not make these emails links, but I would suggest you do so at a future date when you can.  Also, the data structure might be revisited.

**Comment by blaughman** [comment]
@billyhunt @ilodidoj @randyabramson Let's close this card.  We will go with name only since this only faces internal users and the names can be selected in the address book.  Objections?

**Comment by ilodidoj** [comment]
@blaughman no objection.

**Comment by billyhunt** [comment]
Sorry, this card is unclear.  Its not about adding a mailto link, just the db field to add info.  You could add names or emails or whatever.  This card should be put into UAT if the work looks good.

**Comment by blaughman** [comment]
Feature works as expected.  Moving to UAT.

**Comment by blaughman** [comment]
Ready for Production.

**Comment by blaughman** [comment]
Functions as expected in Production.  Closing this card.
