### ISSUE TITLE
SPIKE - click tracking on voting education page

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1373]
## User story:
As a CRT user, I want to know how many public users clicked on links on the voting education page so that I can assess the effectiveness of the page.

## Objective:
Metrics

## Key result:
Gauge effectiveness of this approach for future campaigns

**Comment by randyabramson** [comment]
Hey @billyhunt @ilodidoj  the first stepfor this project is to insert the tag manger tracking code as instructed below. cc @blaughman 

1. Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-N6M8JRD');</script>



2.  Additionally, paste this code immediately after the opening <body> tag:


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N6M8JRD"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>


For more information about installing the Google Tag Manager snippet, visit our Quick Start Guide:
https://developers.google.com/tag-manager/quickstart

**Comment by ilodidoj** [comment]
@randyabramson we already have this incorporated a while ago, starting line 12 and line 83 of the base.html https://github.com/usdoj-crt/crt-portal/blob/develop/crt_portal/cts_forms/templates/base.html in October, 2020. Not sure do we need to change this or add additional script. CC: @blaughman @billyhunt

**Comment by randyabramson** [comment]
@ilodidoj as long as everything is inserted as specified on every page as written above, then we should be good to go!

**Comment by blaughman** [comment]
Closing this card.

**Comment by randyabramson** [comment]
For reference, to see this report, Filter on Behavior > Events > Top Events > Link Clicks 

Then filter on 'Events Label' and Secondary Dimension = Page
