### ISSUE TITLE
SPIKE - Ramifications of moving the VOT module on page 2 of form and proform for the election

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1380]
## User story:
As a CRT user, I need to understand how moving the voting module will impact the form views and automated testing.

## Objective:
Prepare for planned updates for the mid-term elections.

## Key result:
Minimize possibility of bugs.

## Ticket background:
We moved the modules for the last election and experienced a few minor bugs (branching questions, etc.).  We want to learn from the past, not repeat it.  We also have more automated testing than we did 2 years ago.  

Some references from 2020 pr

https://github.com/usdoj-crt/crt-portal/pulls?page=22&q=is%3Apr
https://github.com/usdoj-crt/crt-portal/pull/725/files/cb2917e9f099b3b2f032deafd4797a8d64cb9df1
https://github.com/usdoj-crt/crt-portal/pull/725
https://github.com/usdoj-crt/crt-portal/pull/724
https://github.com/usdoj-crt/crt-portal/pull/721/files

**Comment by blaughman** [comment]
#746

**Comment by ilodidoj** [comment]
@billyhunt let's pair on this card for tomorrow's pairing.

**Comment by blaughman** [comment]
We want to move the VOT module to the top of the list on page two of the public facing form
<img width="314" alt="image" src="https://user-images.githubusercontent.com/52507395/185974529-58d300ca-2517-48e3-b44a-12cf9f04fdfc.png">

**Comment by blaughman** [comment]
Page three of the public facing form is also impacted by the selection on page two.  Selections of the following modules will open branching questions - Workplace discrimination, School discrimination, Police misconduct, Commercial/Public location discrimination.  This same behavior will need to be addressed on the proform.
<img width="311" alt="image" src="https://user-images.githubusercontent.com/52507395/185975449-5d5a2934-cb5d-4bc4-b044-6c92ea24c708.png">

**Comment by blaughman** [comment]
Proform behavior
<img width="319" alt="image" src="https://user-images.githubusercontent.com/52507395/185975646-a41db26f-d8e9-41e8-bb1e-e2d99726a30d.png">

**Comment by ilodidoj** [comment]
@billyhunt I added all the PRs from 2020 in the ticket background section.  @billyhunt @blaughman we need to explore all testing pages impact on this changes, especially Pa11y and E2E tests scripts. No test script changes was done last time.
