### ISSUE TITLE
Add Voting Toggle

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1384]
Add a toggle so we can adjust the forms and site if we are in voting season.

**Comment by billyhunt** [comment]
#### Normal Mode
+ [ ] To start, create a report and make sure the sequence under primary concern matches what is on production
+ [ ] Create multiple reports with all the primary reasons.  Make sure the next tab after primary reason matches the selection.  
+ [ ] Create a couple of reports and edit them, make sure everything works.
+ [ ] Create Proform reports doing the same thing.  Try every primary concern, and make sure the contextual information is correct.  (Workplace should bring up "Public or Private Employer" for example)

#### Voting Mode (talk to dev to switch the site to VOTING_MODE
+ [ ] To start, create a report and make sure the sequence under primary concern is updated with "Voting" on top.
+ [ ] Create multiple reports with all the primary reasons.  Make sure the next tab after primary reason matches the selection.  
+ [ ] Create a couple of reports and edit them, make sure everything works.
+ [ ] Create Proform reports doing the same thing.  Try every primary concern, and make sure the contextual information is correct.  (Workplace should bring up "Public or Private Employer" for example)

**Comment by blaughman** [comment]
All features are working as intended.  Moving to UAT complete.

**Comment by blaughman** [comment]
Staging Testing:

#### Normal Mode
+ [ ] To start, create a report and make sure the sequence under primary concern matches what is on production
+ [ ] Create multiple reports with all the primary reasons.  Make sure the next tab after primary reason matches the selection.  
+ [ ] Create a couple of reports and edit them, make sure everything works.
+ [ ] Create Proform reports doing the same thing.  Try every primary concern, and make sure the contextual information is correct.  (Workplace should bring up "Public or Private Employer" for example)

#### Voting Mode (talk to dev to switch the site to VOTING_MODE)
+ [ ] To start, create a report and make sure the sequence under primary concern is updated with "Voting" on top.
+ [ ] Create multiple reports with all the primary reasons.  Make sure the next tab after primary reason matches the selection.  
+ [ ] Create a couple of reports and edit them, make sure everything works.
+ [ ] Create Proform reports doing the same thing.  Try every primary concern, and make sure the contextual information is correct.  (Workplace should bring up "Public or Private Employer" for example)

**Comment by blaughman** [comment]
Staging verified.  Ready for Production.

**Comment by blaughman** [comment]
Will test in Production when toggle is switched in late October / early November.
