### ISSUE TITLE
Add Voting education page

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1387]
## User story:
As a CRT user, I want an education page for those visitors who wish to report a voting concern around the time of the election.

## Objective:
Make a better user experience for the public

## Key result:
Fewer, better reports

## Ticket background:
We want to add a education page for those users who click the voting banner #1386 on the landing page around the time of the election.  This page will be added when the voting efficiencies are activated #1384.  

## Acceptance criteria:
1) Given I am in the Admin console
when I turn on voting content
then a voting education page is accessed when the voting banner is clicked on the landing page.

## Source of Truth
[Voting Content Translation (Spanish).docx](https://github.com/usdoj-crt/crt-portal-management/files/9601891/Voting.Content.Translation.Spanish.docx)

Refer to internal design location for this file:
Reporting Portal Voting Mockups_1386_1387_8.31.22

**Comment by randyabramson** [comment]
@ilodidoj - voting changed the order of the text on this page. Please see attached. cc: @blaughman 
[Portal 20220907-bob-edit.docx](https://github.com/usdoj-crt/crt-portal-management/files/9556089/Portal.20220907-bob-edit.docx)

**Comment by blaughman** [comment]
Page functions in Dev as expected.  Moving to UAT complete.

**Comment by blaughman** [comment]
Appears and functions as expected in Staging.  Shared w/ VOT team for final confirmation.

**Comment by blaughman** [comment]
Page is functioning as expected in Production.  Will create a new card to update the civil rights link to go to page one of the complaint form.
