### ISSUE TITLE
Reset order of landing page module

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1394]
## Ticket background:
After the voting toggle deploy, the landing page module is showing Voting as the top selection as the default view.

## Expected behavior
Workplace concerns should be the top selection if the voting toggle is turned off

## Current behavior
The page shows workplace concerns as the default view, but selecting the down arrow shows Voting as the top selection.

![image](https://user-images.githubusercontent.com/52507395/192043312-05d5c28c-9c6e-4783-8675-22b1c05ea383.png)

## Acceptance criteria:
1) Given I am on the landing page, understanding your rights module
when I click the down arrown
then I should see workplace concerns as the first topic.

**Comment by billyhunt** [comment]
I created another card to deal with this, so I am closing this out!  

https://github.com/usdoj-crt/crt-portal-management/issues/1396
