### ISSUE TITLE
Update landing page dropdown when page is in voting mode.

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1396]
The landing page should have voting prominently shown when the site is in voting mode.

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/6232068/192551308-872d62fa-54c9-43fd-9cf8-224a076483b5.png">

**Comment by billyhunt** [comment]
+ [ ] Check to see that when voting_mode is engaged, that voting is featured at the default for the civil rights violation examples. 
+ [ ] Make sure all links work in the dropdown.
+ [ ] When voting_mode is turned off, it should default to the normal behavior (workplace as default).  
+ [ ] Make sure all links work in the dropdown.

**Comment by blaughman** [comment]
All tests passed.  Moving to UAT complete.

**Comment by blaughman** [comment]
Appears and functions as expected with voting mode deactivated.  Ready for Production.

**Comment by blaughman** [comment]
Appears and functions as expected in Production.  Closing this card.
