### ISSUE TITLE
SPIKE - Admin console

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1397]
## User story:
As a CRT user, I want to understand how the admin console works so that I can develop new features.

Feature added so an admin can filter based on actor in the activity log.

<img width="2214" alt="image" src="https://user-images.githubusercontent.com/6232068/199086890-c2918d7f-ddce-465f-a2b5-01dde81044ea.png">

## Objective:
Increase our knowledge about the admin console as more reporting features are requested.

## Previous related request
#1365

**Comment by blaughman** [comment]
Functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
@billyhunt Is there any rhyme or reason for the ordering of the actors on the side panel?  Just curious, I could envision a user getting frustrated until we get some UX help on this feature.

cc: @ilodidoj @randyabramson

**Comment by billyhunt** [comment]
Yeah, thats kind of garbage.  Looks like its ordering by id and not name.  I will create a new PR to sort the names alphabetically.

**Comment by blaughman** [comment]
Thanks.

**Comment by billyhunt** [comment]
No problem!

**Comment by blaughman** [comment]
Function working as expected in Production.  Card #1420 created to address the side panel ordering.  Closing this card.
