### ISSUE TITLE
Tech Task: OWASP zap deployment blocker remove

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#1418]
## Objective:
OWASP scan included new warnings, which needs to be set in zap.conf file to remove deployment blocker.  Researched the current scan item and update accordingly.
WARN-NEW: Permissions Policy Header Not Set [10063]
WARN-NEW: Sub Resource Integrity Attribute Missing [90003] x 15

UPDATE: default tab setting on code editor caused conversion of tabs to space for the two new items added.
Added a fix PR to apply strict TAB format for the two new configuration items.

## Key result:
OWASP scan passed and deployment complete.

## Ticket background:
The latest owasp added new scan parameters, which are blocking portal deployment.  
![image](https://user-images.githubusercontent.com/53233196/198595804-6206123d-2682-44ef-aef8-4ea517fe3ba1.png)

![image](https://user-images.githubusercontent.com/53233196/198596011-403ef781-4a7e-4b0b-81b2-2140836d978b.png)

Research ref:
https://www.zaproxy.org/docs/alerts/10063-1/
https://www.zaproxy.org/docs/alerts/90003/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#example
https://resources.infosecinstitute.com/topic/introduction-owasp-zap-web-application-security-assessments/#gref
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#examples

## Acceptance criteria:
owasp scan passed on dev, stage and prod

**Comment by blaughman** [comment]
Release deployed without issue.  Closing this card.
