### ISSUE TITLE
Sort Actors admin actions filter

### ISSUE THREAD

**Issue by billyhunt** [usdoj-crt/crt-portal-management#1420]
We need to sort the Actors in the actions section of the admin panel so users can find the user they are looking for.  

https://user-images.githubusercontent.com/6232068/199086890-c2918d7f-ddce-465f-a2b5-01dde81044ea.png

**Comment by blaughman** [comment]
Panel appears and functions as expected in Dev.  UAT completed - ready for Staging deploy.

**Comment by blaughman** [comment]
Panel appears and functions as expected in Staging.  Ready for Production deploy.

**Comment by blaughman** [comment]
Panel appears and functions as expected in Production.  Closing this card.
