### ISSUE TITLE
Update LSC content - English

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1423]
## User story:
As a CRT user, I want LSC content updated so that it accurately reflects their organization's role.

## Objective:
Improve communication with the public

## Key result:
Improve trust with external stakeholders

## Ticket background:
ATJ and LSC met regarding content published on the portal. LSC expressed concern regarding our language related to their organization.  We shared all instances where their organization was mentioned and they have 5 areas they would like language updated.  

## Content to be edited

- [ ] Landing Page
- [ ] Confirmation Page
- [ ] Housing Resources Page
- [ ] Auto Response Form Letter
- [ ] EEOC Referral letter

## Source of Truth
[LSC.References.on.CRT.Reporting.Portal.RFlagg.edits.11.7.22 (1).docx](https://github.com/usdoj-crt/crt-portal-management/files/9955167/LSC.References.on.CRT.Reporting.Portal.RFlagg.edits.11.7.22.1.docx)

**Comment by billyhunt** [comment]
@blaughman I am not seeing anything filled out from the "No Capacity Form Letter" down.  Is that correct?

**Comment by blaughman** [comment]
@billyhunt Correct.  LSC did not have any objections to the language in those other locations.

**Comment by billyhunt** [comment]
Perfect!  Thank you!

**Comment by billyhunt** [comment]
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/6232068/202541650-ab2a48c9-a4df-4599-b373-7ed96e197081.png">

Do we want to get rid of the paragraph
![image](https://user-images.githubusercontent.com/6232068/202541713-1cd86e21-a2d7-40a3-8470-0f2a73e83ae0.png)

**Comment by blaughman** [comment]
@billyhunt The problem I have if we change the English, the other languages would have to change to match as well.  There is also mention of the American Bar Association that applies to that paragraph as well.  It wouldn't make sense to merge one organization, but not the other.

<img width="207" alt="image" src="https://user-images.githubusercontent.com/52507395/202558368-148360b8-2ad8-4d29-9586-f17017755947.png">

**Comment by billyhunt** [comment]
So you want to leave it in?  It's not in the document is the reason I ask. No skin off my nose either way.

**Comment by blaughman** [comment]
Can we pair on this in the morning?  I have to head out to pick up my son from school.

**Comment by billyhunt** [comment]
Absolutely!

**Comment by blaughman** [comment]
@billyhunt Ready to jump on a call?

**Comment by blaughman** [comment]
Dev Testing:
- [ ] Landing Page
- [ ] Confirmation Page
- [ ] Housing Resources Page
- [ ] Auto Response Form Letter
- [ ] EEOC Referral letter

**Comment by blaughman** [comment]
Staging testing:

- [ ] Landing Page
- [ ] Confirmation Page
- [ ] Housing Resources Page
- [ ] Auto Response Form Letter
- [ ] EEOC Referral letter

**Comment by blaughman** [comment]
All content confirmed in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Production Testing:
- [ ] Landing Page
- [ ] Confirmation Page
- [ ] Housing Resources Page
- [ ] Auto Response Form Letter
- [ ] EEOC Referral letter
