### ISSUE TITLE
Deactivate 'Trends' from the Production environment

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1431]
## User story:
As a portal developer, I want the Trends feature to be deactivated so that we can recover some memory from cloud deployment environment.

## Objective:
Minimize risk of Production failure due to memory constraints

## Ticket background:
Portal have a feature to capture the top 10 keywords on a weekly basis.  This feature was never used extensively and still runs every night.  We want to deactivate this feature since AP analyzes our data when we export it.

**Comment by ilodidoj** [comment]
@billyhunt I am working on this card.
