### ISSUE TITLE
Add 'select all' checkbox for the carrot column on the view all table

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1432]
## User story:
As a CRT user, I want a 'select all' checkbox for the carrot column so that I can efficiently process repeat writers.

## Objective:
Increase intake staff efficiency

## Key result:
Allow intake staff to focus on more meaningful reports

## Ticket background:
A single public user has filed over 15000 reports using the same personal description and only changing the 'location name.'  As the portal currently exists, CRT users much click the carrot on the view all table to view the personal description and trigger the report viewed activity.  On a single page with 50 reports, a user has to click the carrot 50 times to view each personal description.  This is time consuming and affecting staff efficiency and morale.

## Acceptance criteria:
1) Given I am on the view all table
when I look in the header column
then I see a checkbox above the carrot column

2) Given I am on the view all table
when I click the checkbox above the carrot column
then all the reports expand
AND
the report viewed activity indicator is captured

3) Given I am on the view all table
when I unselect the checkbox above the carrot column
then all reports collapse back to the normal view all table appearance
AND
the reports should still be labeled as 'viewed' in the activity column

4) Given I am on the view all table using a screen reader
when I hover over the carrot column select all checkbox
then the screen reader indicates 'Expand all reports checkbox' 

## Technical Notes/Questions
- This feature should function the same as the bulk actions checkbox feature
- Selecting the carrot column checkbox SHOULD NOT trigger the bulk actions modal
- Hovering over the checkbox should read 'Expand all reports checkbox' for a screen reader

**Comment by randyabramson** [comment]
@blaughman  - you might want to put in a comment here about how this feature works with the filter to change the number of reports on the view all table. Beyond that, I think this looks good!

Also, assuming the user can manually close individual report carrots still? Or are they disabled?

**Comment by blaughman** [comment]
Functions as expected in Dev.  Moving to UAT complete.

**Comment by blaughman** [comment]
Feature functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Functions as intended in Production.  Closing this card.
