### ISSUE TITLE
Onboard Designer/UX

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1435]
- [x] Get Email / Teams Access (HelpDesk)
- [x] Send laptop ?? (HelpDesk)
- [x] Phone + RSA access (HelpDesk)
- [x] Government training sessions (Randy check with HR)
- [x] Other software (MS Office, Adobe, etc.) (HelpDesk)
- [x] Invites to core meetings (Standup, Story Time, Sprint Kickoff, Retro, Deep Dive) – Randy / Bill
- [x] Review History/Goals/Personas of Project – Randy
- [x] Go over team wiki (Randy/Bill)
- [x] Virtual Meet and Greet with Engineers (Randy/Bill)
- [x] Github access (Imran)
- [x] Github overview (Randy/Bill)
- [x] Designers connect with Terri Youngblood (Randy/Bill)
- [x] DataViz – GA access (Randy)
- [x] DataViz – Connect with Anthony (Randy)

**Comment by nguyen-tina** [comment]
Hi @randyabramson -- should we set up some time to finish up the DataViz task?

**Comment by randyabramson** [comment]
@nguyen-tina  - do you want access to Google Analytics? It's really up to you. Also, we can check the Anthony item off as well, as we don't have any data viz projects on tap at the moment.

**Comment by nguyen-tina** [comment]
Yes, I'd like Google Analytics access for the portal. It'd be helpful to know what features our users are using frequently @randyabramson
