### ISSUE TITLE
Select all checkbox isn't indicated by a screen reader

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1444]
## User story:
As a visually impaired CRT user, I want the select all checkbox indicated by a screen reader so that I have the same experience as other users.

## Objective:
Improve accessibility

## Ticket background:
We strive for our site to be completely accessible.  During testing, it was discovered that the select all checkbox is not indicated by a screen reader.

## Acceptance criteria:
1) Given I am on the view all table
when I hover over the select all checkbox
then the screen reader indicates "Select all records checkbox"

**Comment by okkays** [comment]
As discussed yesterday, I think it's worth taking a look at what else on this page doesn't pass accessibility standards that we can update while we're there. Talking with @JackRyan1989, we might be able to handle some of the details in the rows better, as well.

I think it's worth doing a quick assessment of the rest of the page, too, and seeing what else we can knock out as quick wins for accessibility.

**Comment by blaughman** [comment]
Terri's findings:
- mega carrot heading has 2 labels (when you hit enter it should say "expanded" when you hit enter again it should say "collapsed" aria expanded=true (Jack says switch to button tags)
- select all records is indicated for the individual checkboxes
- expanded row first label is "blank" MAYBE use "record detail"

**Comment by okkays** [comment]
- Fixes to table (this was a lot of fun): https://github.com/usdoj-crt/crt-portal/pull/1300
- Underline link on homepage: https://github.com/usdoj-crt/crt-portal/pull/1301

**Comment by blaughman** [comment]
Updates are functioning as expected.  Moving to UAT complete.

**Comment by blaughman** [comment]
Updates are functioning as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
@ilodidoj @okkays I'm closing this card.  The card called for us to update the 911 link on the landing page.  I did notice that the link reads as nine hundred eleven instead of nine one one.  I'll make another card to update the way the screen reader picks up the link.   We had a similar issue previously #1080
