### ISSUE TITLE
Link tracking on Servicemember.gov webpage

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1448]
## User story:
As a CRT user, I want to track reports coming from the Servicemembers.gov page so that I can easily access all reports without multiple queries.

## Objective:
Easily access reports related to SVI initiatives

## Key result:
Increased transparency of SVI reports
Better analytics for the SVI page

## Ticket background:
The Policy Section oversees the Division's Servicemember related inquiries.  There is no routing pathway for these reports.  There is also no insight on which reports originate from the SVI webpage.  We want to add a campaign link to the two pathways from the SVI site that direct visitors to the portal.  This will allow POL staff to easily find reports requiring their attention. 

## Acceptance criteria:
1) Given I am on [Justice.gov's Servicemember how we can help page](https://www.justice.gov/servicemembers/how-we-can-help#complaint)
When I click the 'submit a complaint link
<img width="541" alt="image" src="https://user-images.githubusercontent.com/52507395/212954988-37b6864d-e919-499b-a83b-c17aab299fd8.png">
Then I am directed to the reporting portal with the link tracked

2) Given I am on [Justice.gov's Servicemember how we can help page](https://www.justice.gov/servicemembers/how-we-can-help#complaint)
When I select 'Department's Civil Rights Division Reporting Portal'
<img width="515" alt="image" src="https://user-images.githubusercontent.com/52507395/212970937-297f8b3e-fbc7-4712-919c-ff201c6cb63c.png">
Then I am directed to the reporting portal with the link tracked.

## Technical Notes
- The URL for this campaign is:
https://civilrights.justice.gov/report?utm_campaign=c49b0f71-deb0-482c-87b4-b56304a14c81
- We will need to work with Darren Wechsler to update the links

**Comment by okkays** [comment]
Optional, but could help with reporting down the line - I'd add the following tags to this, for later reporting on what specific links and broad sources are entering the portal:

To show the overall source: `utm_source=justice.gov`

And to distinguish between the two links on the page, something like:
`utm_content=scra` for the first, and `utm_content=civilrights` for the second.

Leaving two final links, one for each of the criteria above:

https://civilrights.justice.gov/report?utm_campaign=c49b0f71-deb0-482c-87b4-b56304a14c81&utm_source=justice.gov&utm_content=scra

https://civilrights.justice.gov/report?utm_campaign=c49b0f71-deb0-482c-87b4-b56304a14c81&utm_source=justice.gov&utm_content=civilrights

Happy to explain in more detail if needed - in general, [this is a good overview of supported utm fields](https://medium.com/@AsiDayan/a-beginners-guide-to-tracking-with-utm-parameters-e1e6f5be5a65) - we support `utm_campaign`, `utm_content`, `utm_source`, `utm_medium`, and `utm_term`.

**Comment by okkays** [comment]
@blaughman To summarize:

We're hoping to update two links on https://www.justice.gov/servicemembers/how-we-can-help#complaint

Note that one parameter of each link is different -

We'd like to change the "Submit a Complaint" link under the "How to file an SCRA complaint with the Department of Justice" header to https://civilrights.justice.gov/report?utm_campaign=c49b0f71-deb0-482c-87b4-b56304a14c81&utm_source=justice.gov&utm_content=scra

<img width="921" alt="image" src="https://user-images.githubusercontent.com/15126660/213768733-cbf112bf-5208-402d-8f96-50d7017adf13.png">

And we're hoping to update the "Department's Civil Rights Division Reporting Portal" link under the "How to report a civil rights violation to the Department of Justice" header with: https://civilrights.justice.gov/report?utm_campaign=c49b0f71-deb0-482c-87b4-b56304a14c81&utm_source=justice.gov&utm_content=civilrights

<img width="923" alt="image" src="https://user-images.githubusercontent.com/15126660/213769316-13e8331c-3567-4dcb-b030-0c713c2e5564.png">
