### ISSUE TITLE
Meet w/ Anthony to discuss clean data

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1449]

**Comment by randyabramson** [comment]
**Agenda**
•	What ‘clean data’ would look like
o	Remove 100% matches?
o	Remove repeat writers?
o	Reports that got specific form letters?
•	Pick a section to work with on ‘data model’

**Comment by blaughman** [comment]
Closing this card.  First efforts are to label constant writers and visualize them on the view all table and complaint detail page.  We also will tally matching reports on the complaint detail page.  Other requests from Anthony will be considered as time allows.
