### ISSUE TITLE
Feature prioritization for Repeat reports

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1450]
## User story:
As a Product Owner, I want the intake specialists to choose a design so that our engineers can develop the features.

## Objective:
Less iteration on the finished product

## Key result:
Increase in efficiency, team morale

## Ticket background:
Now that we have wireframes for repeat writer / matching reports, we want the intake specialists to drive our development.  Once the decisions are made at the Deep Dive meeting, we can make subsequent development cards for the features.

**Comment by nguyen-tina** [comment]
Showcase Exploration 1 and 2 at Deep Dive

**Comment by blaughman** [comment]
Voting feedback:
1.	Feature 2
2.	Feature 5
3.	Feature 1 
4.	Feature 4
5.	Feature 3
I’m rating the features based on how they would be implemented if they were added today.  

To clarify, I think Feature 5 would benefit VOTs work most ultimately, but likely would benefit us most after it is built out to include keywords, so I didn’t rank it #1.  For example, we are in the middle of a redistricting cycle and it would be good to be able to group those reports together.  The only time we’ve seen a 100% match is if people are asked to contact DOJ and given talking points which they copy and paste from the prepared comment.  Also, there are several different ways people will refer to the process: districting, redistricting, apportionment, reapportionment etc., and we will see other common related words (precincts, wards, districts, lines, boundaries, etc.).

Feature 2-- I like the look of including the reporter description with the Reported Complaint box (as long as the reporter description still cannot be edited).  

Feature 1- Even though we have an auto-reply on our section’s inbox directing people to the portal, we still process the emails that come in.  Sometimes staff will copy and paste the text in the body of the email into the reporter description box and the email sender may get around to submitting directly to the portal a few days later, which creates a duplicate.  It would be good to see that indication.    

Features 3 and 4 are not as useful to VOT since we do not send letters or review any letters that have been sent by other sections.

**Comment by blaughman** [comment]
DRS feedback:
The only feature that particularly interests me, personally, is Feature 3, though I’d also like to know if we sent an NC letter, not just a CW letter.

**Comment by blaughman** [comment]
ADM staff member feedback:
Good afternoon,

Feature 3
Feature 4
Feature 1
Feature 2
Feature 5

**Comment by blaughman** [comment]
More DRS feedback:
1.	Feature 3 (this would helpful if it shows the latest letter that we sent out, not just Constant Writer :-)
2.	Feature 1
3.	Feature 5
4.	Feature 4
5.	Feature 2

**Comment by nguyen-tina** [comment]
![Options](https://user-images.githubusercontent.com/17328158/214140858-2e787bbc-5ebe-4a3b-8cb6-b70bbc94bb6a.png)
Adding Feature options here for quick reference

**Comment by blaughman** [comment]
SPL feedback:

1.	Feature 5
2.	Feature 3
3.	Feature 1
4.	Feature 2
5.	Feature 4

**Comment by kewitham** [comment]
The following is my ranking of the features for prioritization with notes:
5 & 1 - It seems like these two go hand in hand so I grouped them together. I think these would improve efficiency the most.
3 - Another efficiency improvement
4 - Not sure how we are ranking these?
2 - It seems like this feature could create confusion about what is editable?

**Comment by randyabramson** [comment]
I like feature 1 the most, mainly becasue I think it will be a very easy win. Quick question there...is there a new filter (drop down, radio button, etc.) for 100% match on the view all table? I can't see it in the mock.

Feature 5 looks great...I just want to think through how filters reset currently and understand how that migth impact this new design. For example, when you change sections, all filters are reset. 

3 and 4 look great as well...I would like to really understand if these features would be useed widely and if we could 'ballpark' efficiencies gained.

**Comment by blaughman** [comment]
I'm a fan of 3.  I think there are many frequent flyers out there that haven't been sent the constant writer form letter.  This would add transparency to which haven't gotten the letter and allow staff to correct the mistake.  After correction, we will more easily identify the noise and partition it off from the meaningful reports.

**Comment by nguyen-tina** [comment]
Hello!

Based on the feedback gathered above, it seems that this is how we should begin:

1. Icons for the listing page, connoting when a Constant Writer letter has been sent
2. Grouped view, allowing users to group the listings page by a select few categories (TBD)
3. Link in detail page, allowing users to find other reports with matching descriptions "filtered" on the listings page

These remaining features seemed to receive mixed reception
4. Combining the Personal Description in the detail page, simplying the elements on the detail page
5. Changing the report numbers to a rating – this seems low priority and possibly unwanted. Development here will have to be driven by desire for improved performance. 

See this chart for a summary of the rankings of comments

![RR – Feature prioritization](https://user-images.githubusercontent.com/17328158/215588563-258826f0-4b9a-46bc-8533-b5155c885d54.jpg)
