### ISSUE TITLE
Decouple hard coding from the DRS referral letters

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1452]
## User story:
As a CRT user, I want all sections to be able to use the referral letters so that they can process reports

## Objective:
Provide more tools to intake specialists

## Key result:
Faster turnaround times for reports that belong to another agency

## Ticket background:
When the DRS referral letters were added, the from line was hard coded where only DRS could use those letters.  Other sections need to send some reports to those agencies as well,  By removing the hard coding and replacing the letters to function like other letters, we can expand the available tools for all sections.

## Acceptance criteria:
1) Given I am on the complaint detail page
when I select 'contact complainant'
then I see a modal with the menu of available form letters and languages

2) Given I am on the 'contact complainant' modal
when I select any of the 4 DRS referral letters
then the re: line reflects the section the report is assigned to.

## Technical Notes
- The name of the four referral letters should now be:

1.  CRT - Dept of Ed Referral Form Letter
2. CRT - DOT Referral Form Letter
3. CRT - EEOC Referral Form Letter
4. CRT - HHS Referral From Letter

**Comment by kewitham** [comment]
@blaughman I don't think I have access to add cards to the project - could you add me? I'd like to add the follow up response template deletion task.

**Comment by blaughman** [comment]
The sections are appearing as requested in Dev.  Moving to UAT complete.

**Comment by blaughman** [comment]
Letters appear and function as intended in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Letters function and appear as intended in Production.  Closing this card.
