### ISSUE TITLE
UTM data is removed if any field is edited on a report

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1457]
## Summary
The UTM data for a report is reset to 'none' if any field is edited on a report.  This makes the report non-responsive to a query looking for reports related to that particular campaign.

## Detail
We noticed on report 249366-RTJ that it was no longer associated with the SVI filter.  It appears that an edit in the 'reported complaint' card are removing the UTM data from the record.  Edits in the Actions card and Correspondent Information card are not resetting the UTM data.  This impacts our ability to locate reports and perform analytics.

### Steps To Reproduce

1. Filter for reports associated with a campaign
2. Edit a field in the reported complaint card
3. Check activity log to see if UTM data was set to none

If it's relevant, add browser or operating system where the error occurs.
This is happening on both Chrome and Edge

### Expected Behavior

The UTM data should remain hidden on the detail page.  The UTM data should also remain unchanged if any value is changed in the reported complaint card.

### Actual Behavior

Any changes within the reported complaint card are resetting the UTM information from the associated campaign to none.  Updates to the Actions card and Correspondent information card are not recreating this behavior.

## Suggested Actions

This issue only appears for edits in the reported complaint card on the detail page.

## Acceptance Criteria

1) Given I am on a report detail page associated with a special campaign
when I edit a field on the reported complaint card
then the UTM data is not reset and remains hidden in the background.

## Technical notes/questions

I tested bulk actions to see if I could reproduce this behavior.  Although 'CRT summary' writes to the 'summary' field in the reported complaint card on the detail page, adding a summary from the bulk actions menu did NOT remove the UTM data.

**Comment by okkays** [comment]
I'm able to reproduce by editing the "Reported complaint" section.

Changing other sections doesn't trigger the issue. I should be able to work out a fix from this.

![before](https://user-images.githubusercontent.com/15126660/214912579-df0b0515-ca1f-4730-bdc3-4a6ee7dbe0cd.gif)

**Comment by okkays** [comment]
Found a fix. Also updating some documentation so this hopefully isn't a problem in the future.

https://github.com/usdoj-crt/crt-portal/pull/1310

**Comment by blaughman** [comment]
Update tested in Dev and campaign is not removed when editing the reported complaint card.

**Comment by blaughman** [comment]
Update tested in Staging and campaign is not removed when editing the reported complaint card.  Ready for Production.

**Comment by blaughman** [comment]
Campaign now persists after an edit.  Closing this card.
