### ISSUE TITLE
Add constant writer icon to view all table (Design + Dev)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1461]
## User story:
As a CRT user, I want a visual indicator for complainants that have received a constant writer form letter so that I can prioritize incoming reports.

## Objective:
Increase transparency/efficiency for incoming reports

## Key result:
Visualization for reports that could/should be processed first

## Ticket background:
CRT users only have the Total Complaints card (or accessing individual reports) to know when a complainant has been sent a constant writer form letter. The constant writers are low priority when processing new, incoming reports. 

## Acceptance criteria:
1) Given I am on the view all table
when a new, incoming report from a complaint (that has previously received a constant writer form letter) is received
then I see an icon designating that complainant as a constant writer next to the 'Total #' value

## Mockup:
<img width="173" alt="image" src="https://user-images.githubusercontent.com/52507395/215827118-cd947d20-f386-4ecb-909c-516c66f6e921.png">

## Technical notes/questions:
- We will focus on the view all table for this card - the complaint detail page will come later if we are successful

**Comment by randyabramson** [comment]
@blaughman  - please forward the policy for sending the CW note out to Anthony and confirm that we are all now tracking off of the same definition.

**Comment by blaughman** [comment]
@nguyen-tina This looks great.

**Comment by blaughman** [comment]
Feature functions as expected in Dev.  Moving to UAT complete.

**Comment by blaughman** [comment]
Feature functions as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Feature is functioning as expected in Production.  Closing this card.
