### ISSUE TITLE
Add 100% matching tally on complaint detail page (Design + Dev)

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#1462]
## User story:
As a CRT user, I want to know when an incoming personal description exactly matches another incoming personal description in the system.

## Objective:
Increase transparency for incoming reports

## Key result:
More efficient processing on the back end

## Ticket background:
There are thousands of reports in the system that match completely.  This feature will address those reports.  These reports are, at this time, of little value to the intake staff and prevent them from processing potentially more actionable reports.  This feature will also allow us to identify letter writing campaigns related to trending topics.

## Acceptance criteria:
1) Given I am on the complaint detail page
when I look at the personal description field
then I see a notation, with a tally, if the report completely matches others in the system

2) Given I am on the complaint detail page
when I click the link for matching reports
then I am taken to a filtered view all table showing all reports with the matching description
AND
the matching description is captured in the 'personal description' filter

## Technical notes/questions:
- This feature will operate like our email count (run at off hours, count will be accurate the following business day)
- This MVP will lead to efforts to identify 90%, 80%, etc. matches

**Comment by okkays** [comment]
[PR is up](https://github.com/usdoj-crt/crt-portal/pull/1316) - I've done this in a partially asynchronous way:
1. Page loads, with the "View all matching descriptions" link.
2. (User can use the page and click the link).
3. In the background, we ask for the count of matching descriptions.
4. If that query works, we display the count next to the link.
    - If the query fails, you just won't see the count - you can still click the link to go to the list page.

@blaughman a couple of test cases for dev, once this is merged:
- [ ] That the count appears on records with lots (thousands) of descriptions
- [ ] That it works with super large descriptions (I've tested this on local)

**Comment by nguyen-tina** [comment]
@blaughman Please review the 2/2/23 proposed design for this work. Note the language change: "View X reports matching this description" -- we believe this language is more clear for users.
![Detail Page Complaint Tally](https://user-images.githubusercontent.com/17328158/216425026-86e7208b-5889-4274-8ad1-2aebeb804727.jpg)

**Comment by blaughman** [comment]
@nguyen-tina @ilodidoj @okkays @kewitham @randyabramson This looks good to me.  Dev team - please let us know if there are any concerns with implementing this design.

**Comment by okkays** [comment]
LGTM - I can make a quick change to the PR to match the new wording.

**Comment by okkays** [comment]
Wording updated on the PR!

![new wording](https://user-images.githubusercontent.com/15126660/216458547-7239cfa1-f8d4-48ed-a1fd-c30b2c820ca9.gif)

**Comment by blaughman** [comment]
@okkays **Report 1379-ZJC** is working as intended (This is a longer description that will check to see if the system can identify reports that exactly match this exact wording).  **Report 1368-JFH** also works as intended "Test Report Submission". The personal description in **Report 1374-GHL** seems to be capturing a lot of non-matching results (this is a test).

cc: @ilodidoj @kewitham

**Comment by okkays** [comment]
@blaughman

I have a proposed solution to this, which involves adding a way to say, "I want an exact, full match". The syntax (of `^my search$`) is a bit of a technical standard - it's the best I could think of given that `"` is taken.

See: https://github.com/usdoj-crt/crt-portal/pull/1322

**Comment by blaughman** [comment]
@randyabramson Should we remove case sensitivity for this feature? I have two records in Dev with the text "This is not a test" and "this is not a test"  As it stands, this is capturing them as non-matching reports.  Thoughts?

**Comment by randyabramson** [comment]
I'd vote to remove case sensitivity. Good catch @blaughman.

**Comment by blaughman** [comment]
@okkays Any chance we can remove case sensitivity for this feature?  Please see my comment above.

**Comment by okkays** [comment]
@blaughman @randyabramson I feel like case sensitivity here is important - we only want descriptions that are exactly the same as the specified one. Plus, there's some technical hoops to jump through to remove it efficiently.

Plus, technically, it's tricky because the database has everything indexed based on case. It'll have to look at every report in the database, or we'll have to add an additional index, to do a case-insensitive match.

This might be something to revisit when we look at how to do 80% similar reports (versus exact match)

**Comment by blaughman** [comment]
With the feedback above, this is functioning as the card intended.  Moving to UAT complete.

**Comment by blaughman** [comment]
Feature is functioning as expected in Staging.  Ready for Production.

**Comment by blaughman** [comment]
Feature functions as expected in Production.  Closing this card.
