### ISSUE TITLE
CRT side - Login title running into header

### ISSUE THREAD

**Issue by Jacklynn** [usdoj-crt/crt-portal-management#352]
On the login screen it looks like the top margin is missing and the text is overlapping with the header.

![Screen Shot 2020-03-10 at 10.44.53 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e2143c4a-bf9b-4cf0-ab3c-3a67c9285419)
![Screen Shot 2020-03-10 at 10.45.01 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/ec23d510-4720-4692-98f8-64f8cf697052)

**Comment by LindsayYoung** [comment]
This page won't be on production
