### ISSUE TITLE
[View all table] tighten spacing in the pre-header area

### ISSUE THREAD

**Issue by Jacklynn** [usdoj-crt/crt-portal-management#391]
## Problem
Thee space before the table feels a little loose now that it's implemented, want to tighten up the spacing.

### Current
![Screen Shot 2020-03-23 at 4.47.17 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/f7d8482f-cf9d-4f90-9ee5-c5b5111727aa)

### Expected
**With filters**
![Open area spacing.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/9f5ce900-6ac4-49c4-9663-bc319874eec0)

**Without filters**
![Open area spacing.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/47d900c7-d7af-4653-af59-135b5468631c)

## Annotations
![Open area spacing.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c1670275-fd8f-4a4b-be02-7118b8227460)

**Comment by AvivaOskow** [comment]
@Jacklynn is this still on the table or did it get resolved?
