### ISSUE TITLE
[a11y] "No results" status message 

### ISSUE THREAD

**Issue by LindsayYoung** [usdoj-crt/crt-portal-management#439]
When the view all filter returns no results we want to mark no results as a status message.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_status_role

**Comment by Jacklynn** [comment]
I'm not able to trigger this

**Comment by LindsayYoung** [comment]
I can see the status role is being applied, it isn't reading in in VO, so I think we have to filter back to Terri on this one too

**Comment by LindsayYoung** [comment]
This is added as a status, but the status doesn't get read. 

My best idea at the moment is to add this to the page title- (the title that shows up in the browser tab). 

@Jacklynn what is your preference I think our options are:
 - add a message only when there are no results
 - always have the count in the title
 - ask Terri at our next session

**Comment by LindsayYoung** [comment]
check status

**Comment by blaughman** [comment]
Function works as intended in Prod.  Closing.
