### ISSUE TITLE
Making the phone field easier to fill out for public users and CRT users

### ISSUE THREAD

**Issue by Jacklynn** [usdoj-crt/crt-portal-management#459]
Feedback from HCE soft launch they weren't able to add an extension to someone's contact. they left it as a comment but would be helpful to add up front. 

Q: ability to add in the public too? or just CRT view?

**Comment by Jacklynn** [comment]
Talked to @LindsayYoung about this today, and there's a django form field that's more flexible and could help format and handle extensions better. Considering we're going to do phone intake soon this might come up more.
cc/ @blaughman @lalitha-jonnalagadda

**Comment by blaughman** [comment]
Closing this card.  Superseded by #1353
