### ISSUE TITLE
Import data from 'Classification' system to CRT portal

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [usdoj-crt/crt-portal-management#474]
So far it seems the data migration will be straight forward. We would want to dump the data as a csv and then run an import script. 

Here is the data mapping proposal:
https://docs.google.com/spreadsheets/d/1U4BcpnWkcJHdhw5CH-vUcUJ5KRZXEorCiTuj7Zylvzs/edit#gid=0

I would like to confirm with @ilodidoj that I am not missing anything. 

@blaughman  - This card is for the data migration work in the future

**Comment by blaughman** [comment]
Per Lindsay, this is not needed.  Closing this card.
