### ISSUE TITLE
[user research] review page: consider removing first "submit concern" button on  and "concern" language

### ISSUE THREAD

**Issue by Jacklynn** [usdoj-crt/crt-portal-management#482]
## background
If we want people to review their submission, we can take a firmer stance here and only have it on the bottom. Two users hesitated on it for a moment (this could also be the language) and two others suggested it only be in the bottom.

One user was confused on the language for a moment. He indicated that either "submit concern" language didn't make sense to him but for a moment he thought he was supposed to give feedback on the page, like enter new feedback. 

Button: 
![Screen Shot 2020-05-06 at 5.40.33 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e747e6e3-3a9e-4147-8b84-df6aab5dfec4)

## Proposed
Maybe the language can change to:

`page title` Review your **responses**
`question label` Before you submit your report, please check your responses
`help` If you need to make any changes, you can go back and edit the previous pages. Please make sure your information is accurate. This allows us to respond to your report quickly.
`button -- if keeping button` Submit **report**

**Comment by Jacklynn** [comment]
## background
If we want people to review their submission, we can take a firmer stance here and only have it on the bottom. Two users hesitated on it for a moment (this could also be the language) and two others suggested it only be in the bottom.

Button: 
![Screen Shot 2020-05-06 at 5.40.33 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e747e6e3-3a9e-4147-8b84-df6aab5dfec4)

## Proposed
Maybe the language can change to:
Review your **responses**
Before you submit your report, please check your responses
If you need to make any changes, you can go back and edit the previous pages. Please make sure your information is accurate. This allows us to respond to your report quickly.
Submit **report**

**Comment by AvivaOskow** [comment]
+1 we've heard this several times!

**Comment by blaughman** [comment]
Language was changed.
