### ISSUE TITLE
[landing page] have Menu break occur sooner / protect DOJ logo space

### ISSUE THREAD

**Issue by Jacklynn** [usdoj-crt/crt-portal-management#591]
Problem: When I compress my screen screen the menu squishes the logo
![Screen Shot 2020-06-11 at 3.32.54 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/0f30ed1a-4832-4971-87d8-d9eb64719a84)

Proposed: The space the logo takes up should be protected, if the menu runs into it then it should turn into the "menu" button sooner.
![Screen Shot 2020-06-11 at 3.34.34 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/b9f80f6a-450d-475f-b762-4e2c7ea84933)

**Comment by billyhunt** [comment]
@blaughman this can be closed.

**Comment by blaughman** [comment]
Per @billyhunt, closing this ticket.
