### ISSUE TITLE
Stand up DOJ instance of ZenHub 

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#652]
- [ ] Connect with Darren to see if we need ATO for ZenHub

- [ ] Explore API documentation for export of ZenHub cards https://help.zenhub.com/support/solutions/articles/43000480389-exporting-zenhub-data

- [ ] Export card data from 18F ZenHub

- [ ] Stand up DOJ instance of ZenHub

- [ ] Import 18F ZenHub cards into DOJ instance of ZenHub

**Comment by Jkrzy** [comment]
Any updates on this one? 

We'll need to migrate away from 18F's zenhub in the near term.

**Comment by randyabramson** [comment]
Hi @Jkrzy  -- In talking with @lalitha-jonnalagadda, we have until November to stay on the instance of Zenhub. I had a conversation with our IT team about moving to AIRTABLE. They are in the process of getting that license. I have reminders on my calendar to keep checking in about this.
