### ISSUE TITLE
18F team offboarding 8/30

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [usdoj-crt/crt-portal-management#658]
##### Mural
- [ ] Create PDF's and drop them in the google drive
- [ ] 

#### Calendars
- [ ] Zoomgov
- [ ] Shared Cal
- [ ] Invites

#### Access

- [ ] CRT repo
- [ ] 18F repo
- [ ]

**Comment by LindsayYoung** [comment]
this is a duplicate
