### ISSUE TITLE
Regular research/contacting Samsung 

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#827]
Regular research/contacting Samsung about error. Time boxed at 20 minutes per sprint. @randy and @blaughman  can assist as well

Per @cantsin: 

Jumping in here. Regards 1, I looked through the Samsung Internet support forum but did not find anything conclusive (to be fair, there's not much activity). There's also a deprecated github repository which is also of no help. Since Samsung Internet Explorer is a lesser known (and Chromium-derived) browser variant, I don't think we can expect much from them. For the record, I can't reproduce on Chromium (which is distinct from Chrome stable). So it's something Samsung is doing for whatever reason.

**Comment by LindsayYoung** [comment]
I would recommend closing this and if it comes back up, open it or create a new ticket.

**Comment by blaughman** [comment]
Other information located in card 823 in Zenhub.

**Comment by billyhunt** [comment]
We have discovered that the Samsung Browser is periodically resetting the connection during the reporting process.  There is not much we can do about it currently, as if the connection is reset, we have no idea where the user is in the reporting process.  My recommendation is to keep everything as is.  If we decide we really want to fix this, we could use a new technology like a single page app frontend for the reporting process.  It would fix the problem, but that is a very heavy lift, and not recommended at this time.

CC @randyabramson @blaughman @ilodidoj @chinelo-ikejimba
