### ISSUE TITLE
Implement single sign on in staging environment

### ISSUE THREAD

**Issue by Jkrzy** [usdoj-crt/crt-portal-management#835]
Building on [#788](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/788), as a developer I want the authentication process on staging to mirror production so that we can test more effectively.

PR: https://github.com/usdoj-crt/crt-portal/pull/902

### We'll know we're done when
- [x] The staging instance is configured to use single sign-on for authentication

**Comment by randyabramson** [comment]
@ilodidoj assuming that since I didn't have to sign on to Staging that this is now implemented? Let me know if there is another test I should be working on.

**Comment by randyabramson** [comment]
When I hit the staging URL, I no longer need to log in. Working as intended. Closing.
