### ISSUE TITLE
Configure auto-reply on Amazon SES for complainants who reply to a trending form letter

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#869]
Configure auto-reply on Amazon SES for complainants who reply to a trending form letter.

Note that @AvivaOskow will work up a HTML mock for this, but simple text is as follows:

=====

Thank you for contacting the Civil Rights Division.

Please visit our Civil Rights Report site at https://civilrights.justice.gov/ to submit a report and learn about your rights. If you’ve already submitted a report, visit https://civilrights.justice.gov/#already-submitted.

U.S. Department of Justice
Civil Rights Division
950 Pennsylvania Avenue, NW
Washington, D.C. 20530-0001

(202) 514-3847

**Comment by Jkrzy** [comment]
We're unable to handle inbound emails from Amazon SES. We'll need to tackle this at whichever email address, if any, is used for `Reply-To`

**Comment by LindsayYoung** [comment]
Is this still relevant or should it be closed?
