### ISSUE TITLE
Nudge user to provide contact info (email and/or phone)

### ISSUE THREAD

**Issue by emilycryan** [usdoj-crt/crt-portal-management#872]
Reporters who do not provide email or phone cannot be contacted for any followup. While intake specialists can sometimes find ways to contact complainants, a simple nudge may encourage users to provide this information. 

NOTE: The proposed solutions only highlight the prompt. We can also consider adding in email or phone validation to ensure users provide a valid email or phone. 

**Email prompt, Version 1**:
https://gsa.invisionapp.com/share/67ZRBQEDJWF
(Actual screen / popup: https://gsa.invisionapp.com/share/67ZRBQEDJWF#/screens/440771703)

**Email prompt, Version 2**:
https://gsa.invisionapp.com/share/D9ZRD8Y24WK
(Actual screen / popup: https://gsa.invisionapp.com/share/D9ZRD8Y24WK#/screens/440802719)

In both cases above, the user is only prompted once and if they choose not to provide the information, they will be routed to the next step in the flow. 

Users will also only see this prompt once and if they choose to provide the information, the screen should scroll back up to the email field, highlight the field and place the user's cursor into the form field. We cannot know if the user would prefer to provide phone in lieu of email so we will guide them to the first field, email, and if they choose to ignore this field and instead provide phone, they are already in the area of the page that houses both so they will need to manually move to the phone field if they prefer proving that over email.

**Comment by randyabramson** [comment]
I really like this! I like the pop up a bit more, but I'm wondering if pop up blockers would prevent this from showing? (I know this is more of a modal than a  traditional pop up, but asking anyway.)

Should we change the language to 'You are submitting without email, phone or incomplete address information?'

**Comment by emilycryan** [comment]
@randyabramson I only flagged on email and/or phone. It's going to get really complicated if we attempt to force them to provide all of an address. What if they don't know it all? It seems easier to ask only for phone or email. I'm also not sure how a full mailing address would make it easier to contact someone if you still didn't have a phone or email...? Would we expect sections to send US mail letters?

For this first pass, we may want to stick with email and phone only - it's also easier to validate on proper formatting for those. 

CC @blaughman @AvivaOskow

**Comment by randyabramson** [comment]
@emilycryan - I'm thinking of prisoners who might not have phone/email but might know the address of the prison?

**Comment by randyabramson** [comment]
@emilycryan - I think your idea of just focusing on Email/Phone for round 1 is a good idea. Moving this up for Sprint 39.

**Comment by randyabramson** [comment]
Text being submitted for translation:

You are continuing your complaint without providing email or phone information.

You do not have to provide contact information, however, we will not be able to contact you for any status updates or potential follow up. Would you like to add your contact information now? If you prefer not to, you will go to Step 2.

No, I do not want to provide it
Yes, I'd like to add it

**Comment by LindsayYoung** [comment]
FYI: we already have email and phone validation

**Comment by randyabramson** [comment]
@LindsayYoung by 'email and phone validation' you mean that those elements need to be entered in the correct format, correct? If so, this ticket tackles a different issue.

**Comment by randyabramson** [comment]
Final Spanish translation from Marta attached here
[Spanish - translation - FINAL - from - Marta - 2021 06 14.docx](https://github.com/usdoj-crt/crt-portal-management/files/6669424/Spanish.-.translation.-.FINAL.-.from.-.Marta.-.2021.06.14.docx)

**Comment by randyabramson** [comment]
Randy sent out vendor drafts to FBI on 6/17

**Comment by LindsayYoung** [comment]
@randyabramson the ticket says " We can also consider adding in email or phone validation to ensure users provide a valid email or phone." I rang in to say that we already have validation for those fields.

**Comment by randyabramson** [comment]
Translations sent to FBI for confirmation. Expected back on 6/28

**Comment by randyabramson** [comment]
@blaughman  @emilycryan  I have all of the translations for this card. I am going to close this and open a new card with the ACs and translation requirements.
