### ISSUE TITLE
Printing a Form Letter Response w/ Letterhead

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#886]
## Narrative
As a CRT user, I want to print form letter responses on letterhead so that I can respond to complainants without an email address.

## Background
CRT users are still using legacy systems to respond to snail mail because the portal does not provide a viable alternative.  Now that attachments are nearly ready for production, the form letters need letterhead to add validation to the response.  CRT users expressed serious concern about sending form letters without letterhead.

## Acceptance Criteria
1) Given I am on the complaint detail page
when select 'Contact Complainant' 
then I see the form letter menu appear

2) Given I am on the form letter menu
when I select a form letter response
AND
I select 'Print'
then the form letter is generated with a DOJ letterhead at the top of the response

## Assumptions
- Letterhead would only be needed when a user clicks 'Print'
- The response will need the complainants full mailing address and the date the letter is printed.
- Response date will be vertically aligned under the 'Washington, DC' text in the letterhead.
- Response text WILL NOT include the Response line text that is included for email responses.
- A valid email address in the 'Correspondent information' card is the preferred method of contact.

## Technical Questions
- Should send button remain gray and unable for selection if no email is in the contact information?
- Anonymous or illegible name?  No name in mailing address, Dear Friend salutation?

## Mockup
[https://app.zenhub.com/files/183258764/39efa2a3-f58a-491d-9ca7-2baaa4b3bb04/download](https://app.zenhub.com/files/183258764/39efa2a3-f58a-491d-9ca7-2baaa4b3bb04/download)

**Comment by timoballard** [comment]
@blaughman - does the text in the letterhead ("U.S. Department of Justice", "Civil Rights Division") get translated, or is it always English?

**Comment by blaughman** [comment]
@timoballard Great question.  I'll check with the LWG about this.

**Comment by timoballard** [comment]
@blaughman -- Does the contact info need to be at a precise location to accommodate window envelopes? If so, do you have the specifications?

**Comment by blaughman** [comment]
@timoballard We haven't had anyone in the office, but I think we should be fine if we have the name and physical address spaced 2.5 inches from the top of the document.  The bottom of the address (below city, state, zip) would hopefully be no lower than 3.5 inches from the top of the document.  Hope this helps.

**Comment by blaughman** [comment]
@timoballard @ilodidoj the envelopes are 4 inches by 10.75 inches.

**Comment by blaughman** [comment]
@timoballard Here you go:![DOJ Envelope - Left Indent.jpg](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/2c5b1474-6c78-437c-8f32-07a27029b3d5)

**Comment by blaughman** [comment]
@timoballard ![DOJ Envelope - Top and Bottom Indents.jpg](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/e597dbe9-d566-4e86-9bb9-a3dd15d6267e)

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by randyabramson** [comment]
Works as intended on LIVE

**Comment by blaughman** [comment]
This has been implemented.  Closing this card.
