### ISSUE TITLE
Form letter selection functions - New Languages

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#911]
## Narrative
As a CRT user, I want form letters separated by language so that I can efficiently select an appropriate response.

### Background
We currently have 14 form letters, all of them being available in English and Spanish.  The current selector function lists all of the form letters in a dropdown list, which is already a very long. As we add more languages, it is clear that we need a new interface that will allow intake specialists to filter on the language first and then select the form letter template. (see mock below)

### Assumptions
1. The default selection for the language dropdown is English since nearly 100% of the incoming complaints are in English.
2. If the CRT user is selecting a language other than English, then the CRT user MUST make a selection from the language drop down BEFORE they can see the list of form letters available
2. The language dropdown populates the relevant form letters in the template drop down
3. Only the 'COPY' and 'PRINT' functions will be operational on the bottom row of buttons. 'SEND' will become functional when we have Email integration.
4. Maintain behavior of current product where 'copy', 'print' and 'send' buttons are greyed out until form letter is selected

### Acceptance criteria
1) Given that I am on an individual record
When I click the contact complainant button
I see a modal pop up that shows the complainant name (if available), Email (if available), Subject (to be populated after template selection), a language drop down, a template drop down (greyed out/not active), a greyed out field, and the 'copy', 'send', 'print' and 'cancel' buttons

2) Given that when I see the contact complainant modal
When I see the 'language' dropdown
then I see 'English' is the default selection
AND
I am able to click a dropdown menu with the following selections:

简体字 (Chinese Simplified)
簡體字 Chinese Traditional)
English
Español (Spanish)
한국어 (Korean)
Tagalog
Tiếng Việt (Vietnamese)

3) Given that when I see the language list
When I select a language 
The selected language is shown in the language dropdown AND the template list is populated with the corresponding translated form letters AND the template list becomes active

4) Given that when I see the template list
When I select a template 
The selected template is shown in the template list dropdown AND the template list is populated in the empty field

5) Given I am in the template selection menu
when I select a form letter response
then I see the response generated with metadata from the complaint

5) Given I am on an individual record
when I select a language that is NOT English
then a cookie is dropped to that I will see that language as my default language moving forward

![form letter selector.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/70c9b345-515d-43e7-85a6-4ca7c58dd75b)

**Comment by randyabramson** [comment]
@timoballard @ilodidoj @blaughman 

copy/send/print buttons are nearly off screen at certain resolutions. We need to fix this in Sprint 46.

![stage-copy-send.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/0b99170e-3222-4602-9269-961b4c986248)

**Comment by randyabramson** [comment]
Disregard above - fixed on staging (I forgot to refresh)

**Comment by randyabramson** [comment]
Works on live desktop

**Comment by LindsayYoung** [comment]
This issue didn't close but it is in the done column. Closing now
