### ISSUE TITLE
Asian Translations - Fine Tuning Card

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#932]

**Comment by randyabramson** [comment]
- [ ] Go Button – bug on github https://github.com/usdoj-crt/crt-portal/pull/853
- [ ] All languages in header and drop down
- [ ] No translation for ‘print report’ at the moment
- [ ] Alignment on GO button is off on Vietnamese
- [ ] Alignment on CITY/STATE is off on Vietnamese
- [ ] “more accessibility language services” vs. “Availability of Language Assistance Services” in mobile drop down

**Comment by randyabramson** [comment]
Accessibility link from Marta. @timoballard we can go with 

Alternatives:
More language services
Más servicios lingüísticos


For now. We should adjust this for other languages down the road.

===

Your text:
More accessibility language services
Más servicios lingüísticos accesibles

Alternatives:
More language services
Más servicios lingüísticos

Additional languages available
Idiomas adicionales disponibles

**Comment by randyabramson** [comment]
Instructions for translating Touchpoints tab and form (for later sprint):

Translations are accomplished by copying the form and translating the text manually.

Then, in your website, different versions can be presented to a user based on the how it handles ?locales.

Happy to chat about your specific needs. This can be a bit tricky, but we do have a few spanish and mandarin forms floating around.

cc: @blaughman @timoballard @ilodidoj @Jkrzy

**Comment by randyabramson** [comment]
@timoballard, I see that @blaughman added this branching question for Vietnamese:
-	Discrimination in an Educational Setting

Do we need this translation for other languages as well?

**Comment by randyabramson** [comment]
Some postmortem thoughts:

1. Moving forward, do we have to use vendor if FBI is going to verify anyway? Even for 1 word or sentence?
2. Are we ok with publishing changes to English first and doing translations later?
3. What does testing look like in all languages? How can Playwrite automation help?
4. We should talk about communications - Monica wanted to be cc'd on content updates
5. Monica should be part of postmortem
6. Surprised to learn that Linguists are not the final authority at FBI; learn more about ORF process

**Comment by Jkrzy** [comment]
TO add here:

- [ ] Styling for `Go` button in footer for Tagalog.

![Screen Shot 2021-04-28 at 4.50.55 PM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/e39ec11c-35ac-4601-bb40-83ee195b3a78)

cc: @timoballard

**Comment by randyabramson** [comment]
thanks for catching that @Jkrzy

**Comment by randyabramson** [comment]
Randy intake testing DEV:

- [ ] Chinese Traditional
- [ ] Chinese Simplified
- [ ] Korean
- [ ] Vietnamese
- [ ] Tagalog

**Comment by randyabramson** [comment]
Randy intake and PDF testing on STAGING:

- [ ]  Chinese Traditional
- [ ]  Chinese Simplified
- [ ]  Korean
- [ ]  Vietnamese
- [ ]  Tagalog

* Something to check for staging/PROD - after form is submitted, I got an error when I tried to switch languages on top

**Comment by randyabramson** [comment]
Staging branching questions

- [ ]  English
- [ ]  Spanish
- [ ]  Chinese Traditional
- [ ]  Chinese Simplified
- [ ]  Korean
- [ ]  Vietnamese
- [ ]  Tagalog

**Comment by randyabramson** [comment]
Staging Homepage buttons/Links/language selector

- [ ]  English
- [ ]  Spanish
- [ ]  Chinese Traditional
- [ ]  Chinese Simplified
- [ ]  Korean
- [ ]  Vietnamese
- [ ]  Tagalog

**Comment by blaughman** [comment]
@randyabramson @timoballard I'm curious about the FOIA link in the footer for Simplified Chinese.  Should we include the <<>> ?
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/32468e5b-d515-4925-8ae3-446f3c9a5402)

**Comment by randyabramson** [comment]
@blaughman @timoballard 

I googled 《信息自由法》 and it looks like that translation is actually correct

![foia.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/78455cd8-5015-4798-9d96-148acb37cb8e)

**Comment by randyabramson** [comment]
Staging - Privacy page and Error pages

- [x]  English
- [ ]  Spanish
- [ ]  Chinese Traditional
- [ ]  Chinese Simplified
- [ ]  Korean
- [ ]  Vietnamese
- [ ]  Tagalog

**Comment by randyabramson** [comment]
For reference - here's the pull request that Joe shared for the Vietnamese font issue fix
https://github.com/usdoj-crt/crt-portal/pull/874

**Comment by timoballard** [comment]
Marked the "Go" button styling for Tagalog as complete -- Dianne provided an alternate translation (Oo, which translates literally to "Yes") which she thought was appropriate in this context, and which fits inside the button

**Comment by randyabramson** [comment]
Thanks @timoballard !

**Comment by randyabramson** [comment]
PROD 

FORM
- []  English
- []  Spanish
- []  Chinese Traditional
- []  Chinese Simplified
- []  Korean
- []  Vietnamese
- []  Tagalog

Branching Questions
- []  English
- []  Spanish
- []  Chinese Traditional
- []  Chinese Simplified
- []  Korean
- []  Vietnamese
- []  Tagalog

Homepage, Privacy Page, Error Pages

- []  English
- []  Spanish
- []  Chinese Traditional
- []  Chinese Simplified
- []  Korean
- []  Vietnamese
- []  Tagalog

**Comment by randyabramson** [comment]
@Jkrzy @timoballard @timoballard 

Very low priority. but when I have two tabs open in different languages, I get an error when going through the form on both tabs.

I know this is VERY EDGE...will add it to the checklist above.

**Comment by timoballard** [comment]
Added [945](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/945) to track Go button adjustment

**Comment by blaughman** [comment]
Per Emily, no need to translate the letterhead.

**Comment by randyabramson** [comment]
@blaughman there are very low priority items on this list. I am going to close this and add the items to our backlog
