### ISSUE TITLE
Line break style guide for Form Letters (Email integration)

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#934]
@Jkrzy @timoballard @ilodidoj @AvivaOskow @blaughman 

Including @emilycryan 'text only' mocks for form letters here.

I am not sure if bolding/underlining fall into the HTML category of letters, but I hope that these will at least help with where to place character returns.

[https://app.zenhub.com/files/183258764/204e48be-60c9-44d3-9adf-60983d536d11/download](https://app.zenhub.com/files/183258764/204e48be-60c9-44d3-9adf-60983d536d11/download)

[https://app.zenhub.com/files/183258764/4b2228fb-9436-4c45-95d5-39c2f9e110dc/download](https://app.zenhub.com/files/183258764/4b2228fb-9436-4c45-95d5-39c2f9e110dc/download)

[https://app.zenhub.com/files/183258764/d129a890-013b-4ad8-b44a-71e503cae46c/download](https://app.zenhub.com/files/183258764/d129a890-013b-4ad8-b44a-71e503cae46c/download)

[https://app.zenhub.com/files/183258764/48d20491-afba-4b50-8e9a-de194a96d451/download](https://app.zenhub.com/files/183258764/48d20491-afba-4b50-8e9a-de194a96d451/download)

[https://app.zenhub.com/files/183258764/7ef934dd-91dd-4172-98c6-67c296341f25/download](https://app.zenhub.com/files/183258764/7ef934dd-91dd-4172-98c6-67c296341f25/download)

[https://app.zenhub.com/files/183258764/78fa08d7-7506-4323-a5ef-a86e4b65abc2/download](https://app.zenhub.com/files/183258764/78fa08d7-7506-4323-a5ef-a86e4b65abc2/download)

[https://app.zenhub.com/files/183258764/8fcf461a-fcef-4256-8ef3-eba773344501/download](https://app.zenhub.com/files/183258764/8fcf461a-fcef-4256-8ef3-eba773344501/download)

[https://app.zenhub.com/files/183258764/c8a147fd-6678-47c2-b2f1-a0337a754995/download](https://app.zenhub.com/files/183258764/c8a147fd-6678-47c2-b2f1-a0337a754995/download)

[https://app.zenhub.com/files/183258764/118b86a9-dfa8-419f-bf44-6e9712b6cb39/download](https://app.zenhub.com/files/183258764/118b86a9-dfa8-419f-bf44-6e9712b6cb39/download)

**Comment by randyabramson** [comment]
@Jkrzy any status update on this card?

**Comment by blaughman** [comment]
@Jkrzy Were we able to make any progress on this request?  Please advise.  Thanks.

**Comment by ilodidoj** [comment]
@randyabramson I have not done any part of GovDelivery TMS yet, I will know more once have a chance to work on the email coding part.

**Comment by randyabramson** [comment]
@blaughman in my tests on DEV, the line breaks look good, so I am going to close this. We can discuss if we want to do BOLDING next (might be hard for non-English)
