### ISSUE TITLE
Outstanding IT tasks for Email

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#942]
1.	DOJ/SDS update the DKIM final info (Ticket opened and up for approval).
2.	GovDelivery team bind the domain and do a test (Final step for end of subdomain and DKIM setup).

**Comment by randyabramson** [comment]
Update

Only this is due
GovDelivery team bind the domain and do a test (Final step for end of subdomain and DKIM setup).

**Comment by ilodidoj** [comment]
DKIM bind completed.  Jill will update the new account information to be ready by COB Friday, 5/7/2021
