### ISSUE TITLE
Intake date and form letter response time zone mismatch

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#943]
## Narrative
As a CRT intake specialist, I want the form letter date/time to match the date/time of the public user's submission so there are no inconsistencies between the two.

## Background
The time zone for form letters is ahead of the submission time zone.  So, for complaints submitted for a few hours of every day, the form letter response will report a submission date that isn't accurate.  

## Solution
Set the time zone for date submitted to the eastern time zone.  This should prevent any future mismatches.

**Comment by randyabramson** [comment]
@blaughman I believe this is working, but I could use your second set of eyes.

I sent an email on STAGE and the 'last updated' time updated when I sent the Email + the 'activity log' updated with the correct time. Additionally, the email was delivered with the correct time stamp.

**Comment by blaughman** [comment]
Also 793-SNV works as intended in Staging.

**Comment by randyabramson** [comment]
Can't test on prod without sending a letter. @blaughman - please test when you send out a TMS mail. Closing for now and can re-open as needed.

**Comment by blaughman** [comment]
@randyabramson The fix works as intended in Prod.  A form letter was used to respond to ID: 86026-PDW
 and the intake date on the letter matched the date in the system.
