### ISSUE TITLE
Add Complaint ID # to the View All Table

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#962]
## User story:
As a CRT User, I want to see the complaint ID# in the view all table so that I can quickly locate a specific complaint for a writer that has submitted multiple complaints.

## Objective:
To improve efficiency for CRT Users processing complaints. 

## Key result:
By having the complaint ID # on the view all table (not nested in the expanded 'Carrot' view), CRT Users can be more efficient in their work.

## Ticket background:
CRT Users are often contacted by the public regarding complaints that were previously submitted.  A public complainant who submitted one complaint makes for easy processing.  CRT Users have expressed frustration when interacting with a public complainant who submitted multiple complaints.  The public complainant will reference their complaint ID # which isn’t easily accessible on the view all table.  

## Acceptance criteria:
1. Given I am on the View All Table
when I look at the columns
then I see a sortable column labeled "ID" in between the 'Total #' and 'Routed' columns

2. Given I am on View All Table
when I look at the ID column
then I see the ID numbers displayed for the associated records

3. Given I am on the View All Table
when I click the arrow to sort the ID column
then the records are displayed in a descending order
AND
when I click the arrow again the records are displayed in an ascending order

Design criteria: 
- [ ] The column header font is 16px. Change this to .75 REM 
   - [ ] verify that this is legible or revert the change
- [ ] Make the padding inside the cells .625 REM between the content and the edge of the cell on all sides
- [ ] Reducing the vertical space between the table and the filters/tags ( like 2.5 REM or 2.8 REM)

For accessibility, use REM instead of PX. Here is the guidance for more info: https://designsystem.digital.gov/documentation/accessibility/

## Mockup
![image](https://user-images.githubusercontent.com/6254621/120559353-e6ee7a80-c3ce-11eb-845e-09a894e3a608.png)

## Assumptions

- Adding this column is in conjunction with other View All Table changes.  'Summary' is moving to the expanded 'carrot' view (Card 961), 'Incident Location Name' is moving to the primary view.

**Comment by randyabramson** [comment]
Notes from Aviva on padding, etc.

* Right now the column header font is 16px, I think they can be 12px and will still be very legible being all caps
* I would try making the padding inside the cells just 10px between the content and the edge of the cell on all sides
* Try reducing the vertical space between the table and the filters/tags (in my mockup I think its only like 40 or 48px)

**Comment by LindsayYoung** [comment]
@randyabramson  I am adding your notes as acceptance criteria. We want to make sure that for your task, you can read the card and have all the task and acceptance criteria in one place. 

I also translated Aviva's note to REM, which is accessible for zooming and improves mobile experience too!

**Comment by LindsayYoung** [comment]
Just clarifying that descending order is alphabetical, since it it alphanumeric characters. We don't have leading zeros it's not in numeric order. If it needs to be in numeric order, we will want to sort by id in the filter while still displaying public id.s

If you want them in number order, currently you will want to sort by submitted date.

**Comment by randyabramson** [comment]
Works as expected on DEV on EDGE and CHROME. Moving to UAT Complete.

**Comment by randyabramson** [comment]
Works as expected on STAGING

**Comment by randyabramson** [comment]
Works as expected on PROD. Moving this to CLOSED
