### ISSUE TITLE
SPL Form Letter

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#965]
## User story:
As a SPL end user, I want a form letter so that I can reply to a majority of the incoming complaints for my section.

## Objective:
Give SPL end users the tool(s) necessary to complete their work.

## Key result:
Greater staff efficiency and reduced backlog.

## Ticket background:
The primary SPL form letter is used to respond to over 90% of all incoming correspondence.

## Acceptance criteria:
1. Given I am on the complaint detail page
when I click on the 'Contact complainant' button
then I see a list of form letters

2. Given I am on the 'Contact complainant' list of form letters
when I scroll the list sorted in alphabetical order
then I see a form letter labeled 'SPL - Standard Form Letter'

## Assumptions:
- This form letter will need translation into all the available languages

[SPL.Form.Letter (7) with Header Edit.docx](https://github.com/usdoj-crt/crt-portal-management/files/6976804/SPL.Form.Letter.7.with.Header.Edit.docx)

**Comment by blaughman** [comment]
[SPL Form Letter_SP.docx](https://github.com/usdoj-crt/crt-portal-management/files/6735920/SPL.Form.Letter_SP.docx)

Spanish Form letter.

**Comment by randyabramson** [comment]
@blaughman can you check back in with the LEP group to see where the vendor is on these?

**Comment by blaughman** [comment]
[212454cg-s_SPL.Form.Letter_SIMPLIFIED CHINESE_a1z.pdf](https://github.com/usdoj-crt/crt-portal-management/files/6933783/212454cg-s_SPL.Form.Letter_SIMPLIFIED.CHINESE_a1z.pdf)

**Comment by blaughman** [comment]
[212454cg-t_SPL.Form.Letter_TRADITIONAL CHINESE_a3z.pdf](https://github.com/usdoj-crt/crt-portal-management/files/6933788/212454cg-t_SPL.Form.Letter_TRADITIONAL.CHINESE_a3z.pdf)

**Comment by blaughman** [comment]
[212454ko_SPL.Form.Letter_KOREAN_a2z.pdf](https://github.com/usdoj-crt/crt-portal-management/files/6933790/212454ko_SPL.Form.Letter_KOREAN_a2z.pdf)

**Comment by blaughman** [comment]
[212454sg_SPL.Form.Letter_SPANISH_a3z.pdf](https://github.com/usdoj-crt/crt-portal-management/files/6933791/212454sg_SPL.Form.Letter_SPANISH_a3z.pdf)

**Comment by blaughman** [comment]
[212454ta_SPL.Form.Letter_TAGALOG_a4z.pdf](https://github.com/usdoj-crt/crt-portal-management/files/6933793/212454ta_SPL.Form.Letter_TAGALOG_a4z.pdf)

**Comment by blaughman** [comment]
[212454vi_SPL.Form.Letter_VIETNAMESE_a4z.pdf](https://github.com/usdoj-crt/crt-portal-management/files/6933795/212454vi_SPL.Form.Letter_VIETNAMESE_a4z.pdf)

**Comment by blaughman** [comment]
@randyabramson @ilodidoj @billyhunt Translations are added for all languages.

**Comment by billyhunt** [comment]
> [SPL Form Letter_SP.docx](https://github.com/usdoj-crt/crt-portal-management/files/6735920/SPL.Form.Letter_SP.docx)
> 
> Spanish Form letter.

@blaughman, @randyabramson, and @emilycryan,  the salutation of the spanish language translation is Estimad[o/a] with the last letter changing based on the gender of the person.  This might be a little complicated to implement.  Is it necessary to include the "Dear" at the beginning?

**Comment by randyabramson** [comment]
@billyhunt - I think we can forego the 'dear' at the beginning. I assume this may come into play for the other languages as well?

**Comment by billyhunt** [comment]
I am not sure.  I have not looked through everything. One thing I did notice in some of the other translations is that the variable names are also translated.  For example, [Submission Date] was in Tagalog, or something.  I can assume by placement that its going to be submission date, but we should definitely make sure when testing that it all lines up.  Does that make sense @randyabramson?

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by randyabramson** [comment]
Works as intended on CHROME and EDGE. Closing.
