### ISSUE TITLE
Hub link to Portal - login error

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#980]
## Summary

Internal users who click on the Portal admin link from http://mycrt/home/default/ or the HUB get a logon error

### Steps To Reproduce
1. Go to http://mycrt/home/default/ or the HUB in a browser other than IE Explorer (example: EDGE or CHROME)
2. Click on CRT Intake Portal 
3. Get 'Welcome to DOJ Federal Services' log in page

If it's relevant, add browser or operating system where the error occurs.
* PC, non IE browser

## Acceptance Criteria

1. Go to http://mycrt/home/default/ or the HUB in a browser other than IE Explorer (example: EDGE or CHROME)
2. Click on CRT Intake Portal 
3. Get  to https://crt-portal-django-prod.app.cloud.gov/form/view/ page

**Comment by randyabramson** [comment]
@ilodidoj assuming there isn't a way to test this on DEV or STAGING, correct?

**Comment by ilodidoj** [comment]
> @ilodidoj assuming there isn't a way to test this on DEV or STAGING, correct?

real test only can be done from HUB to portal or insider to portal.  We can mimic staging portal URL link saved on email and then click on that link should take you to the portal without error (this is not 100 test).  Validating from production is more apt for this.

**Comment by randyabramson** [comment]
OK @ilodidoj  we will test on Staging then. Moving to UAT complete.

**Comment by randyabramson** [comment]
Worked as expected in live environment. Moving to closed.
