### ISSUE TITLE
Email and Phone nudge

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#982]
## User story:
As a product owner, I want to provide a 'nudge' to users to remind them to enter their contact info (phone or Email) so that we can act on more reports.

## Objective:
The goal of this ticket is to provide sufficient information to our intake specialists so that they can act on reports when it's relevant.

## Key result:
We know that from June 2020 - February 2021, almost 10% of reports received did not include either phone or Email. We hope that after this nudge is in place that that total would drop to 7%.

## Ticket background:
* Original ticket with invision links at https://github.com/usdoj-crt/crt-portal-management/issues/872
* PopUp invision flow is at https://gsa.invisionapp.com/console/share/67ZRBQEDJWF/619008291

Screen grab of popup:

![image](https://user-images.githubusercontent.com/6254621/123843950-701aa380-d8e0-11eb-96c2-fc1a2ad1a568.png)

Email prompt, Version 2:
https://gsa.invisionapp.com/share/D9ZRD8Y24WK
(Actual screen / popup: https://gsa.invisionapp.com/share/D9ZRD8Y24WK#/screens/440802719)

## Acceptance criteria:

1. Given I am on the Contact page
when the complainant does not enter Email OR Phone info AND clicks NEXT
then I see a popup that requests that they fill in Email and/or Phone info

2. Given I am on the popup
when I click NO I DO NOT WANT TO PROVIDE IT
then I the popup CLOSES AND the dimming is reset AND I go to the next page of the form

3. Given I am on the popup
when I click YES I'D LIKE TO ADD IT
then the POP UP CLOSES AND the dimming is reset AND I am scrolled up to the EMAIL FIELD AND the cursor is placed in the Email Field

4. Given I filled in my EMAIL OR PHONE info
when I scroll down and click NEXT
then I go to the next page of the form

## Assumptions:
* Screen will dim when popup comes up as seen on the Human Trafficking pop up (https://github.com/usdoj-crt/crt-portal-management/issues/532)
* Follow the styling of card 532
* Email and phone format requirements still apply. If the user enters in an invalid format, they are alerted per the standing messaging

**Comment by randyabramson** [comment]
@ilodidoj @billyhunt @blaughman  - translations attached here

[1348581.Vietnamese.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/6810698/1348581.Vietnamese.final.docx)
[Spanish - translation - FINAL - from - Marta - 2021 06 14.docx](https://github.com/usdoj-crt/crt-portal-management/files/6810700/Spanish.-.translation.-.FINAL.-.from.-.Marta.-.2021.06.14.docx)
[1348577.Chinese_Simplfied_and_Traditional.Final.docx](https://github.com/usdoj-crt/crt-portal-management/files/6810701/1348577.Chinese_Simplfied_and_Traditional.Final.docx)
[1348579.Korean.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/6810702/1348579.Korean.final.docx)
[1348580.Tagalog.final.docx](https://github.com/usdoj-crt/crt-portal-management/files/6810703/1348580.Tagalog.final.docx)

**Comment by emilycryan** [comment]
![Mobile-Email+PhoneNudge](https://user-images.githubusercontent.com/73443807/125973171-d2777357-3e83-441e-81ac-2212db1e6ab9.png)
Here's the mobile mockup - the popup is 240 px wide with 18px inner padding. 18 pixels is also the spacing between the two buttons. Header is 18 pt, body copy is 14 pt. CC @billyhunt

**Comment by randyabramson** [comment]
@billyhunt  @ilodidoj  clean translations here and I will add them to the individual tickets.

[Chinese - Traditional - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881919/Chinese.-.Traditional.-.translation.-.FINAL.docx)
[Korean - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881920/Korean.-.translation.-.FINAL.docx)
[Spanish - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881921/Spanish.-.translation.-.FINAL.docx)
[Tagalog - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881922/Tagalog.-.translation.-.FINAL.docx)
[Vietnamese - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881923/Vietnamese.-.translation.-.FINAL.docx)
[Chinese - Simplified - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881924/Chinese.-.Simplified.-.translation.-.FINAL.docx)

**Comment by randyabramson** [comment]
@billyhunt  great work! Functions as expected on DEV on iPhone and desktop CHROME and EDGE. Would love to get this tested on ANDROID if possible. Moving to UAT Complete.

**Comment by randyabramson** [comment]
@ilodidoj I saw your note about the inconsistent language. If you are in there anyway, feel free to change all versions to 'No, I don't want to add it.' If not, it is fine to leave it as is.

**Comment by emilycryan** [comment]
@randyabramson and @ilodidoj  I'm assuming you're talking about "provide" vs "add". I'd advocate for leaving it as-is (two different words) because the word choice actually **highlights the difference between the two** even more specifically. Otherwise, you only have one word that is different, "yes" and "no" and it's much easier for a user to gloss over the phrase and select the wrong one, than it is if they are more different and actually cause the user to slow just a bit and read both in full.

**Comment by randyabramson** [comment]
Works as intended. Moving to STAGING

**Comment by blaughman** [comment]
Verified in Production.  Closing this card.
