### ISSUE TITLE
Research ClamAV error on New Relic and Kibana

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#985]
We are noticing some HTTP 429 errors from app "clamav-rest" in both staging and prod that seem to indicate that download of new virus definition files is being rate limited.
From the ClamAV docs: "If you are receiving a 429, that means you are rate limited. You’re downloading too fast or too much." 
In looking at the logs, suspect that both the staging and prod instance of this application are using the default value for refresh interval in the "freshclam.conf" file, which is 12 times per day. Would it be possible to dial this back a bit, to only check for updates a few times per day?

More information on configurable settings : https://github.com/ajilaag/clamav-rest#environment-variables
Information in docker hub: https://hub.docker.com/r/ajilaag/clamav-rest
ClamAV scan: https://www.clamav.net

Findings and suggestions:
Application is using current default setting for SIGNATURE_CHECKS, which is 24.  This needs to be reduced to a suitable number for each environment: dev, stage and prod.

**Comment by randyabramson** [comment]
No way to test until we add a live attachment, but assuming DEVs reduced SIGNATURE_CHECKS below 24. Closing ticket.
