### ISSUE TITLE
Prison Type Filter

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#986]
## User story:
As a CRT user, I want a filter for prison types so that I can easily categorize incoming complaints.

## Objective:
This feature will improve staff efficiency.

## Key result:
CRT SPL users will quickly determine which complaints are potentially within their jurisdiction.

## Ticket background:
SPL receives complaints involving conditions of confinement.  Their jurisdiction is limited to state/local correctional facilities.  The public complainant is required to identify the type of correctional facility on the complaint form, but there is no filter for this information on the back end.

## Acceptance criteria:
1) Given I am on the view all table
when I click the 'more' button
then I see a drop down filter labeled 'Prison type' as an available selection

2) Given I am on the view all table
when I click the 'Prison type' filter 
then I see four checkboxes with the following selections: 'State/Local'; 'Federal'; 'Private'; 'I'm not sure'

3) Given I am on the view all table
when I select a Prison type and click the 'Filter Results' button
then I see the view all table filters to display all records matching the selection
AND
I see a tag/label with the filtered criteria by the filtered data

## Assumptions
- CRT user can select more than one category in the filter
- ESC should close the filter box
- SPACE should open the box, working
- Reference closed card 927.  Language filter - should operate in same manner.

## Mockup
![image](https://user-images.githubusercontent.com/52507395/124636202-47515b80-de56-11eb-9cb0-a6098c3e6135.png)

**Comment by randyabramson** [comment]
@blaughman  is this good to move into the 'ready for dev' column?

**Comment by blaughman** [comment]
@randyabramson I moved it.

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by randyabramson** [comment]
Works as intended. Moving to staging.

**Comment by blaughman** [comment]
Verified in Production.  Closing this card.
