### ISSUE TITLE
Error View does not exist in module cts_forms.views

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#988]
New relic monitor reporting high frequency of csrf error:

Error Message
Could not import 'cts_forms.views.csrf_failure'. View does not exist in module cts_forms.views.

Logs needs to be reviewed for next corrective action.

**Comment by randyabramson** [comment]
@ilodidoj not sure how to test this. Moving to closed. Can re-open if necessary.
