### ISSUE TITLE
Email and Phone nudge - Espanol

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#989]
## User story:
As a public user I should be able to view the same Email and Phone nudge in Spanish Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment]
@billyhunt  translation here:

[Spanish - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881937/Spanish.-.translation.-.FINAL.docx)

**Comment by ilodidoj** [comment]
@randyabramson @blaughman It seems English to all language translations has a different format presentation than the English mock for this button: "**No, I don't want to provide it**" .  All other language version has this as "No, I **do not** want to provide it". Meaning is same, just the format presentation is different in all languages compare to English format of the button.

**Comment by randyabramson** [comment]
Works as intended...moving to staging.

**Comment by blaughman** [comment]
Verified in Production.  Closing this card.
