### ISSUE TITLE
Email and Phone nudge - Simplified Chinese

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#990]
## User story:
Email and Phone nudge in Simplified Chinese.  As a public user I should be able to view the same Email and Phone nudge in Simplified Chines Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment]
@billyhunt  translation here:

[Chinese - Simplified - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881933/Chinese.-.Simplified.-.translation.-.FINAL.docx)

**Comment by blaughman** [comment]
Function works as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment]
Works as intended. Moving to staging.

**Comment by blaughman** [comment]
Verified in Production.  Closing this card.
