### ISSUE TITLE
Email and Phone nudge - Traditional Chinese

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#991]
## User story:
Email and Phone nudge in Traditional Chinese.  As a public user I should be able to view the same Email and Phone nudge in Simplified Chines Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment]
@billyhunt  translation here:

[Chinese - Traditional - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881938/Chinese.-.Traditional.-.translation.-.FINAL.docx)

**Comment by blaughman** [comment]
Function works as intended.  Moving to UAT.

**Comment by randyabramson** [comment]
Works as intended. Moving to staging.

**Comment by blaughman** [comment]
Verified in Production.  Closing this card.
