### ISSUE TITLE
Email and Phone nudge - Vietnamese 

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#993]
## User story:
Email and Phone nudge in Vietnamese Language.  As a public user I should be able to view the same Email and Phone nudge in Vietnamese Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment]
@billyhunt  translation here:

[Vietnamese - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881946/Vietnamese.-.translation.-.FINAL.docx)

**Comment by blaughman** [comment]
Function works as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment]
Works as intended. Moving to Staging.

**Comment by blaughman** [comment]
Verified in Production.  Closing this card.
