### ISSUE TITLE
Email and Phone nudge - Tagalog

### ISSUE THREAD

**Issue by ilodidoj** [usdoj-crt/crt-portal-management#994]
## User story:
Email and Phone nudge in Tagalog Language.  As a public user I should be able to view the same Email and Phone nudge in Tagalog Language.

Refer to the following link for details and acceptance criteria.
Ref: https://github.com/usdoj-crt/crt-portal-management/issues/982

**Comment by randyabramson** [comment]
@billyhunt  translation here:

[Tagalog - translation - FINAL.docx](https://github.com/usdoj-crt/crt-portal-management/files/6881943/Tagalog.-.translation.-.FINAL.docx)

**Comment by blaughman** [comment]
Verified in Production.  Closing this card.
