### ISSUE TITLE
Splunk Research

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#995]
## User story:
As a Developer I will be able to configure all portal site log to a log aggregator and the redirect to an AWS S3 bucket location for irplog retreival.  

## Objective:
Meet DOJ compliance need for log aggregation to a central location.

## Tech Tasks (this will be completed by separate dev cards)
- [ ] Setup fluentdt on local docker with file and http logs
- [ ] Setup localstack s3 for log ingestion
- [ ] Setup fluentd on Dev circle ci and docker with s3 bucket
- [ ] Setup fluentd on Stage circle ci and docker with s3 bucket
- [ ] Setup fluentd on Prod circle ci and docker with s3 bucket

Note: Check for memory and local storage usage to determine additional memory and storage space needed for cloud.gov  post log aggregator implementation.
Current memory quota 12MB, used 9.5, free 2.5 before implementation.

## Ticket background:
Background info from Sean:

======

We have met with the cloud.gov team and have a proposed architecture that we think might meet the needs of the DOJ centralized logging initiative.

Below, is a reference architecture that DOD is using to pull logs from cloud.gov. 
 
Basically, the CRT team will create a small app in cloud.gov that will capture the logs and write them to S3 files. CRT will give DOJ the credentials for that S3 bucket. The DOJ Splunk team will have to pull the logs from cloud.gov, via an S3 bucket.

Here are the full details of how we can save the logs in a private S3 bucket using a data collector for unified logging.
https://github.com/cloud-gov/custom-fluentd

To recap, there are the alternatives we have discussed so far:

Streaming the logs from where they originate to Splunk
This method is in use on cloud.gov by the Federal Deposit Insurance Corporation (FDIC) and a few other agencies with similar needs. 

Previously, we discussed two methods of doing this:
 
1) Streaming the logs directly to Splunk. This is a common and easy way to distribute logs from cloud.gov and other CloudFoundry-based platforms to Splunk.

2) Streaming the logs to another log server. Then, Splunk pulls the logs.

DOJ will pull the logs from cloud.gov.

Other background:

Logs are currently being maintained and monitored in cloud.gov. CRT has access to them in a search and dashboard interfaces. The logs are retained to meet the FISMA moderate security needs of the app.

**Comment by blaughman** [comment]
Closing this card.  Tasks for implementation have been established.
